### ISSUE TITLE
How to reuse rd_kafka_t?

### ISSUE THREAD

**Issue by viniciuswebdev** [php-rdkafka/php-rdkafka#10]
Hi guys,

I was talking with @arnaud-lb about reuse rd_kafka_t to do not create different connections every message published, how can I help  you guys to do this?

Thanks for the project

**Comment by arnaud-lb** [comment]
Hi @viniciuswebdev,

A `RdKafka\Producer` instance uses a single `rd_kafka_t` instance by default. The example [here](https://github.com/arnaud-lb/php-rdkafka/blob/master/examples/producer.php) uses a single `rd_kafka_t`.
