### ISSUE TITLE
I  can't receive any error when produce mesage , although the Kafka server is not connected

### ISSUE THREAD

**Issue by yxw2014** [php-rdkafka/php-rdkafka#100]
$ret= $topic->produce(RD_KAFKA_PARTITION_UA, 0, json_encode($message));   

no return value， no Excepton， no Error message。

call rd_kafka_errno() always get 0

 * PHP version: 5.6
 * librdkafka version: 
 * php-rdkfaka version: 1.0.0

**Comment by yxw2014** [comment]
librdkafka version (runtime) => 0.9.2
librdkafka version (build) => 0.9.1.0

**Comment by arnaud-lb** [comment]
I @yxw2014 

You should set an error callback, and a delivery message callback:

```
$conf->setErrorCb(function ($kafka, $err) { ... });
$conf->setDrMsgCb(function ($kafka, err) { ... });
$kafka = new RdKafka\Producer($conf);
...
```

Also, you should call poll() after produce():

```
$topic->produce(...);
$kafka->poll(50);

// and when you have finished producing messages:
while ($kafka->getOutQLen() > 0) {
    $kafka->poll(50);
}
```

**Comment by yxw2014** [comment]
oh， thanks！
