### ISSUE TITLE
Segmentation fault for producer

### ISSUE THREAD

**Issue by allyraza** [php-rdkafka/php-rdkafka#102]
Hi, 

I am running mac osx have a basic producer script from examples which throws a segfault.

 * PHP version: 7.0
 * librdkafka version: 0.9.3
 * php-rdkfaka version: php70-rdkafka

**Comment by Nicofuma** [comment]
I have the same with php 5.6, librdkafka 0.9.2 and centos 7

Edit: no issue with the consumer 
Edit2: no issue with librdkafka 0.9.1

**Comment by merkerxu** [comment]
I got the same, I try set the _**optional RdKafka\Conf instance**_, and it works.

**Comment by arnaud-lb** [comment]
Hi

I believe that this bug has been fixed in php-rdkafka 3.x
