### ISSUE TITLE
pecl install: error: redefinition of typedef ‘kafka_object’

### ISSUE THREAD

**Issue by joaodlf** [php-rdkafka/php-rdkafka#104]
* PHP version: 5.6.29
 * librdkafka version: git clone https://github.com/edenhill/librdkafka (as of writing)
 * php-rdkfaka version: rdkafka-alpha

Running under centos-release-6-8.el6.centos.12.3.x86_64 and gcc 4.4.7, when I run:
`sudo pecl install channel://pecl.php.net/rdkafka-alpha`

I'm getting:

> /bin/sh /var/tmp/pear-build-root0JFps7/rdkafka-3.0.0/libtool --mode=compile cc  -I. -I/var/tmp/rdkafka -DPHP_ATOM_INC -I/var/tmp/pear-build-root0JFps7/rdkafka-3.0.0/include -I/var/tmp/pear-build-root0JFps7/rdkafka-3.0.0/main -I/var/tmp/rdkafka -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /var/tmp/rdkafka/rdkafka.c -o rdkafka.lo
libtool: compile:  cc -I. -I/var/tmp/rdkafka -DPHP_ATOM_INC -I/var/tmp/pear-build-root0JFps7/rdkafka-3.0.0/include -I/var/tmp/pear-build-root0JFps7/rdkafka-3.0.0/main -I/var/tmp/rdkafka -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /var/tmp/rdkafka/rdkafka.c  -fPIC -DPIC -o .libs/rdkafka.o
/var/tmp/rdkafka/rdkafka.c:59: error: redefinition of typedef ‘kafka_object’
/var/tmp/rdkafka/php_rdkafka_priv.h:216: note: previous declaration of ‘kafka_object’ was here
/var/tmp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__Kafka_setLogger’:
/var/tmp/rdkafka/rdkafka.c:563: warning: ‘rd_kafka_set_logger’ is deprecated (declared at /usr/local/include/librdkafka/rdkafka.h:2820)
make: *** [rdkafka.lo] Error 1
ERROR: `make' failed

**Comment by joaodlf** [comment]
Note, non pecl install (following https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.installation.manual.html) works :)

**Comment by merkerxu** [comment]
@joaodlf I got the same problem with the pecl 3.0.0 ext, just as the error describing:
`redefinition of typedef ‘kafka_object’`
in php_rdkafka_priv.h line 218:
```
typedef struct _kafka_object kafka_object;
```
but in php_rdkafka_priv.h  line 48-59:
```
typedef struct _kafka_object {
#if PHP_MAJOR_VERSION < 7
    zend_object             std;
#endif
    rd_kafka_type_t         type;
    rd_kafka_t              *rk;
    kafka_conf_callbacks    cbs;
    HashTable               consuming;
#if PHP_MAJOR_VERSION >= 7
    zend_object             std;
#endif
} kafka_object;
```
and this issue had been fixed by https://github.com/arnaud-lb/php-rdkafka/commit/317d4d9daa7af9f0607d5c99524947be1776e0ee

**Comment by arnaud-lb** [comment]
Hi!

I've just uploaded a new version on PECL with mentioned fix.
