### ISSUE TITLE
Invalid message size 

### ISSUE THREAD

**Issue by ktalebian** [php-rdkafka/php-rdkafka#106]
I'm getting the following error on consuming the kafka stream:

`
Receive failed: Invalid message size 1213486156 (0..1000000000): increase receive.message.max.bytes
`

Then increasing the byte size:

`
$conf = new RdKafka\Conf();
$conf->set('receive.message.max.bytes', 1213486156);
` 

gives me 

`
PHP Fatal error:  Uncaught exception 'RdKafka\Exception' with message 'Configuration property "receive.message.max.bytes" value 1213486156 is outside allowed range 1000..1000000000
`

Help is appreciated

**Comment by arnaud-lb** [comment]
Hi

Did you try specifying the Kafka Server's version ? https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
