### ISSUE TITLE
Can i connect to the Brokers by zookeeper?

### ISSUE THREAD

**Issue by Kooooooma** [php-rdkafka/php-rdkafka#109]
As what i said in the title.

**Comment by arnaud-lb** [comment]
Yes, you can use the [Zookeeper extension](https://github.com/andreiz/php-zookeeper) to fetch the list of brokers, and then connect to the brokers. This way, you only have to know the address of the zookeeper nodes.

Personally, I do it the other way around: My code only knows the address of 3 Kafka nodes, and never talks to Zookeeper. I find this simpler.
