### ISSUE TITLE
Rdkafka messes up my exception handling

### ISSUE THREAD

**Issue by juliusza** [php-rdkafka/php-rdkafka#111]
Why have you added zend_replace_error_handling in PHP_METHOD(RdKafka__TopicPartition, __construct)? This messes up my PHP NOTICE -> exception handling. I've removed this code and seems to work fine.

**Comment by arnaud-lb** [comment]
Hi @juliusza

Well spotted, this is a bug. This code was supposed to restore the previous error handling after that.

**Comment by arnaud-lb** [comment]
Fixed. It's common in native PHP constructors to set the error handling to "throw", because this is the only way a constructor can report errors. However, this particular constructor forgot to restore the original error handling before returning.
