### ISSUE TITLE
undefined symbol: object_properties_init

### ISSUE THREAD

**Issue by gspiegelberg** [php-rdkafka/php-rdkafka#12]
CentOS 6
# phpize

Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626

Performed make, added extension to php.ini and make tests says...
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/gspiegel/src/kafka/php-rdkafka/modules/rdkafka.so' - /home/gspiegel/src/kafka/php-rdkafka/modules/rdkafka.so: undefined symbol: object_properties_init in Unknown on line 0

TIA.

**Comment by arnaud-lb** [comment]
Hi @gspiegelberg,

Which PHP version are you using ?

**Comment by gspiegelberg** [comment]
Have tried 5.3.3 and 5.3.10 under Cent 6.  Whatever version comes with Cent 7 works fine but I need to wedge this onto a Cent 6 platform.

**Comment by arnaud-lb** [comment]
@gspiegelberg this has been fixed. Note that you have to re-run phpize, configure before make.
