### ISSUE TITLE
can't consume msg produced by kafka-php

### ISSUE THREAD

**Issue by sjp00556** [php-rdkafka/php-rdkafka#120]
* PHP version:7.0.13
 * librdkafka version:0.9.1
 * php-rdkfaka version:2.0.0

Hello,

I'm  using kafka-php client to produce msg (becaues it has smaller latency),  msgs can successfully consumed by kafka-php client or kafka-console-consumer.sh. However, when i'm using php-rdkafka to consume these msgs ( which kafka-php created ) , the consumer script can't read msg and hanged up.  is this a bug or phprdkafka is incompatible with kafka-php producer?

thanks for your help!

**Comment by sjp00556** [comment]
php-rdkafka produce msg has a very high latency in php-fpm env (60ms +)  and i'm already set socket.blocking.max.ms =1 ,

**Comment by sjp00556** [comment]
it maybe the protocal incompatible.  use broker 0.10+ can solve this problem....

**Comment by arnaud-lb** [comment]
You can use the `api.version.request=false` + `broker.version.fallback=0.8` settings if you are using a 0.8 broker.
