### ISSUE TITLE
Enable librdkafka's statistics 

### ISSUE THREAD

**Issue by vadimiron** [php-rdkafka/php-rdkafka#121]
It would be nice, if it would be possible to get statistics of librdkafka - for example, as a callback (Conf class)
https://github.com/edenhill/librdkafka/wiki/Statistics

Thank you very much in advance!

 * PHP version: 7.1
 * librdkafka version: 0.9.5
 * php-rdkfaka version: 3.0.3

**Comment by arnaud-lb** [comment]
👍  would be easy to add a `RdKafka\Conf::setConfCb()` method

**Comment by tPl0ch** [comment]
@arnaud-lb Isn't this already implemented in https://github.com/arnaud-lb/php-rdkafka/blob/93e618242176585efd192ac4b6baf8c2ac3ed712/conf.c#L484 and could be closed?

Or this is rather a missing documentation issue I guess, since `RdKafka\Conf::setStatsCb(callable $callback)` is not documented.

**Comment by arnaud-lb** [comment]
You are right, I'm adding the doc label

**Comment by nick-zh** [comment]
@arnaud-lb this has been added to the doc and can be closed
