### ISSUE TITLE
Message compression and validation issue

### ISSUE THREAD

**Issue by balajivenki** [php-rdkafka/php-rdkafka#123]
Our messages can be as high as 40MB+ so we enabled compression using compression.codec to snappy. The issue we faced was since the actual message is more than message.max.bytes(10MB) the message was not published to Kafka. After we enabled compression the compressed messages came down < 10MB in size, however the message sending still fails and it looks like the size validation is done to the message before compression and not after compression. Can you please take a look at it.

 * PHP version: 5.6.x
 * librdkafka version: librdkafka-0.9.3
 * php-rdkfaka version: php-rdkafka-3.0.1

**Comment by nick-zh** [comment]
@balajivenki i am late to the party, if you still have this issue, you can set `message.max.bytes` that you mention on the broker side, this should fix this. If it works or you found the solution anyway, feel free to close this issue :smile:

**Comment by nick-zh** [comment]
@arnaud-lb i think this can be closed
