### ISSUE TITLE
Script hangs in RdKafka\Consumer destructor

### ISSUE THREAD

**Issue by arnaud-lb** [php-rdkafka/php-rdkafka#126]
When using php-rdkafka <= 3.0.3 with librdkafka >= 0.9, the php script can hang during the destruction of a RdKafka\Consumer object. This happens when a RdKafka\Queue object outlives the related Consumer object.

**Comment by arnaud-lb** [comment]
This issue has been fixed in php-rdkafka 3.0.4.

**Comment by lzyRun** [comment]
@arnaud-lb it doesn`t work。the script still hang
