### ISSUE TITLE
Control log output when using the high level consumer

### ISSUE THREAD

**Issue by kristophjunge** [php-rdkafka/php-rdkafka#127]
* PHP version: 7.1.6 (cli)
 * librdkafka version: 0.9.5
 * php-rdkfaka version: 3.0.4

Hello,

by reading issue #81 i found the undocumented method "setLogger". By setting it to "RD_KAFKA_LOG_SYSLOG" i can suppress the output to stdout and stderr which is at least a workaround. 

But in my situation iam using the high level consumer as shown in the [example](https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-high-level-consumer.html).

The class "RdKafka\KafkaConsumer" used for a high level consumer does not contain the "setLogger" method. 

So its currently not possible for me to suppress the log output when using high level consumers.

* Am i missing something here? The other invoked classes "RdKafka\Conf" and "RdKafka\TopicConf" also do not contain the method.
* Why dosent the class "RdKafka\KafkaConsumer" contain the "setLogger" method? Is that on purpose? Would it be possible to add it there?

Thanks

**Comment by nick-zh** [comment]
@kristophjunge i would say it's similar to what i've answered in #81 
Here is some example code that should work for you, let me know if you need more help on this:

```
<?php

declare(strict_types=1);

use RdKafka\Conf;
use RdKafka\KafkaConsumer;

$conf = new Conf();
$conf->set('group.id', 'test');
$conf->set('metadata.broker.list', 'localhost:9999');

$conf->setErrorCb(function ($kafka, int $errorCode, string $errorMsg) {
    throw new \RuntimeException($errorMsg, $errorCode);
});

$consumer = new KafkaConsumer($conf);

$consumer->subscribe(['test']);

try {
    $message = $consumer->consume(12 * 1000);
} catch (RuntimeException $e) {

}
```
