### ISSUE TITLE
Uncaught RdKafka\Exception: Local: Broker transport failure

### ISSUE THREAD

**Issue by zuoRambo** [php-rdkafka/php-rdkafka#128]
* PHP version: PHP 7.0.22 (cli) (built: Aug  7 2017 14:07:27) ( NTS ) Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
 * librdkafka version: stable 0.11.0 (bottled), HEAD
 * php-rdkfaka version: stable 2.0.1 (bottled), HEAD
 * OS version: MacOs 10.12.1 

```php
$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("192.168.10.35.25:9092,192.168.5.220:9092,192.168.35.189:9092");
$topic = $rk->newTopic("rambone-topic");
var_dump($rk->getMetadata(true, $topic, 0));
```

I get the follow Exception: `PHP Fatal error:  Uncaught RdKafka\Exception: Local: Broker transport failure`.

**Comment by zuoRambo** [comment]
Kafka-Server version: 0.10.2.0-1

**Comment by nick-zh** [comment]
@zuoRambo is this still a problem or can this be resolved?
