### ISSUE TITLE
Allow users to search offsets by timestamp on partitions

### ISSUE THREAD

**Issue by chrisLeeTW** [php-rdkafka/php-rdkafka#130]
As of 0.10.0.1 the java library lets users seek to offsets based on timestamp.

https://kafka.apache.org/documentation#upgrade_1010_notable

And also offsets_for_times() support was added to librdkafka.

**Comment by nick-zh** [comment]
@arnaud-lb any update / plans on this? Having support for https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2695 would be really great.
Sadly my C knowledge is very very rusty, so it would take me quite a while to contribute this.
Cheers,
Nick

**Comment by nick-zh** [comment]
@arnaud-lb i think we can close this after doc is merged, thanks in advance :+1:
