### ISSUE TITLE
Synchronous Mode & Callbacks called after destructors

### ISSUE THREAD

**Issue by magic-m-johnson** [php-rdkafka/php-rdkafka#134]
Hey,

I have an implementation where I read messages from a database and want to delete them once successfully produced. I only want to produce the next message if the current one was successful and also delete the entry from the database. So i put everything in a closure, called it for the first message and tried to call it for the next message in the error-free dr_msg callback. 

This is roughly the logic I tried to build:
```
function Closure(message) {
    Kafka->onSucces(function(){
        DeleteFromDb() && Closure(nextMessage)
    })

    Kafka->produce(message)
}

Closure(firstMessage)
```
Unfortunately this didn't work since the success-callback seems to be called too late. Do you have an idea how to go about this? 

Also, I read about some synchronous mode for producing. Is this a planned or available feature, so that I could just loop my data the old-fashioned way?

Greetings and thanks in advance.

**Comment by arnaud-lb** [comment]
Hi,

Try calling poll() after produce(). E.g. something like this:

```
while ($producer->getOutQLen() > 0) {
    $producer->poll(1);
}
```
