### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by ixqbar** [php-rdkafka/php-rdkafka#135]
php-rdkafka/rdkafka.c:585:5: warning: 'rd_kafka_set_logger' is deprecated [-Wdeprecated-declarations]
    rd_kafka_set_logger(intern->rk, logger);

librdkafka/rdkafka.h:2999:6: note: 'rd_kafka_set_logger' has been explicitly marked deprecated here
void rd_kafka_set_logger(rd_kafka_t *rk,

php-rdkafka/topic.c:144:15: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
        err = rd_kafka_errno2err(errno);

**Comment by arnaud-lb** [comment]
These are used in order to keep backwards compatibility with previous php-rdkafka versions. rd_kafka_set_logger() allows to implement Consumer::setLogger(), for instance.
