### ISSUE TITLE
Find messages by key

### ISSUE THREAD

**Issue by artekpol** [php-rdkafka/php-rdkafka#137]
Is it possible to fetch messages by key.
eg. 
I was produced two messages with the same key and another one with different key:
1 -> message A
1-> message B
3 -> message C
Now, I want to fetch all messages with key=1. (A, B).
Is it possible ?

**Comment by arnaud-lb** [comment]
librdkafka allows this, but that's not in php-rdkafka yet. Contributions welcome :)

**Comment by tPl0ch** [comment]
@arnaud-lb How does `librdkafka` allow for this? The only way I found would be through the `on_consume()` interceptor and piping the messages with a specific key into a separate receiver. 

Any other way this could be done?

**Comment by nick-zh** [comment]
@arnaud-lb i don't think this is possible, at least i was unable to find how to do this in librdkafka, i might be mistaken though. Let me know, if there is a way, i will try to contribute.
