### ISSUE TITLE
Unable to install the extension using PECL

### ISSUE THREAD

**Issue by kebab-mai-haddi** [php-rdkafka/php-rdkafka#138]
I want to install php-rdkafka. While following the instructions [here](https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.installation.html), I decided to install using the [step 1](https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.installation.pecl.html).

The first thing that I did was to install pecl. After that, I am stuck on it and unable to install the extension.

For the screenshot, click [here](https://drive.google.com/file/d/1CFVbGV_5Pe9FaM71-qmCcd4eqpbUp_kE/view?usp=sharing).

**Comment by kebab-mai-haddi** [comment]
@arnaud-lb Thanks for the extension, could you please guide me here.

Thank you!

**Comment by arnaud-lb** [comment]
Hi @avisrivastava254084 

If seems that `configure` can not find librdkafka/rdkafka.h. This probably means that librdkafka is not installed on your system, or that you didn't install the dev headers (e.g. if you installed it with `apt`, make sure that you installed `-dev` package).
