### ISSUE TITLE
Problem with Low Level Consumer (multiple topics)

### ISSUE THREAD

**Issue by mateusmaaia** [php-rdkafka/php-rdkafka#139]
Hello!

I´m having a little trouble to work with multiple topics, I always receive an error (-191) for each topic that I'm listening. I'm using kafka 0.11.

My code base is:

```
  $rk = new RdKafka\Consumer();
        $queue = $rk->newQueue();        
        $topicConf = new RdKafka\TopicConf();         
        $rk->addBrokers("kafka");        
        $vocabulary = taxonomy_vocabulary_machine_name_load('client');
        $terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));

        foreach ($terms as $terms->name => $client) {
                $topic[$client->name] = $rk->newTopic($client->name, $topicConf);
                $topic[$client->name]->consumeQueueStart(0, kafka_user_offset($client->name), $queue);
        }
        
        while (true){                   
            $msg_user = $queue->consume(1000); 
        ... }
```

When I start that queue I recieve this log for each topic:

`RdKafka\Message Object ( [err] => -191 [topic_name] => 'TOPIC_NAME' [partition] => 0 [payload] => [key] => [offset] => 0 )`

There´s something that I'm missing? There´s a lot of messages to be consumed in each topic, but my application don´t see it. It only happens if I'm using queue mode, for single topic it works normally.

**Comment by arnaud-lb** [comment]
Hi @mateusmaaia 

-191 is RD_KAFKA_RESP_ERR__PARTITION_EOF, which means that the consumer has hit the end of a partition. This is not really an error, and you can safely continue consuming, as shown in the examples: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-low-level-consumer-basic.html

You can disable these by setting `enable.partition.eof` to `"false"`.

Note that you can get a human readable error by calling $message->errstr().
