### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by bo2018** [php-rdkafka/php-rdkafka#14]
memory of php-fpm worker process continues to grow , does anyone else have the same problem? thanks

**Comment by arnaud-lb** [comment]
@bobobreakwall: if you are consuming topics from an offset way behind the tail of the topic and/or from many partitions, librdkafka will buffer of lot of messages by default.

You might want to reduce `queued.max.messages.kbytes` https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by arnaud-lb** [comment]
I've added a section about this in the readme: https://github.com/arnaud-lb/php-rdkafka/blob/master/README.md#queuedmaxmessageskbytes

**Comment by bo2018** [comment]
Thanks for your reply and sorry for the unclear question, below is the test code:

<?php

pcntl_sigprocmask(SIG_BLOCK, array(SIGIO)); 

$conf = new RdKafka\Conf();
$conf->set('receive.message.max.bytes',1000000);
$conf->set('internal.termination.signal', SIGIO);
$conf->set('topic.metadata.refresh.sparse',true);
$conf->set('topic.metadata.refresh.interval.ms',600000);
$conf->set('queued.max.messages.kbytes',1000);
$conf->set('socket.send.buffer.bytes',1000000);
$conf->set('queue.buffering.max.messages',100);
//$conf->set('queue.buffering.max.ms',1);

$kfk = new RdKafka\Producer($conf);
$kfk->setLogLevel(LOG_ERR);
$kfk->addBrokers("10.144.12.22:9092,10.163.96.163:9092,10.144.224.132:9092");

$confTopic = new RdKafka\TopicConf();
$confTopic->set('request.required.acks', 0);
$topic = $kfk->newTopic('wbzk1',$confTopic);

try{
     $ret = $topic->produce(RD_KAFKA_PARTITION_UA, 0, str_pad('',50000,'a'));
}catch(RdKafka\Exception $e){
     var_dump($e);
     exit();
}

and the php-fpm.conf file:

[global]
pid = /usr/local/php/var/run/php-fpm.pid
error_log = /usr/local/php/var/log/php-fpm.log
log_level = notice

[www]
listen = /tmp/php-cgi.sock
listen.backlog = -1
listen.allowed_clients = 127.0.0.1
listen.owner = www
listen.group = www
listen.mode = 0666
user = www
group = www
pm = dynamic
pm.max_children = 20
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 6
pm.max_requests = 100000
request_terminate_timeout = 100
request_slowlog_timeout = 0
slowlog = var/log/slow.log

I did all configurations  I could find, but the memory still  continues to grow

**Comment by arnaud-lb** [comment]
By how much is the memory usage growing ?

I can not reproduce the issue here: in FPM, the memory usage shown by _top_ doesn't grows in a significant manner. When executed in command line, the script finishes without any memory leak under valgrind / without zend alloc.

**Comment by bo2018** [comment]
Finally I found it's the "addBrokers"  function  that  contributed to the memory growth , memory of php-fpm process is increased to  almost 100M after processed 100000 requests, below is the test code:

$kfk = new RdKafka\Producer(); 
$kfk->addBrokers("10.144.12.22:9092");
exit();

**Comment by bo2018** [comment]
@arnaud-lb can you reproduce this issue now?

**Comment by edenhill** [comment]
@bobobreakwall Can you try running your program with valgrind?

`valgrind --leak-check=full php /your/script.php`

**Comment by arnaud-lb** [comment]
@bobobreakwall @edenhill I wasn't able to reproduce the issue on my side. Valgrind shows no memory leak related to the extension or librdkafka.

@bobobreakwall Note that you have to disable the zend memory allocator when running valgrind, else memory allocated by php or the extension are hidden from valgrind:

```
USE_ZEND_ALLOC=0 valgrind --leak-check=full php /your/script.php
```

**Comment by bo2018** [comment]
Please note that valgrind  does not detect this memory error every time  , After following this tutorial :https://bugs.php.net/bugs-getting-valgrind-log.php ,it outputs   :

[root@iZ28gp4s5kaZ trade]# valgrind --leak-check=full php v2produce.php 
==23817== Memcheck, a memory error detector
==23817== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==23817== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==23817== Command: php v2produce.php
==23817== 
==23817== 
==23817== HEAP SUMMARY:
==23817==     in use at exit: 6,974 bytes in 19 blocks
==23817==   total heap usage: 15,851 allocs, 15,832 frees, 3,216,655 bytes allocated
==23817== 
==23817== 288 bytes in 1 blocks are possibly lost in loss record 12 of 18
==23817==    at 0x4A057BB: calloc (vg_replace_malloc.c:593)
==23817==    by 0x34DC811952: _dl_allocate_tls (in /lib64/ld-2.12.so)
==23817==    by 0x34DD4071E8: pthread_create@@GLIBC_2.2.5 (in /lib64/libpthread-2.12.so)
==23817==    by 0x551F89B: rd_kafka_broker_add (rdkafka_broker.c:4348)
==23817==    by 0x551FB66: rd_kafka_brokers_add (rdkafka_broker.c:4482)
==23817==    by 0x5309298: zim_RdKafka__Kafka_addBrokers (rdkafka.c:818)
==23817==    by 0x884D5D: zend_do_fcall_common_helper_SPEC (zend_vm_execute.h:550)
==23817==    by 0x885530: ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (zend_vm_execute.h:685)
==23817==    by 0x884455: execute_ex (zend_vm_execute.h:363)
==23817==    by 0x8844D8: zend_execute (zend_vm_execute.h:388)
==23817==    by 0x843CB2: zend_execute_scripts (zend.c:1327)
==23817==    by 0x7AC42F: php_execute_script (main.c:2525)
==23817== 
==23817== 3,516 (248 direct, 3,268 indirect) bytes in 1 blocks are definitely lost in loss record 18 of 18
==23817==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==23817==    by 0x809F47: _emalloc (zend_alloc.c:2427)
==23817==    by 0x7E56FE: compile_file (zend_language_scanner.l:556)
==23817==    by 0x67B2BB: phar_compile_file (phar.c:3388)
==23817==    by 0x843BD3: zend_execute_scripts (zend.c:1319)
==23817==    by 0x7AC42F: php_execute_script (main.c:2525)
==23817==    by 0x8F7090: do_cli (php_cli.c:994)
==23817==    by 0x8F8125: main (php_cli.c:1378)
==23817== 
==23817== LEAK SUMMARY:
==23817==    definitely lost: 248 bytes in 1 blocks
==23817==    indirectly lost: 3,268 bytes in 6 blocks
==23817==      possibly lost: 288 bytes in 1 blocks
==23817==    still reachable: 3,170 bytes in 11 blocks
==23817==         suppressed: 0 bytes in 0 blocks
==23817== Reachable blocks (those to which a pointer was found) are not shown.
==23817== To see them, rerun with: --leak-check=full --show-reachable=yes
==23817== 
==23817== For counts of detected and suppressed errors, rerun with: -v
==23817== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 6 from 6)

[root@iZ28gp4s5kaZ trade]# valgrind --leak-check=full php v2produce.php 
==26517== Memcheck, a memory error detector
==26517== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==26517== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==26517== Command: php v2produce.php
==26517== 
%5|1448614516.437|TOPICBRK|rdkafka#producer-0| Topic wbzk333 [0] migrated to unknown broker 0: requesting metadata update
%5|1448614516.480|TOPICBRK|rdkafka#producer-0| Topic wbzk333 [0] migrated to unknown broker 0: requesting metadata update
==26517== 
==26517== HEAP SUMMARY:
==26517==     in use at exit: 9,310 bytes in 20 blocks
==26517==   total heap usage: 15,936 allocs, 15,916 frees, 3,303,398 bytes allocated
==26517== 
==26517== 288 bytes in 1 blocks are possibly lost in loss record 12 of 19
==26517==    at 0x4A057BB: calloc (vg_replace_malloc.c:593)
==26517==    by 0x34DC811952: _dl_allocate_tls (in /lib64/ld-2.12.so)
==26517==    by 0x34DD4071E8: pthread_create@@GLIBC_2.2.5 (in /lib64/libpthread-2.12.so)
==26517==    by 0x551F89B: rd_kafka_broker_add (rdkafka_broker.c:4348)
==26517==    by 0x5528A5F: rd_kafka_broker_metadata_reply (rdkafka_broker.c:4525)
==26517==    by 0x5523C66: rd_kafka_recv (rdkafka_broker.c:1342)
==26517==    by 0x5524ADF: rd_kafka_broker_io_serve (rdkafka_broker.c:2527)
==26517==    by 0x55268BE: rd_kafka_broker_thread_main (rdkafka_broker.c:2550)
==26517==    by 0x34DD4079D0: start_thread (in /lib64/libpthread-2.12.so)
==26517==    by 0x6F406FF: ???
==26517== 
==26517== 2,384 bytes in 1 blocks are possibly lost in loss record 18 of 19
==26517==    at 0x4A05588: memalign (vg_replace_malloc.c:727)
==26517==    by 0x34DC81118F: tls_get_addr_tail (in /lib64/ld-2.12.so)
==26517==    by 0x34DC81165F: __tls_get_addr (in /lib64/ld-2.12.so)
==26517==    by 0x552ED81: rd_addrinfo_prepare (rdaddr.c:97)
==26517==    by 0x552EF5D: rd_getaddrinfo (rdaddr.c:153)
==26517==    by 0x552675E: rd_kafka_broker_thread_main (rdkafka_broker.c:580)
==26517==    by 0x34DD4079D0: start_thread (in /lib64/libpthread-2.12.so)
==26517==    by 0x79416FF: ???
==26517== 
==26517== 3,468 (248 direct, 3,220 indirect) bytes in 1 blocks are definitely lost in loss record 19 of 19
==26517==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==26517==    by 0x809F47: _emalloc (zend_alloc.c:2427)
==26517==    by 0x7E56FE: compile_file (zend_language_scanner.l:556)
==26517==    by 0x67B2BB: phar_compile_file (phar.c:3388)
==26517==    by 0x843BD3: zend_execute_scripts (zend.c:1319)
==26517==    by 0x7AC42F: php_execute_script (main.c:2525)
==26517==    by 0x8F7090: do_cli (php_cli.c:994)
==26517==    by 0x8F8125: main (php_cli.c:1378)
==26517== 
==26517== LEAK SUMMARY:
==26517==    definitely lost: 248 bytes in 1 blocks
==26517==    indirectly lost: 3,220 bytes in 6 blocks
==26517==      possibly lost: 2,672 bytes in 2 blocks
==26517==    still reachable: 3,170 bytes in 11 blocks
==26517==         suppressed: 0 bytes in 0 blocks
==26517== Reachable blocks (those to which a pointer was found) are not shown.
==26517== To see them, rerun with: --leak-check=full --show-reachable=yes
==26517== 
==26517== For counts of detected and suppressed errors, rerun with: -v
==26517== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 6 from 6)

**Comment by edenhill** [comment]
Those leaks look like false positive glibc TLS internals and can probably be ignored.
