### ISSUE TITLE
errstr() function return payload if it is string

### ISSUE THREAD

**Issue by sofire** [php-rdkafka/php-rdkafka#143]
* PHP version:5.6
 * librdkafka version: 0.11.3
 * php-rdkfaka version:3.0.5

$message->errstr() function return payload if it is string. 
Is it a bug or not?

...
zpayload = rdkafka_read_property(NULL, getThis(), ZEND_STRL("payload"), 0 TSRMLS_CC);

    if (zpayload && Z_TYPE_P(zpayload) == IS_STRING) {
        RETURN_ZVAL(zpayload, 1, 0);
    }
...

**Comment by TiMESPLiNTER** [comment]
Same for PHP 7

**Comment by arnaud-lb** [comment]
Not a bug :)

The `payload` field actually contains an error string when the `err` field is non zero (like in librdkafka: https://github.com/edenhill/librdkafka/blob/c3d50eb613704fb9c8ab3bce95a88275cb5875b7/src/rdkafka.h#L1053)

It's not valid to call `errstr()` when `err` is zero.

**Comment by sofire** [comment]
Thanks for reply.

in librdkafka:
	void   *payload;           /**< Producer: original message payload.
				    * Consumer: Depends on the value of \c err :
				    * - \c err==0: Message payload.
				    * - \c err!=0: Error string */

for Producer, if err should use 
  rd_kafka_err2str($message->err)

**Comment by arnaud-lb** [comment]
errstr() is basically an alias for `rd_kafka_err2str($message->err)`

**Comment by nick-zh** [comment]
@arnaud-lb https://github.com/arnaud-lb/php-rdkafka/blob/master/message.c#L90
for v3.0.5 i still get the payload as errstr e.g. i had err -192 and message->errstr gives me the payload
