### ISSUE TITLE
1 second timeout on every connection close. Why so?

### ISSUE THREAD

**Issue by blurayman** [php-rdkafka/php-rdkafka#145]
We anallyzed why our scripts are so slow on writing data to kafka queue using php-rdkafka and found out that writing takes less than 0.03 sec, but all the php-fpm script works more than 1 sec. We profiled it and found the problem in closing connection method. Inside it we found delay in 1 second in sources:

https://github.com/arnaud-lb/php-rdkafka/blob/6f6f4b046b5bd0bdd8e2ed1aab82b37566ac57d7/rdkafka.c#L772

We reviewed the history of commits for this line and saw no proper comments descibing why this delay had been made.

Is there a special need to be stuck for 1 second? The problem is that this delay makes all the php-fpm process be stuck and don't close. In our php-fpm config there is a restriction for 100 concurent processes. If you make many write requests at the same time (e.g. 60 rps) and stuck for 1 sec each then you'll have soon Gateway timeout error from web server.

**Comment by awons** [comment]
```
rdkafka-3.0.5
```
```
php -v
PHP 7.1.11 (cli) (built: Oct 29 2017 17:26:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
```
 php -i | grep kafka
/etc/php.d/rdkafka.ini,
rdkafka
rdkafka support => enabled
librdkafka version (runtime) => 0.11.3
librdkafka version (build) => 0.11.3.0
```

We encountered exactly the same issue. Although it looks completely random.
The simplest script to show what is happening is this:

```php
use RdKafka\Conf;
use RdKafka\Producer;

for ($i = 0; $i < 30; $i++) {
    sendMessage();
}

function sendMessage()
{
    echo sprintf("\nCreate new producer at %s\n", microtime(true));

    $conf = new Conf();
    $conf->set('debug', 'all');

    $producer = new Producer($conf);
    $producer->addBrokers('kafka:9092');

    echo sprintf("Producer destruction started at %s\n", microtime(true));
}
```

First output is when everything went fine and destruction took in total around 100ms:
```
Create new producer at 1518181626.7224
%7|1518181626.727|WAKEUPFD|rdkafka#producer-1| [thrd:app]: kafka:9092/bootstrap: Enabled low-latency partition queue wake-ups
%7|1518181626.727|WAKEUPFD|rdkafka#producer-1| [thrd:app]: kafka:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1518181626.727|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1518181626.727|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1518181626.727|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1518181626.727|BROKER|rdkafka#producer-1| [thrd:app]: kafka:9092/bootstrap: Added new broker with NodeId -1
Producer destruction started at 1518181626.7271
%7|1518181626.727|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:app]: Interrupting timers
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:app]: Sending TERMINATE to main background thread
%7|1518181626.727|BRKMAIN|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Enter main broker thread
%7|1518181626.727|CONNECT|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: broker in state INIT connecting
%7|1518181626.727|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1518181626.727|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:main]: Purging reply queue
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:main]: Decommissioning internal broker
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:main]: Join 2 broker thread(s)
%7|1518181626.727|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 fetch toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1518181626.727|BROADCAST|rdkafka#producer-1| [thrd:app]: Broadcasting state change
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:app]: Joining main background thread
%7|1518181626.727|CONNECT|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connecting to ipv4#172.19.0.4:9092 (plaintext) with socket 7
%7|1518181626.727|STATE|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1518181626.727|BROADCAST|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: Broadcasting state change
%7|1518181626.727|TERMINATE|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181626.727|BROKERFAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)
%7|1518181626.727|STATE|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1518181626.728|BROADCAST|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: Broadcasting state change
%7|1518181626.728|BUFQ|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Purging bufq with 0 buffers
%7|1518181626.728|BUFQ|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Updating 0 buffers on connection reset
%7|1518181626.827|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181626.827|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1518181626.827|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN
%7|1518181626.827|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1518181626.827|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1518181626.827|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1518181626.827|TERMINATE|rdkafka#producer-1| [thrd:main]: Main background thread exiting
%7|1518181626.827|TERMINATE|rdkafka#producer-1| [thrd:app]: Destroying op queues
%7|1518181626.827|TERMINATE|rdkafka#producer-1| [thrd:app]: Termination done: freeing resources
```

And here is the output when it takes over 1000ms:

```
Create new producer at 1518181627.3481
%7|1518181627.348|BRKMAIN|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1518181627.348|STATE|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1518181627.348|BROADCAST|rdkafka#producer-8| [thrd::0/internal]: Broadcasting state change
%7|1518181627.348|WAKEUPFD|rdkafka#producer-8| [thrd:app]: kafka:9092/bootstrap: Enabled low-latency partition queue wake-ups
%7|1518181627.348|WAKEUPFD|rdkafka#producer-8| [thrd:app]: kafka:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1518181627.349|BROKER|rdkafka#producer-8| [thrd:app]: kafka:9092/bootstrap: Added new broker with NodeId -1
%7|1518181627.349|BRKMAIN|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Enter main broker thread
Producer destruction started at 1518181627.349
%7|1518181627.349|CONNECT|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: broker in state INIT connecting
%7|1518181627.349|DESTROY|rdkafka#producer-8| [thrd:app]: Terminating instance
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:app]: Interrupting timers
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:app]: Sending TERMINATE to main background thread
%7|1518181627.349|BROADCAST|rdkafka#producer-8| [thrd:app]: Broadcasting state change
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:app]: Joining main background thread
%7|1518181627.349|DESTROY|rdkafka#producer-8| [thrd:main]: Destroy internal
%7|1518181627.349|DESTROY|rdkafka#producer-8| [thrd:main]: Removing all topics
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:main]: Purging reply queue
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:main]: Decommissioning internal broker
%7|1518181627.349|TERM|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 2 refcnts, 0 toppar(s), 0 fetch toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1518181627.349|TERMINATE|rdkafka#producer-8| [thrd:main]: Join 2 broker thread(s)
%7|1518181627.349|CONNECT|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connecting to ipv4#172.19.0.4:9092 (plaintext) with socket 7
%7|1518181627.350|STATE|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1518181627.350|BROADCAST|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: Broadcasting state change
%7|1518181627.350|TERMINATE|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181627.350|BROKERFAIL|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)
%7|1518181627.350|STATE|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1518181627.350|BROADCAST|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: Broadcasting state change
%7|1518181627.350|BUFQ|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Purging bufq with 0 buffers
%7|1518181627.350|BUFQ|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Updating 0 buffers on connection reset
%7|1518181628.449|TERMINATE|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181628.449|BROKERFAIL|rdkafka#producer-8| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1518181628.449|STATE|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN
%7|1518181628.449|BROADCAST|rdkafka#producer-8| [thrd::0/internal]: Broadcasting state change
%7|1518181628.449|BUFQ|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1518181628.449|BUFQ|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1518181628.449|TERMINATE|rdkafka#producer-8| [thrd:main]: Main background thread exiting
%7|1518181628.449|TERMINATE|rdkafka#producer-8| [thrd:app]: Destroying op queues
%7|1518181628.449|TERMINATE|rdkafka#producer-8| [thrd:app]: Termination done: freeing resources
```

The biggest difference is here:
-- ok
```
%7|1518181626.728|BUFQ|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Purging bufq with 0 buffers
%7|1518181626.728|BUFQ|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Updating 0 buffers on connection reset
%7|1518181626.827|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181626.827|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
```
-- too long
```
%7|1518181627.350|BUFQ|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Purging bufq with 0 buffers
%7|1518181627.350|BUFQ|rdkafka#producer-8| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Updating 0 buffers on connection reset
%7|1518181628.449|TERMINATE|rdkafka#producer-8| [thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1518181628.449|BROKERFAIL|rdkafka#producer-8| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
```

From what I can see the blocking `rd_kafka_wait_destroyed` is only needed for librdkafka < 0.9 (https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence)

I am not really familiar with building PHP extensions so it is hard to tell if this problem is in the extension or in the library itself.

**Comment by awons** [comment]
I removed the offending line and the issue is still there. Confirmed that this is indeed an issue in librdkafka (https://github.com/edenhill/librdkafka/issues/1690). The only viable solution is to implement a persisted producer.

A workaround with setting `socket.blocking.max.ms` to a lower value (like 100ms) works but since our system is in deep development state I am not able to say how this will affect production. It should work for now but in a long run it would probably be better to have persisted producer and not have to create it on each request.

Edit: I guess it can be closed because it is not an issue with the extension.

**Comment by nick-zh** [comment]
@arnaud-lb this can be closed

**Comment by maks-rafalko** [comment]
Having issues with the same problem. Could you please share your thoughts @awons & @arnaud-lb  on how to write persistent connection for **consumer** using `php-rdkafka`?

**Comment by Steveb-p** [comment]
@maks-rafalko writing a persistent Producer and/or Consumer is a complex thing to do. To write it as part of C extension that phprdkafka is you would need to maintain some resource that will survive request cleanup and operate between different PHP processes. In world of SQL database drivers there is a concept of persistent connection, but it's usage is highly contested - there are things that affect current client state that needs to be taken care of which usually leads to the benefit of persistent connection being overtaken by complications and additional operations (which make any optimization gains irrelevant).

See: https://www.php.net/manual/en/internals2.memory.persistence.php

Therefore, I would say what you'd want to do is to keep the connection persistent **in a specific process**. What I mean by that, all consumption and production should be done in dedicated CLI processes.  Don't use web processes (Apache php mod nor PHP-FPM) for sending or receiving messages - they are supposed to be quick, throw-away processes.

That's the approach I'm usually taking when integrating Kafka as a message bus.

**Comment by maks-rafalko** [comment]
> Therefore, I would say what you'd want to do is to keep the connection persistent in a specific process.

To be honest, I was asking *only* in the context of long-running CLI process, I'm sorry that I didn't make it clear.

We are using `php-rdkafka` (as a backend of Symfony Messenger) and faced with the issue that

```php
/** @var \KafkaConsumer $consumer */
$consumer->consume(500)
```

code spends ~1 second just to get the next message from the Kafka. After reading several of the issues here and on the `librdkafka` repository, I decided it is related to the same (or very similar) problem as described in this issue, so I thought that the "persistent connection" would help avoiding that 1s delay on each `consume()`.

> you'd want to do is to keep the connection persistent

do you have any recommendations on how to do it in the CLI process? Seems like I miss something...

**Comment by Steveb-p** [comment]
@maks-rafalko I'm using phprdkafka with Symfony Messenger as well. I'm using php-enqueue library to create two "queues" - one for Redis and second for Kafka itself. However, any solution combining a "local" queue (like filesystem or a database) would do just fine.

For Kafka consumer, see https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/rdkafka/RdKafkaConsumer.php. Even if you do not end up using enqueue, you can use this code as a reference for your own consumer. I'm sure it works properly, since I've had it consume thousands of messages per second.

Due to a couple of issues (like 4.0 compatibility) the package mentioned will receive an update soonish (™).

Other than that what I'd suggest is using asynchronous message commit, since normal commit waits for the offset to be written to disk as far as I remember, which will slow you down. When using `commitAsync` instead the command to write new offset is only sent to Kafka without waiting for confirmation - if you're ok with possibility of messages being processed twice at times. This also might be the reason why you're experiencing delays in consumption.

**Comment by nick-zh** [comment]
I will try to sum up the stuff we have here, to give an overview:
> rd_kafka_wait_destroyed(1000);

This will be removed in the next bugfix versions (3.x and 4.x), it was only needed for `<=librdkafka:0.9`  (#293, #294)

> First output is when everything went fine and destruction took in total around 100ms:

We used to do polling in the destructor, this was removed (#278, #264), released in `rdkafka:4.0.0`

There are also some interesting settings for shutdown, that can be found in the readme:
https://github.com/arnaud-lb/php-rdkafka#internalterminationsignal
https://github.com/arnaud-lb/php-rdkafka#socketblockingmaxms-librdkafka--100
https://github.com/arnaud-lb/php-rdkafka#queuebufferingmaxms

Regarding commit behaviour:
- commit to file has been deprecated and is discouraged (default is broker)
- a normal commit is blocking and will wait until the broker responds to the commit request
- a async commit doesn't wait for a broker response
If you commit async (unless you don't care about the commits) you need to use `Conf::setOffsetCommitCb` to handle commit failures properly.

Overall i would say, this issue had many causes over time. With `rdkafka:4.0.0` and appropriate settings, hopefully the behaviour is better / more consistent. 

To the original question of @maks-rafalko , in a long running cli process, you actually shouldn't face this problem. On start of your command, you might have an intial delay (SSL handshake, rebalancing), so until you read the very first message, it might take a few seconds.
But afterwards, consumption should be quite fast even with sync commit (unless you have a bad network connection). If you could find out, where that 1s gets lost, i would be quite interested.

**Comment by nick-zh** [comment]
@Steveb-p i could help out over at enqueue this WE unless you are already in the middle of it anyway, let me know

**Comment by maks-rafalko** [comment]
Thank you for the detailed answers. Regarding slow consumers: we were affected by the bug with consumer being initialized more than once (before this commit https://github.com/php-enqueue/enqueue-dev/commit/a07b0f95aecaee32816706d02f9205d0fab08945#diff-a369b1e017795d839d89abb5a6ad58c9), also had this class overridden in our code so upgrade didn't help.

I can confirm that for the `php-enqueu/enqueue-dev:0.9.14` consumer works as expected, without any delays, and `php-rdkafka` is not the source of the issue.

**Comment by nick-zh** [comment]
@maks-rafalko thank you very much for the feedback :+1: , glad to hear it is resolved
