### ISSUE TITLE
produce cost 1 second

### ISSUE THREAD

**Issue by a285577011** [php-rdkafka/php-rdkafka#146]
descript 
%7|1517296084.475|BROADCAST|rdkafka#producer-1| [thrd:xxx:9092/bootstrap]: Broadcasting state change
%7|1517296085.475|TOPPAR|rdkafka#producer-1| [thrd:211.149.162.241:9092/bootstrap]: xxxx:9092/0: Gula-ApiTest [0] 0+0 msgs

debug cost 1 seconds 1517296084.475-1517296085.475
why so long?

 * PHP version:7.1
 * librdkafka version:3.0.6
 * php-rdkfaka version:0.11.1

**Comment by a285577011** [comment]
@arnaud-lb

**Comment by wangluyu** [comment]
@a285577011 have you solved this issue?

**Comment by a285577011** [comment]
@wangluyu yes
