### ISSUE TITLE
how to use php-rdkafka on windows os ? somebody help?

### ISSUE THREAD

**Issue by leisuredev** [php-rdkafka/php-rdkafka#147]
* PHP version: 7.0.27
 * librdkafka version: 
 * php-rdkfaka version: 3.0.5
download link: http://pecl.php.net/package/rdkafka/3.0.5/windows

i want to use php-rdkafka on windows os, but it show:

Fatal error: Uncaught RdKafka\Exception: No such configuration property: "sasl.mechanisms"

Do I need to install sals ? How to install sals on windows os ? 

please help me!

**Comment by tobbelito123** [comment]
Remember I had a lot of problems getting the most simple example to work. Stuff I remember was:
- installing openssl 32bit and 64bit (you probably only need one of them)
- check if your system is thread safe or non-threadsafe, x86 or x64. You MUST choose the right download version and use the two dlls in there.
- CHECK YOUR SYSTEM PATHS (where is the web server looking for example)
- put the two dlls in the download package under your php/ext folder and make sure to activate the phprdkafka.dd in your phpinfo file. 
- repeat all of the above with all variations until when you run phpinfo() from your browser you will see your rdkafka extension.

**Comment by nick-zh** [comment]
@leisuredev do you still need help or has this been resolved?
