### ISSUE TITLE
Uncatchable error callback exception

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#149]
The exception form my callback is not catcheable. I used some real certificates but with a server that does not know them and has SSL not enabled

```
<?php

$conf = new RdKafka\Conf();

$conf->set('security.protocol', 'ssl');
$conf->set('ssl.ca.location','ca.pem');
$conf->set('ssl.certificate.location','bla.cert');
$conf->set('ssl.key.location','bla.key');

$conf->setErrorCb(function ($kafka, $err, $reason) {
    throw new \Exception(rd_kafka_err2str($err), $err);
});

try {
  $rk = new RdKafka\Producer($conf);
  $rk->addBrokers("127.0.0.1:9092");
  $topic = $rk->newTopic("test");
  $topic->produce(RD_KAFKA_PARTITION_UA,0,"bla");
} catch (\Exception $e) {
	echo "caught!";
}
```
it results in

```
PHP Fatal error:  Uncaught Exception: Local: SSL error in kafka.php:11
Stack trace:
#0 [internal function]: {closure}(Object(RdKafka\Producer), -181, 'ssl://127.0.0.1...')
#1 {main}
  thrown in kafka.php on line 11
```
PHP version: 7.2
librdkafka version: 0.11.1-r1
php-rdkfaka version: 3.0.5

**Comment by arnaud-lb** [comment]
Hi

produce() is asynchronous. As a result, the error callback is usually called after the produce() method has returned.

**Comment by nick-zh** [comment]
@arnaud-lb that is what i suspected, so i am assuming i am unable to catch this error, since it will be thrown in a different context, right?

**Comment by arnaud-lb** [comment]
Exactly. In order to be able to catch it in this context, you can use poll() to block until all async operations are done:

```
while ($rk->getOutQLen()) {
    $rk->poll(50);
}
```

**Comment by nick-zh** [comment]
@arnaud-lb i added that loop my test case, interestingly though, it catches the exception, but i still get additional output

```
caught!PHP Fatal error:  Uncaught Exception: Local: SSL error in kafka.php:11
Stack trace:
...
```
So it seems it catches it and at the same time it doesn't, or have i configured something wrong?
