### ISSUE TITLE
How to keep consumer connection alive while doing some work

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#150]
Hey! Thanks for awesome library. Wanted to ask whether there is something I can do to keep consumer alive while doing some work.

My consumer prefetches some amount of messages, then inserts them into DB and then commits offset.

```php
if (count($this->buffer) === self::BATCH_SIZE) {
    $this->insertToDb();
    $kafkaConsumer->commit($message);
}
```

However, when commiting, I often get Exception `Broker: Group rebalance in progress`. I guess it's because insert to db took few seconds and broker dropped consumer's connection.

Is there something to keep it alive? Help much appreciated!

 * PHP version: 7.1
 * librdkafka version: 0.11.3
 * php-rdkfaka version: 3.0.5

**Comment by tPl0ch** [comment]
@simPod You should set the `session.timeout.ms` > worst batch processing time + some headroom in order to indicate that the consumer is still processing instead of being assumed to have failed/timed out.

**Comment by simPod** [comment]
Will try to increase. Thanks for guidance
