### ISSUE TITLE
Add other rdkafka callbacks

### ISSUE THREAD

**Issue by jeckhart** [php-rdkafka/php-rdkafka#151]
* PHP version: 7.0 (but applicable to all)
 * librdkafka version: 0.11.1
 * php-rdkfaka version: 3.0.5

I'm hitting a problem where offsets are timing out on low traffic queues. The offsets "should" be getting committed every five minutes (using `$consumer->commitAsync();`) but I'm having a hard time trying to debug the issue.

rdkafka supports registering callbacks for commits, events, and other callbacks that aren't accessible in php-rdkafka today. These would be helpful to see what is happening in the async flows.

Is there a design decision to not expose those today? Would you be able to add them or be willing to review a PR?

Thank you!

**Comment by arnaud-lb** [comment]
Hi @jeckhart 

I'm willing to accept a PR for this :)
