### ISSUE TITLE
php_rdkafka.dll is not a valid Win32 application (64 bit)

### ISSUE THREAD

**Issue by aand18** [php-rdkafka/php-rdkafka#152]
Trying to run the x64 build but php doesn't recognise the DLL as valid:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'php_rdkafka.dll' (tried: C:/php-7.2.2-nts-Win32-VC15-x64/ext\php_rdkafka.dll (%1 is not a valid Win32 application.
> ), C:/php-7.2.2-nts-Win32-VC15-x64/ext\php_php_rdkafka.dll.dll (The specified module could not be found.
> )) in Unknown on line 0

Using:

- http://windows.php.net/downloads/pecl/snaps/rdkafka/3.0.5/php_rdkafka-3.0.5-7.2-nts-vc15-x64.zip 
- http://windows.php.net/downloads/releases/php-7.2.2-nts-Win32-VC15-x64.zip
- VC++ redistributable 2017 installed for both x86 and x64
- librdkafka.dll (file bundled with the PHP module) in System32 folder
- OS is Windows Server 2012 R2 x64

The same setup works using the x86 builds !

**Comment by nick-zh** [comment]
@aand18 do you still need help with this? Also this part in the error strikes me as a bit odd, the naming seems kind of messed up:
```
php_php_rdkafka.dll.dll (The specified module could not be found.
```

**Comment by inri13666** [comment]
Have the same issue, but found the reason.
Please check that your PHP root folder contain `librdkafka.dll` (./ext/.../librdkafka.dll)
