### ISSUE TITLE
Process doesn't exit on Ctrl+C

### ISSUE THREAD

**Issue by aand18** [php-rdkafka/php-rdkafka#153]
When you run a consumer script from command line you have to press Ctrl+C multiple times to exit the program.

Another issue (I think it's related) is you cannot kill (and therefore control) the script through Task Scheduler:
 - if you execute a consumer script from a batch file using Task Scheduler, when you command the task to end only the batch file gets terminated. The PHP CLI process continues to run in the background as a 'zombie' process.

Environment:
[php_rdkafka-3.0.5-7.2-nts-vc15-x86](http://windows.php.net/downloads/pecl/snaps/rdkafka/3.0.5/php_rdkafka-3.0.5-7.2-nts-vc15-x86.zip)
[php-7.2.2-nts-Win32-VC15-x86](http://windows.php.net/downloads/releases/php-7.2.2-nts-Win32-VC15-x86.zip)
OS:  Windows Server 2012 R2 x64

**Comment by nick-zh** [comment]
@aand18 is this still a problem? Have you tried using the current rdkafka release? Which version of librdkafka are you using?
