### ISSUE TITLE
Cannot trigger callbacks in high level consumer

### ISSUE THREAD

**Issue by beriba** [php-rdkafka/php-rdkafka#157]
* PHP version: 5.6
 * librdkafka version: 0.11.0-RC1
 * php-rdkfaka version: 3.0.5

In documentation for class RdKafka\KafkaConsumer I cannot see any possibility to trigger manually callbacks, especially setStatsCb(). Such option is available in low level consumer by using poll(). In high level consumer the only way I see to trigger callbacks is to execute consume() but it's not an option due to bussiness requirements. Can you provide an equivalent of poll() method to the RdKafka\KafkaConsumer class?

**Comment by nick-zh** [comment]
@beriba may i ask what our usecase is? Since you don't want to consume you could just do this with the low level consumer.

**Comment by beriba** [comment]
Since it was 1.5 years ago I don't remember what was the use case. Feel free to close this issue because I certainly no longer need it.
