### ISSUE TITLE
Delay initiating consumer when running php script

### ISSUE THREAD

**Issue by tobbelito123** [php-rdkafka/php-rdkafka#158]
* PHP version: 7.1
 * librdkafka version: ?
 * php-rdkfaka version: 3.05

So we are trying to build an application where we want to visualize messages in 'real time' in the browser using the consumer, as they come in on different topics. What we have tried so far is calling a slightly modified php script form the examples in php rdkafka outputting the messages every 50ms or so, in some div using jquery/ajax. This causes a delay of slightly less than a second every time the script is run and we initiate the consumer it seems, or if the delay is because we are not destroying it properly. Or we are just approaching it plain wrong doing that type of "solution" for real time data. 

Is there some way to have the consumer "open" the whole time and as soon as there is message to consume, it will be consumed and some event handler in javascript or whatever will take care of the visualization? Is it possible to run a script w php-cli initiating the consumer and start some infinite loop, and then pop the messages up in the browser as they come, with javascript or similar?

We also tried just increasing the execution time of php script and using flush in an infinite while loop to output msgs from consumer (thus initiating it only once), and then there is almost no delay no matter what producer is used to send msgs (the producers are not in php). So the issue (if I may call it that) is only really in initiating the consumer. 

If this is not considered an issue, I would even so appreciate some help on this, how to approach it (am obviously not a very advanced web developer). Can note that I tried setting all of the config parameters containing anything with ms in them to a low value, so it should not be any of that.

**Comment by nick-zh** [comment]
@tobbelito123 i am not sure if this issue is still exsting for you, but i would suggest running a consumer in the backgroudn that populates it's data somewhere and your page consumes it (not manipulating the html directly). The delay that you are seeing is because the high level consumer does a rebalance at startup, which takes some time. Let me know if you need further assistance.

**Comment by nick-zh** [comment]
@arnaud-lb i think this can be closed
