### ISSUE TITLE
configure error while installing

### ISSUE THREAD

**Issue by lc-Arvin** [php-rdkafka/php-rdkafka#161]
while installing php-rdkafka in my environment, i meet an error: 
![image](https://user-images.githubusercontent.com/4946674/37589027-f3c601a4-2b9e-11e8-829b-e35525aaaa61.png)

I tried different versions of librdkafka & php-rdkafka, but none helps. Please help if you got some hint. thanks!

My env info is as follows:

 * PHP version:
```
[root@xx  php-rdkafka-0.9.1-php5]# /home/bss/bss/third/php/bin/php -v
PHP 5.4.34 (cli) (built: Jan 28 2015 18:48:10)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

 * librdkafka version:
**librdkafka-0.9.1**

 * php-rdkfaka version:
**php-rdkafka-0.9.1-php5**

I downloaded the librdkafka source and the lib is placed in **/usr/local/lib/librdkafka**
```
[root@xx kafka]# nm /usr/local/lib/librdkafka
librdkafka.a       librdkafka++.a     librdkafka.so      librdkafka++.so    librdkafka.so.1    librdkafka++.so.1
[root@nmg02-bce-test91.nmg02.baidu.com kafka]# nm /usr/local/lib/librdkafka.so |grep version
0000000000012100 t rd_kafka_broker_set_api_versions
0000000000022d00 t rd_kafka_conf_validate_broker_version
000000000002a960 t rd_kafka_q_purge_toppar_version
0000000000008b20 T rd_kafka_version
0000000000008dc0 T rd_kafka_version_str
```

**Comment by arnaud-lb** [comment]
What's the content of the config.log file after the line `checking for rd_kafka_new` ?

**Comment by nick-zh** [comment]
@lc-Arvin is this issue still open or can it be closed?

**Comment by nick-zh** [comment]
@arnaud-lb i think this can be closed
