### ISSUE TITLE
7.x based DLLs for Windows missing (pecl)

### ISSUE THREAD

**Issue by atrauzzi** [php-rdkafka/php-rdkafka#162]
I just did a `choco install php` and ended up with version 7.2 of PHP. 

Any chance you can get a build of the 7.2 dll up?

**Comment by nick-zh** [comment]
@atrauzzi maybe i am understanding something wrong, but for me (for auto completion), i used https://github.com/kwn/php-rdkafka-stubs

**Comment by scaytrase** [comment]
Yes, stubs could be used for autocompletion. But 7.2 library is still wanted for running i.e tests locally

**Comment by atrauzzi** [comment]
Sorry, edited out the irrelevant part.

Just after a 7.2 version.

**Comment by acrozes** [comment]
Hello,
Is it possible to have a roadmap for a windows release on php 7.2 ?
Thank you

**Comment by cmb69** [comment]
Binary Windows packages of rdkafka 4.0.0 [are now available](https://windows.php.net/downloads/pecl/snaps/rdkafka/4.0.0/) for testing. They do not contain the fix from PR #294, so will likely segfault during shutdown, and as such are not suitable for production. As soon as new rdkafka versions will be released, builds for these versions should be triggered automatically again, and the DLLs should then be linked from https://pecl.php.net/package/rdkafka.

**Comment by nick-zh** [comment]
@cmb69 awesome, thank you very much for the support :+1:
will this also be available for any new 3.1.x versions?

**Comment by cmb69** [comment]
Yes, all new releases are supposed to be built. Please ping me if that doesn't work.

**Comment by nick-zh** [comment]
@cmb69 today there were two bugfix releases, i am not seeing any DLLs for `php-rdkafka:4.0.1`, can i somehow check if the build failed (or if it is still queued)? Sry i am new to pecl builds, so not sure where to check.
It seems `php-rdkafka:3.1.3` successfully built windows DLLs for php 7.2,7.3 & 7.4, which is great! Thx a lot and thx in advance for helping out with this :bowing_man: 
#313

**Comment by cmb69** [comment]
Indeed, the build machine stalled, and I had to manually trigger rebuilds of rdkafka 3.1.3 and 4.0.1. The latter is currently built. :)

**Comment by nick-zh** [comment]
@cmb69 much appreciated, thx a lot :+1:
