### ISSUE TITLE
How do I specify the number of partitions for a new topic?

### ISSUE THREAD

**Issue by atrauzzi** [php-rdkafka/php-rdkafka#163]
![image](https://user-images.githubusercontent.com/115199/37743418-fd134150-2d37-11e8-964d-32b3e021bd4d.png)

Fairly straightforward.  I'd like to have some commands as part of my application that can be responsible for provisioning the necessary topics and partitions.  Unfortunately it's not clear to me how I specify the partition count to the client...

**Comment by arnaud-lb** [comment]
`newTopic()` just creates a new topic object, not an actual Kafka topic. However, if the server is configured to have `auto.create.topics.enable=true`, the topic may eventually be automatically created. You can configure the default number of partitions for automatically created topics by configuring `num.partitions` on the server.
