### ISSUE TITLE
Does it support kafka 1.0.1?

### ISSUE THREAD

**Issue by dzhyw** [php-rdkafka/php-rdkafka#166]
kafka 1.0.1 is the latest release. The current stable version is 1.0.1. but this client is still 0.10

Does it support kafka 1.0.1?

thanks

**Comment by sp213** [comment]
I am asking the same question... Please make it available for Kafka's latest stable release. Thank you..

**Comment by nick-zh** [comment]
@lecodet @dzhyw I have been using this for 1.0.1 and so far i had no problems with it

**Comment by nick-zh** [comment]
Readme was updated with the latest release to reflect the support of kafka >= 0.8
so this can be closed @dzhyw @arnaud-lb
