### ISSUE TITLE
Error while running producer and consumer on different instance after sometime ! 

### ISSUE THREAD

**Issue by Shubham3521** [php-rdkafka/php-rdkafka#167]
2018/03/23 07:07:50 [error] 9819#9819: *539 connect() to unix:/run/php/php7.0-fpm.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 35.190.64.128, server: api-useast.midarexdigital.com, request: "POST /rtb/70b4bf164fd840f80afe320b1ad98234 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "exchange.adnexus.mobi"

**Comment by arnaud-lb** [comment]
Hi @Shubham3521 

IIRC this error means that you webserver can not connect to the php-fpm server because all fpm processes are buzy. It's possible that you are executing long running php scripts in fpm, and that they occupy all fpm processes.
