### ISSUE TITLE
Segmentation fault for producer

### ISSUE THREAD

**Issue by clyquan** [php-rdkafka/php-rdkafka#17]
when I used the producer as your examples, and got an error below:
Segmentation fault
what happened ? please help me and give more details about it.

**Comment by arnaud-lb** [comment]
Hi @clyquan,

Could you generate a stack trace for this ? https://bugs.php.net/bugs-generating-backtrace.php

Could you give some details about your environment ? OS/version, compiler version ? Which librdkafka version are you using ?

**Comment by arnaud-lb** [comment]
@clyquan, could you try with librdkafka 0.8.6 ?

**Comment by clyquan** [comment]
it 's 0.9, and maybe I should try it again with 0.8.6.

**Comment by arnaud-lb** [comment]
Closing as duplicate of #16
