### ISSUE TITLE
 failed: Connection refused

### ISSUE THREAD

**Issue by dzhyw** [php-rdkafka/php-rdkafka#175]
* PHP version: php5.6.21
 * librdkafka version: 0.11.4
 * php-rdkfaka version:  master 

[root@dev-node1 ~]# cat producer.php 
`<?php
$rk = new RdKafka\Producer();
        $rk->setLogLevel(LOG_DEBUG);
        $rk->addBrokers("192.168.200.73:9092");
        $topic = $rk->newTopic("user_report_tms");
        for ($i = 0; $i < 10; $i++) {
            $topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message $i");
        }`

[root@dev-node1 ~]# php producer.php 
%3|1527042221.372|FAIL|rdkafka#producer-1| [thrd:localhost:9094/2]: localhost:9094/2: Connect to ipv4#127.0.0.1:9094 failed: Connection refused
%3|1527042221.372|ERROR|rdkafka#producer-1| [thrd:localhost:9094/2]: localhost:9094/2: Connect to ipv4#127.0.0.1:9094 failed: Connection refused
%3|1527042221.372|FAIL|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
%3|1527042221.372|ERROR|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
%3|1527042221.372|FAIL|rdkafka#producer-1| [thrd:localhost:9093/1]: localhost:9093/1: Connect to ipv6#[::1]:9093 failed: Connection refused
%3|1527042221.372|ERROR|rdkafka#producer-1| [thrd:localhost:9093/1]: localhost:9093/1: Connect to ipv6#[::1]:9093 failed: Connection refused

why , still connect localhost?

**Comment by caelumcao** [comment]
you should set your ip in kafka/config/server.properties:
listeners=PLAINTEXT://192.168.92.132:9092

**Comment by dzhyw** [comment]
@caelumcao  yes, i  set this parameter, has worked.
