### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#178]
I may be mistaken but i think here:
https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-kafkaconsumertopic.offsetstore.html

The note should not say
> auto.commit.enable must be set to false when using this API.

but 

> enable_auto_offset_store must be set to false when using this API

I assume this note is, so that we avoid this:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_offset.c#L703

**Comment by nick-zh** [comment]
@arnaud-lb any insight no this? I want to make sure we are using this right

**Comment by nick-zh** [comment]
@arnaud-lb any feedback on this?

**Comment by arnaud-lb** [comment]
I'm not sure. The `rd_kafka_offset_store()` docblock mentions this:

```
  * @remark \c `enable.auto.offset.store` must be set to "false" when using this API.
```

https://github.com/edenhill/librdkafka/blob/v1.1.0/src/rdkafka.h#L3182

**Comment by nick-zh** [comment]
@arnaud-lb i opened an issue at librdkafka a while back, from the answer i think, if you want full controll, the one setting we want to adjust is `enable_auto_offset_store`, you can check the answer here:
https://github.com/edenhill/librdkafka/issues/1829#issuecomment-393427324

so yes what i am saying is:
`auto.commit.enable`  should be true
`enable.auto.offset.store` should be false
If you agree, i can open a PR for the doc :)

**Comment by arnaud-lb** [comment]
Yes, from this ticket and the related wiki page, this seems right :)

**Comment by nick-zh** [comment]
@arnaud-lb alright, i am going to create a pr on doc, thx :)
