### ISSUE TITLE
php7 process dont die while failing to connect to broker

### ISSUE THREAD

**Issue by omansour** [php-rdkafka/php-rdkafka#18]
thanks for the extension ! 

testing again php7.0.1, i am facing this error : 

``` shell
$ php test.php
%3|1452077507.698|FAIL|rdkafka#producer-0| 192.168.50.14:9092/bootstrap: Failed to connect to broker at kafka-node1:9092: Connection refused
%3|1452077507.698|ERROR|rdkafka#producer-0| 192.168.50.14:9092/bootstrap: Failed to connect to broker at kafka-node1:9092: Connection refused
%3|1452077507.698|ERROR|rdkafka#producer-0| 1/1 brokers are down
^C^C^C^C^C^C^C
```

and the script become unkillable. Am I missing something about timeout ? 

my test is pretty straitforward 

``` php
<?php

$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("192.168.50.14");

$topic = $rk->newTopic("test");
$topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message payload");

exit(0);


```

**Comment by arnaud-lb** [comment]
Hi @omansour,

I've seen the same behavior already, and it seems desirable to me. I haven't investigated much yet on how to abort abort after some time.

I can kill the script by hitting ctrl-C, though. Did you mask any signal in the script ?

**Comment by ankalagon** [comment]
I've got the same issue in
`PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29)`

I was investigating strace and I have:
`
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, {1461330365, 223921000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3, {1461330365, 275924000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5, {1461330365, 326234000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 7, {1461330365, 376423000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 9, {1461330365, 426785000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 11, {1461330365, 476909000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 13, {1461330365, 527250000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 15, {1461330365, 577432000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 17, {1461330365, 627883000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 19, {1461330365, 678050000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 21, {1461330365, 728335000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 23, {1461330365, 778790000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 25, {1461330365, 829175000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 27, {1461330365, 879525000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 29, {1461330365, 929910000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 31, {1461330365, 980455000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 33, {1461330366, 30587000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 35, {1461330366, 81045000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, {1461330365, 223921000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3, {1461330365, 275924000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5, {1461330365, 326234000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 7, {1461330365, 376423000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 9, {1461330365, 426785000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 11, {1461330365, 476909000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 13, {1461330365, 527250000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 15, {1461330365, 577432000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 17, {1461330365, 627883000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 19, {1461330365, 678050000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 21, {1461330365, 728335000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 23, {1461330365, 778790000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 25, {1461330365, 829175000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 27, {1461330365, 879525000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 29, {1461330365, 929910000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 31, {1461330365, 980455000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 33, {1461330366, 30587000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 35, {1461330366, 81045000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 37, {1461330366, 131291000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 39, {1461330366, 181549000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 41, {1461330366, 231869000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 43, {1461330366, 282206000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 45, {1461330366, 332361000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 47, {1461330366, 382608000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 49, {1461330366, 432850000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 51, {1461330366, 483254000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 53, {1461330366, 533587000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 55, {1461330366, 583852000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 57, {1461330366, 633991000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 59, {1461330366, 684400000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)= 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 37, {1461330366, 131291000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 39, {1461330366, 181549000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 41, {1461330366, 231869000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 43, {1461330366, 282206000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 45, {1461330366, 332361000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 47, {1461330366, 382608000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 49, {1461330366, 432850000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 51, {1461330366, 483254000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 53, {1461330366, 533587000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 55, {1461330366, 583852000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 57, {1461330366, 633991000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2fe6d30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2fe6d5c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 59, {1461330366, 684400000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)`

But I was playing with brokers and partitions. I've got topic test witch 1 partition, next I add 3 others brokers and issue occured. I modify topic, I set partitions to 4 and everything was working correctly, but strace was looking strange even if it was working correctly, I've seen 2 or 3 times `timeout` (exectly the same as above) and script exited correctly.

After few minutes issue came back and it's still not working.

**Comment by iyaozhen** [comment]
I have this problem too. `$topic->produce` function **no return value**(This is a async and non-blocking.). But you can set `message.timeout.ms` to short, this default value is 300000ms.

```
$conf = new RdKafka\TopicConf();
$conf->set("message.timeout.ms", 1000);
$topic = $rk->newTopic("DEV", $conf);
```

I don't understand how can I catch error, if something wrong.

**Comment by arnaud-lb** [comment]
@iyaozhen: you can use a delivery callback to be notified of delivery issues: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-conf.setdrmsgcb.html

**Comment by iyaozhen** [comment]
@arnaud-lb Thx. But I try it failure:

```
%3|1467727445.256|FAIL|rdkafka#producer-1| kafka.xxx.com:8000/bootstrap: Failed to connect to broker at 37.61.54.158:8000: Network is unreachable
%3|1467727445.256|ERROR|rdkafka#producer-1| kafka.xxx.com:8000/bootstrap: Failed to connect to broker at 37.61.54.158:8000: Network is unreachable
%3|1467727445.256|ERROR|rdkafka#producer-1| 1/1 brokers are down
PHP Fatal error:  Uncaught Error: Call to undefined method RdKafka\Conf::setDrMsgCb() in /home/work/local/temp/test.php:17
```

I hope catch like `Failed to connect` error and log it to file.

My ugly code:

``` PHP
$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("kafka.xxx.com:8000");  // this is wrong address

$topicConf = new RdKafka\TopicConf();
$topicConf->set("message.timeout.ms", 1000);
$topic = $rk->newTopic("DEV", $topicConf);

$topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message");

$rk->poll(1000);
$kafkaConf = new RdKafka\Conf();
$kafkaConf->setErrorCb(function ($rk, $err, $reason) {
    printf("Kafka error: %s (reason: %s)\n", rd_kafka_err2str($err), $reason);
});
$kafkaConf->setDrMsgCb(function ($rk, $message) {
    if ($message->err) {
        print_r($message);
    } else {
        print_r("ok");
    }
});
```

I think I do not understand this: `call poll() at regular intervals to serve any queued callbacks waiting to be called.` https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.poll.html

**Comment by arnaud-lb** [comment]
It seems that you don't have the setDrMsgCb method. Could you try upgrading to the latest php-rdkafka version ?

**Comment by buddy-yao** [comment]
@arnaud-lb I occurred the same error.  i have used setDrMsgCb method, but it was not called.
```
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5363, {tv_sec=1564734347, tv_nsec=892466700}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=897768100}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5365, {tv_sec=1564734347, tv_nsec=898768100}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=904660800}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5367, {tv_sec=1564734347, tv_nsec=905660800}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=931079500}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5369, {tv_sec=1564734347, tv_nsec=932079500}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=937849800}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5371, {tv_sec=1564734347, tv_nsec=938849800}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=945187500}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5373, {tv_sec=1564734347, tv_nsec=946187500}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=948114900}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5375, {tv_sec=1564734347, tv_nsec=949114900}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=972060900}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5377, {tv_sec=1564734347, tv_nsec=973060900}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734347, tv_nsec=997444700}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5379, {tv_sec=1564734347, tv_nsec=998444700}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1564734348, tv_nsec=11491100}) = 0
futex(0x5630c658003c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5381, {tv_sec=1564734348, tv_nsec=12491100}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x5630c6580010, FUTEX_WAKE_PRIVATE, 1) = 0
```

**Comment by nick-zh** [comment]
@buddy-yao please open a new issue and provide all the relevant information to replicate this, thanks!
