### ISSUE TITLE
Support for batch produce?

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#182]
I have found `rd_kafka_produce_batch()` in https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/tests/0011-produce_batch.c#L121

Is it possible to leverage that API using this library? If not, possible to implement?

Thanks!

**Comment by larsdecker** [comment]
It would be great if the library has a batch insert function.

**Comment by nick-zh** [comment]
@arnaud-lb can you label this issue please?

**Comment by nick-zh** [comment]
I will try to check this out this weekend

**Comment by nick-zh** [comment]
In sight of this: https://github.com/edenhill/librdkafka/issues/2415
I think it does not make sense to port a function that will be deprecated.
@arnaud-lb i think we can close this
