### ISSUE TITLE
How to quit gracefully?

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#183]
Hey! I wonder how to properly quit the consumer instance.

Would it make sense to call `unsubscribe()` on `__destruct()` of my high level rdkafka consumer?

Also, what about catching eg. SIGTERM etc. signals? Sometimes, the consumers are simply quit by CTRL/CMD + C so catching the signal and unsubscribing sounds like a good idea. Or, is there a code behind that handles all it?

Thanks

**Comment by upyx** [comment]
Hello!
I'm interesting in same question. If I understand right, extension does shutdown process on its own and there is no way to affect it. You no need to use `unsubscribe()` or anything else. By default SIGTERM breaks graceful shutdown but you can catch it and manually stop your program e.g. by `exit()` function.

I've found some details in https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

**Comment by nick-zh** [comment]
Hey guys

So i think @upyx is on the right track. The link he provided states, that the proper shutdown of a consumer consists of the following calls:
- `rd_kafka_consumer_close`
- `rd_kafka_destroy`
It is also mentioned there, that there is no need to call `unsubscribe` before this.
The above calls will be made when the PHP object gets destroyed (https://github.com/arnaud-lb/php-rdkafka/blob/master/kafka_consumer.c#L49)
Let me know if you need more information on this.
