### ISSUE TITLE
Fatal error: Uncaught Error: Class 'RdKafka\Conf' not found

### ISSUE THREAD

**Issue by sonalithakkar** [php-rdkafka/php-rdkafka#185]
I am getting following error
Fatal error: Uncaught Error: Class 'RdKafka\Conf' not found

php -i | grep kafka
rdkafka
rdkafka support => enabled
librdkafka version (runtime) => 0.11.0
librdkafka version (build) => 0.8.6.0

Also i have added extension=rdkafka.so in etc/php/cli/php.ini and in fpm/php.ini

Please help me

 * PHP version:7.0

**Comment by Xantas** [comment]
The same problem in my implementation:

rdkafka support => enabled
librdkafka version (runtime) => 0.9.3
librdkafka version (build) => 0.9.3.0

Extension loaded correctly.

PHP ver. 7.1.20

**Comment by sonalithakkar** [comment]
My issue get resolved after i added extension=rdkafka.so to /etc/php/7.0/apache/php.in

**Comment by lkoida** [comment]
@sonalithakkar Try to provide full path to extension.
In my case I added 
`extension=/usr/lib/php/20170718/rdkafka.so`
in two places
-  /etc/php/7.2/cli/conf.d/99-overrides.ini
- /etc/php/7.2/fpm/conf.d/99-overrides.ini
So I didn't modify the main ini file, but override it with additional configurations

**Comment by nick-zh** [comment]
@sonalithakkar can be closed then?

**Comment by nick-zh** [comment]
@arnaud-lb can be closed

**Comment by GabrielCHEN1** [comment]
i meet same problem... 
- my computer install `php` by `brew`
- in `/usr/local/etc/php/7.2/php.ini` , i have add `extension="rdkafka.so"`
- lib info
```
➜  7.2 php -i | grep kafka
rdkafka
rdkafka support => enabled
librdkafka version (runtime) => 1.5.0
librdkafka version (build) => 1.5.0.255
```

when I use command `php kafkatest.php`,,, it working,,, but I want use command by supervisor..

supervisor conf file
```
[program:kafka]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/www/project/Sites/kafka/kafkatest.php
autostart=true
autorestart=true
user=www
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/www/project/Sites/kafka/kafkatest.log
```

`sudo supervisorctl start kafka:kafka_00`
`/Users/www/project/Sites/kafka/kafkatest.log` print error

```
Fatal error: Uncaught Error: Class 'RdKafka\Conf' not found in 
/Users/www/project/Sites/kafka/kafkatest.php:11
Stack trace:
#0 {main}
  thrown in /Users/www/project/Sites/kafka/kafkatest.php on line 11
```

`kafkatest.php` file
```
<?php

$kafkaSetting = [
    'bootstrap_servers'   => '',
    'topic_name'          => '',
    'consumer_id'         => '',
];

$conf = new RdKafka\Conf();
$conf->set('api.version.request', 'true');
$conf->set('group.id', $kafkaSetting['consumer_id']);
$conf->set('metadata.broker.list', $kafkaSetting['bootstrap_servers']);
$topicConf = new RdKafka\TopicConf();
$conf->setDefaultTopicConf($topicConf);

$consumer = new RdKafka\KafkaConsumer($conf);


try {
    $consumer->subscribe([$kafkaSetting['topic_name']]);

    echo "Waiting for partition assignment... (make take some time when\n";
    echo "quickly re-joining the group after leaving it.)\n";

    while (true) {
        $message = $consumer->consume(30 * 1000);
        switch ($message->err) {
            case RD_KAFKA_RESP_ERR_NO_ERROR:
                var_dump($message);
                break;
            case RD_KAFKA_RESP_ERR__PARTITION_EOF:
                echo "No more messages; will wait for more\n";
                break;
            case RD_KAFKA_RESP_ERR__TIMED_OUT:
                echo "Timed out\n";
                break;
            default:
                throw new \Exception($message->errstr(), $message->err);
                break;
        }
    }
} catch (\RdKafka\Exception $e) {
    echo 'RdKafka Exception';
    exit;
}
```

**Comment by Steveb-p** [comment]
@sonalithakkar check that the PHP that supervisord executes uses the same .ini files as the shell user you're using when executing them manually.

The fact that you can execute it "by hand" clearly points in the direction that you're using different php configurations, if not even versions.

**Comment by 12raja** [comment]
hay,

i have face the php issue below like:

PHP Fatal error:  Uncaught Error: Class 'RdKafka\\Conf' not found in /var/www/html/iot-filling-station-2.0/kafkapublish/producer.php:15\nStack trace:\n#0 {main}\n  thrown in /var/www/html/iot-filling-station-2.0/kafkapublish/producer.php on line 15

Note: i added the kafka extension php.ini and fmp ini also

**Comment by Steveb-p** [comment]
@12raja this **always** happens if the extension is not actually loaded in the context you are executing it in.

Is this an error from a web server (fpm, probably) or CLI? As you noticed they have separate configurations, but as I stated - this happens when the extension is not actually enabled.

**Comment by 12raja** [comment]
@Steveb-p  please help me how to fix this.

**Comment by Steveb-p** [comment]
@12raja first, you need to pinpoint which PHP is misconfigured.

You can do so by running:
```shell
php -m | grep rdkafka
```
and
```shell
php-fpm -m | grep rdkafka
```
(as far as I know `php-fpm` can be used like a normal PHP and should tell you whether or not the extension is loaded).

If there is no output, then it will mean that in this case extension is **not loaded**.

I assume you're working with PHP CLI and PHP FPM. If you're working with Apache that uses mod_php, then this would be a tad different - and would point that you need to update it's configuration instead.

Then you know which PHP is not working, then run `php --ini` or `php-fpm --ini` to display configuration file locations. Then update the correct configuration and you should be good to go.
