### ISSUE TITLE
Topics reappearing after delete

### ISSUE THREAD

**Issue by chabior** [php-rdkafka/php-rdkafka#189]
Hi,
 We use an auto-create feature for topics in Kafka, but we are using kafka-manager to delete topics after some time. The problem is deleted topics reappears in Kafka after some time. I found that those topics are created again when rdkafka fetches metadata from the broker. Is there any way to fix it? I thought about deleting topics using admin api from librdkafa but it seems to me that it is not available in php binding, is there any plan to add admin api to php-rdkafka?

 * PHP version: 7.2.10
 * librdkafka version: 0.11.1
 * php-rdkfaka version: 3.0.5

**Comment by nick-zh** [comment]
Is related to #215

**Comment by nick-zh** [comment]
@chabior i don't know if there are any current plans right now. But i think this can be resolved. Please subscribe to #215 if you want to track the progress on this.
