### ISSUE TITLE
errors when install this package

### ISSUE THREAD

**Issue by clyquan** [php-rdkafka/php-rdkafka#19]
I try the librdkafka 0.8.6, and install this package for php 5.6 using "pecl install channel://pecl.php.net/rdkafka-0.0.2", get some errors  as follow, also i have tried the version 0.8.5/master, and got the same errors.

/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘kafka_init’:
/tmp/pear/temp/rdkafka/rdkafka.c:133: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c:133: error: (Each undeclared identifier is reported only once
/tmp/pear/temp/rdkafka/rdkafka.c:133: error: for each function it appears in.)
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘kafka_new’:
/tmp/pear/temp/rdkafka/rdkafka.c:145: error: too few arguments to function ‘zend_object_std_init’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘get_kafka_object’:
/tmp/pear/temp/rdkafka/rdkafka.c:157: error: too few arguments to function ‘zend_object_store_get_object’
/tmp/pear/temp/rdkafka/rdkafka.c:160: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘kafka_conf_new’:
/tmp/pear/temp/rdkafka/rdkafka.c:196: error: too few arguments to function ‘zend_object_std_init’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘get_kafka_conf_object’:
/tmp/pear/temp/rdkafka/rdkafka.c:208: error: too few arguments to function ‘zend_object_store_get_object’
/tmp/pear/temp/rdkafka/rdkafka.c:211: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘kafka_queue_new’:
/tmp/pear/temp/rdkafka/rdkafka.c:238: error: too few arguments to function ‘zend_object_std_init’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘get_kafka_queue_object’:
/tmp/pear/temp/rdkafka/rdkafka.c:250: error: too few arguments to function ‘zend_object_store_get_object’
/tmp/pear/temp/rdkafka/rdkafka.c:253: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘kafka_topic_new’:
/tmp/pear/temp/rdkafka/rdkafka.c:283: error: too few arguments to function ‘zend_object_std_init’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘get_kafka_topic_object’:
/tmp/pear/temp/rdkafka/rdkafka.c:295: error: too few arguments to function ‘zend_object_store_get_object’
/tmp/pear/temp/rdkafka/rdkafka.c:298: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘new_message’:
/tmp/pear/temp/rdkafka/rdkafka.c:307: error: ‘tsrm_ls’ undeclared (first use in this function)
/tmp/pear/temp/rdkafka/rdkafka.c:309: error: too few arguments to function ‘zend_update_property_long’
/tmp/pear/temp/rdkafka/rdkafka.c:310: error: too few arguments to function ‘zend_update_property_string’
/tmp/pear/temp/rdkafka/rdkafka.c:311: error: too few arguments to function ‘zend_update_property_long’
/tmp/pear/temp/rdkafka/rdkafka.c:313: error: too few arguments to function ‘zend_update_property_stringl’
/tmp/pear/temp/rdkafka/rdkafka.c:316: error: too few arguments to function ‘zend_update_property_stringl’
/tmp/pear/temp/rdkafka/rdkafka.c:318: error: too few arguments to function ‘zend_update_property_long’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka___construct’:
/tmp/pear/temp/rdkafka/rdkafka.c:327: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__Conf_set’:
/tmp/pear/temp/rdkafka/rdkafka.c:452: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c:455: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeQueueStart’:
/tmp/pear/temp/rdkafka/rdkafka.c:512: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeStart’:
/tmp/pear/temp/rdkafka/rdkafka.c:551: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeStop’:
/tmp/pear/temp/rdkafka/rdkafka.c:588: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consume’:
/tmp/pear/temp/rdkafka/rdkafka.c:630: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__Kafka_metadata’:
/tmp/pear/temp/rdkafka/rdkafka.c:743: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__ProducerTopic_produce’:
/tmp/pear/temp/rdkafka/rdkafka.c:1024: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zim_RdKafka__Queue_consume’:
/tmp/pear/temp/rdkafka/rdkafka.c:1096: error: too few arguments to function ‘zend_throw_exception’
/tmp/pear/temp/rdkafka/rdkafka.c: In function ‘zm_startup_rdkafka’:
/tmp/pear/temp/rdkafka/rdkafka.c:1308: error: too few arguments to function ‘zend_declare_property_null’
/tmp/pear/temp/rdkafka/rdkafka.c:1309: error: too few arguments to function ‘zend_declare_property_null’
/tmp/pear/temp/rdkafka/rdkafka.c:1310: error: too few arguments to function ‘zend_declare_property_null’
/tmp/pear/temp/rdkafka/rdkafka.c:1311: error: too few arguments to function ‘zend_declare_property_null’
/tmp/pear/temp/rdkafka/rdkafka.c:1312: error: too few arguments to function ‘zend_declare_property_null’
/tmp/pear/temp/rdkafka/rdkafka.c:1313: error: too few arguments to function ‘zend_declare_property_null’
make: **\* [rdkafka.lo] Error 1
ERROR: `make' failed

**Comment by arnaud-lb** [comment]
Hi @clyquan,

The version on PECL doesn't support ZTS PHP builds. I'll upload a new version soon. In the mean time, installing from source should work.

**Comment by arnaud-lb** [comment]
Thanks for reporting this issue

**Comment by arnaud-lb** [comment]
I've uploaded a new version on PECL, could you retry ?

**Comment by clyquan** [comment]
thanks for your help. I tryed the new version on PECL but got an error like #20, and I will follow this issue solution.
