### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Robustshouhualee** [php-rdkafka/php-rdkafka#191]
I have successfully install librdkafka and  php-rdkafka.
But I run the php demo awalys report:**Segmentation fault**
![image](https://user-images.githubusercontent.com/22031657/47949781-cc886200-df83-11e8-840b-cc6903255311.png)

I holp to receive you replay.THX

 * PHP :5.4.41
 * librdkafka version:v1.0.0-RC2
 * php-rdkfaka :3.05

**Comment by Robustshouhualee** [comment]
Resolved！
when you build your librdkafka, using ./configure  **--disable-ssl --disable-sasl**

**Comment by nick-zh** [comment]
@Robustshouhualee can be closed then?
