### ISSUE TITLE
SSL Authentification

### ISSUE THREAD

**Issue by AdrienGoetz** [php-rdkafka/php-rdkafka#192]
Hi,

Is it possible to use SSL authentication ? I've tried to add the following parameters to an RdKafkaConf object before passing it to a RdKafkaProducer according to librdkafka instructions 
(https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka) : 
- security.protocol
- ssl.ca.location
- ssl.certificate.location
- ssl.key.location
- ssl.key.password

But it results to this following error " No such configuration property : .. ".

I've tried this code : 
    `$conf` = new \RdKafka\Conf();
    `dd($conf->dump());`

All of the parameters are not in the array so I guess that is the reason why I can't set them up.

Do you guys have any solutions ?
Thanks

- php : 7.2.9
- php-rdkafka : 3.0.5

**Comment by YumeMichi** [comment]
```
<?php
$conf = new RdKafka\Conf();
$conf->set('metadata.broker.list', '127.0.0.1:9093');
$conf->set('security.protocol', 'ssl');
$conf->set('ssl.ca.location', '/srv/kafka-ssl/ssl/ca-cert');
$conf->set('ssl.certificate.location', '/srv/kafka-ssl/ssl/client_client_client.pem');
$conf->set('ssl.key.location', '/srv/kafka-ssl/ssl/client_client_client.key');
$conf->set('ssl.key.password', 'abcdefgh');

$rk = new RdKafka\Consumer($conf);
$rk->setLogLevel(LOG_DEBUG);
$topic = $rk->newTopic("test");
$topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);
while (true) {
    $msg = $topic->consume(0, 1000);
    if ($msg->err) {
        echo $msg->errstr(), "\n";
        break;
    } else {
        echo $msg->payload, "\n";
    }
}
```

**Comment by AdrienGoetz** [comment]
That's what I've already tried. 
It results to the error "No such configuration property : ...".

![image](https://user-images.githubusercontent.com/44789999/48341883-90818b00-e66e-11e8-850b-f5bb44ab78b4.png)

![image](https://user-images.githubusercontent.com/44789999/48341914-a2fbc480-e66e-11e8-9170-a4fb08a53195.png)

When I dump the conf, I got this :

![image](https://user-images.githubusercontent.com/44789999/48341979-d0487280-e66e-11e8-9a32-8a209510dcd3.png)

As you see, ssl.ca.location etc... do not appear in the array.

**Comment by YumeMichi** [comment]
![](https://i.imgur.com/Mn1zuXA.png)
![](https://i.imgur.com/S1Pg9wH.png)
![](https://i.imgur.com/LRBeSVU.png)

**Comment by AdrienGoetz** [comment]
My problem is not from kafka broker set up... 
Can you tell me how to check the version of php rdkafka ans librdkafka installed ? What about yours ? I think mine might be too old

**Comment by YumeMichi** [comment]
Both librdkafka and php-rdkafka are built from latest source.

https://kafka.apache.org/documentation/#security_configbroker

**Comment by AdrienGoetz** [comment]
Thank you for your answers !

**Comment by BingXiong1995** [comment]
i have the same issue. Can you tell me how you solved it?

**Comment by abhimanyuseth** [comment]
I had the same problem, but on MacOS. I had to reinstall openssl with brew and also librdkafka with brew. After that, it worked.
It wasn't working when I installed from source.
