### ISSUE TITLE
Confused！Why kafka cli does not have any comsumers in comsumer group?

### ISSUE THREAD

**Issue by june6868** [php-rdkafka/php-rdkafka#194]
When using low level consumer to cosume , I could not see any consumers in specific consumer group at the cli mode. Why?

**Comment by mancioshell** [comment]
same here

**Comment by nick-zh** [comment]
How are you checking this? I found that this command helped me to get the offsets for my consumer groups:
`kafka-consumer-groups  --bootstrap-server <broker url> --describe --group <consumer group name>`
With some tools i had the same problem, that if the consumer is not consuming right now, that i didn't see the offsets
Also make sure your offsets are really commited back to the broker (and not to a file or not at all)
Hope this helps

**Comment by arnaud-lb** [comment]
Hi @june6868 

The low level consumer does not use Kafka's consumer groups at all. The high level consumer does (this is the main difference between the two consumers).

**Comment by nick-zh** [comment]
@arnaud-lb but i think you can set it if you do a
`$conf->set('group.id', 'my-consumer-group');`
no? I followed this example in the doc:
https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-low-level-consumer-basic.html

**Comment by arnaud-lb** [comment]
Yes, this is used by librdkafka to prevents conflicts between multiple consumers of the same topics on the same host. The file offset store uses the group id as a "namespace", for example. However, I don't think that the group id is ever sent to the brokers.

**Comment by nick-zh** [comment]
@arnaud-lb i see, but if i use broker as the store method, then it does as far as i know
Sry i was not sure what store method was used for this issue. But thanks for the insight on what the file store does, didn't know that

**Comment by arnaud-lb** [comment]
Oh you are right: When using the broker store method, the group id is getting used on the broker as well. I don't think that it creates a consumer group, though.

**Comment by nick-zh** [comment]
@arnaud-lb right now we use this and i seem to get the result with the kafka command i mentioned above, so as far as i can see it does. At least the quick tests that i made, it seems when i use the low level, my consumer is really able to "restart" where he left off, even after a reboot or destruction of my php container :smile:
