### ISSUE TITLE
Headers message support

### ISSUE THREAD

**Issue by padlavoine** [php-rdkafka/php-rdkafka#197]
Hi, 

Is header support in a message provided ?
https://github.com/edenhill/librdkafka/blob/v0.11.5/src/rdkafka.h#L962

Thank you.

* PHP version: >7.1
 * librdkafka version 0.11.5:
 * php-rdkfaka version: 3.5

**Comment by nick-zh** [comment]
It should be now with the newest release of 3.1.0 which was released 5 days ago
I think this can be closed now @padlavoine @arnaud-lb ?
