### ISSUE TITLE
How use consumer properties about security sasl SASL_PLAINTEXT

### ISSUE THREAD

**Issue by fighthorse** [php-rdkafka/php-rdkafka#198]
* PHP version: 7.1.12
 * librdkafka version: 0.9
 * php-rdkfaka version: 3.0

like C++ use kafka ：

rd_kafka_conf_set(conf_, "bootstrap.servers", brokers.c_str(), errstr,sizeof(errstr));
rd_kafka_conf_set(conf_, "security.protocol", "sasl_plaintext", errstr,sizeof(errstr));
rd_kafka_conf_set(conf_, "sasl.mechanisms", "PLAIN", errstr, sizeof(errstr));
rd_kafka_conf_set(conf_, "sasl.username", username.c_str(), errstr, sizeof(errstr));
rd_kafka_conf_set(conf_, "sasl.password", password.c_str(), errstr,sizeof(errstr));
rd_kafka_conf_set(conf_, "api.version.request", "true", errstr,sizeof(errstr));
 
 
1、$conf = new \RdKafka\Conf();
2、how can I set  conf   Object ， kafka can config ：
bootstrap.servers: broker
security.protocol: SASL_PLAINTEXT
sasl.mechanisms: sasl
sasl.username: 
sasl.password: 

can see this ：https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

php-rdkafka can use this ？？

for help~

**Comment by fighthorse** [comment]
##################consumer.properties
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
##############kafka_client_consumer_jass 
KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="writer"
  password="writer";
};

**Comment by fighthorse** [comment]
We can use properties  like this:
        $conf->set('security.protocol', 'sasl_plaintext');//sasl_plaintext  SASL_SSL
        $conf->set('sasl.mechanisms', 'PLAIN');
        $conf->set('sasl.username', $config['user']);
        $conf->set('sasl.password', $config['pwd']);

**Comment by fighthorse** [comment]
Is There Some Body Can help me ？

**Comment by nick-zh** [comment]
@fighthorse what exactly is going wrong? The example you provided

```
$conf->set('security.protocol', 'sasl_plaintext');//sasl_plaintext SASL_SSL
$conf->set('sasl.mechanisms', 'PLAIN');
$conf->set('sasl.username', $config['user']);
$conf->set('sasl.password', $config['pwd']);
```

looks not bad, i havent used sasl though, only ssl. What kind of error do you get?

**Comment by nick-zh** [comment]
@fighthorse do you still need help or can this be closed?

**Comment by pratdineout** [comment]
@fighthorse Were you able to use these?
$conf->set('security.protocol', 'sasl_plaintext');//sasl_plaintext SASL_SSL
$conf->set('sasl.mechanisms', 'PLAIN');
$conf->set('sasl.username', $config['user']);
$conf->set('sasl.password', $config['pwd']);

what was the issue?
Please share the solution.
I am stuck with this.

Thanks

**Comment by nick-zh** [comment]
So for example confluent uses SASL, they provide examples in the clients section.
Those settings should work:
```
// can be SASL_PLAINTEXT, SASL_SSL
$conf->set('security.protocol', '');
// can be GSSAPI, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, OAUTHBEARER
$conf->set('sasl.mechanisms', '');
$conf->set('sasl.username', '');
$conf->set('sasl.password', '');
```

Depending on your setup you might also need
```
$conf->set('ssl.endpoint.identification.algorithm', 'https');
```
A description of what error you are getting might also help
