### ISSUE TITLE
 ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by cocktail18** [php-rdkafka/php-rdkafka#199]
* PHP version: PHP 7.2.11 
 * librdkafka version:0.11.4.0
 * php-rdkfaka version:3.0.5

when i use the consumer for a long time (one or two day), the consumer would got null.
And i **trace** it by strace and i got these:
```
futex(0x7f1d8c3520ac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 11204059, {1546826345, 410598000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f1d8c352080, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f1d8c3520ac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 11204061, {1546826347, 409779000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f1d8c352080, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f1d8c3520ac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 11204063, {1546826349, 409924000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)

```

It is confused

**Comment by douyux** [comment]
Same issue. Is there any updates ? Maybe we can register a error callback and restart the daemon consumer.

**Comment by nick-zh** [comment]
@cocktail18 @douyu do you still need help with this? If yes, please try if you still have the same behaviour with `librdkafka:1.1.0` and `rdkafka:3.1.2` and if so, please let me know.
