### ISSUE TITLE
Support of 0.9.x versions of Kafka

### ISSUE THREAD

**Issue by vchampion** [php-rdkafka/php-rdkafka#20]
When I try to build extension with librdkafka greater than 0.9.0.0 error occurs
`configure: error: Unsupported librdkafka version. Supported versions: 0.8.x`

**Comment by arnaud-lb** [comment]
Hi Vladislav,

This is expected, there is a bug in the master / 0.9 branch of librdkafka
that is causing crashes. This configure-time check is meant to avoid
the trouble
to php-rdkafka users. I'll remove this restriction as soon as possible.

**Comment by vchampion** [comment]
Thank you! Glad to hear that all will be good

**Comment by arnaud-lb** [comment]
The bug has been fixed in librdkafka master, so I'll remove the restriction soon. In the mean time, it's still possible to install php-rdkafka with librdkafka 0.8.6.

**Comment by arnaud-lb** [comment]
@vchampion @clyquan: I've pushed a new version of php-rdkafka here and on pecl. Make sure to install the latest version of librdkafka before building php-rdkafka. I you install php-rdkafka from source, make sure to re-execute `phpize` under the php-rdkafka directory before executing `./configure`.

**Comment by clyquan** [comment]
thanks, It's ok now.
