### ISSUE TITLE
high level api supports commit offset??

### ISSUE THREAD

**Issue by tanxiaolong** [php-rdkafka/php-rdkafka#201]
hi~
i use high level api.
1/ if i set "enable.auto.commit" true, then i don't need to `$consumer->commit()` by myself, right?
2/ `$consumer->consume(120 * 1000)`.  does this mean every 1.2s consume a message??

thank you for your time answering my questions~  :D

**Comment by upyx** [comment]
Hello.

> 1/ if i set "enable.auto.commit" true, then i don't need to `$consumer->commit()` by myself, right?

Yes. It will commits every `auto.commit.interval.ms`. 

> 2/ `$consumer->consume(120 * 1000)`. does this mean every 1.2s consume a message??

No. It is timeout of receiving message. And 120 * 1000 = 120 seconds.

**Comment by nick-zh** [comment]
@tanxiaolong @arnaud-lb i think this can be closed, yes?
