### ISSUE TITLE
Convert second param of conf->set() to string?

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#204]
Is this valid?

`$conf->set('internal.termination.signal', (string) SIGIO)`

`SIGIO` is of type int but `\RdKafka\Conf`'s 2nd param is string https://github.com/arnaud-lb/php-rdkafka/blob/8f1c8a0cabeadc721c1fe26912ebd364118c106a/conf.c#L392

Like `$conf->set('internal.termination.signal', SIGIO)` this call is type-invalid, right?

**Comment by arnaud-lb** [comment]
Hello

Yes, this is valid

**Comment by simPod** [comment]
Thanks!
