### ISSUE TITLE
offset.store.path causes  consume stop

### ISSUE THREAD

**Issue by snowonbridge** [php-rdkafka/php-rdkafka#205]
* PHP version:
 * librdkafka version:
 * php-rdkfaka version:

environment:

rdkafka support => enabled
version => 3.0.6-dev
build date => Mar 12 2019 03:23:14
librdkafka version (runtime) => 0.9.0
librdkafka version (build) => 0.9.0.0

codes:
` $conf = new \RdKafka\Conf();

// Set the group id. This is required when storing offsets on the broker
        $conf->set('group.id', 'test');

        $rk = new \RdKafka\Consumer($conf);
        $rk->addBrokers(Env::get("kafka.ip"));
        $topicConf = new \RdKafka\TopicConf();
        $topicConf->set('auto.commit.interval.ms', 100);
        $topicConf->set('offset.store.method', 'file');
        @unlink(RUNTIME_PATH.'wm/kafka-offset.txt');
        $topicConf->set('offset.store.path', RUNTIME_PATH.'wm/kafka-offset.txt');

        $topicConf->set('auto.offset.reset', `'smallest');
       $topic = $rk->newTopic("test", $topicConf);
       while (true) {
            $message = $topic->consume(0, 120*10000);
            if(!is_object($message)){
                sleep(2);
                continue;
            }
            switch ($message->err) {
                case RD_KAFKA_RESP_ERR_NO_ERROR:
                    self::payload($message->payload);
                    $topic->offsetStore($message->partition, $message->offset);
                    break;
                case RD_KAFKA_RESP_ERR__PARTITION_EOF:
                    \think\Log::error("No more messages; will wait for more");
                    break;
                case RD_KAFKA_RESP_ERR__TIMED_OUT:
                    \think\Log::error("Timed out");
                    break;
                default:
                    \think\Log::error("error code {$message->err}:".$message->errstr());
                    break;
            }
        }`

    
problems:
1.when i  remove  the unlink function , php process will be blocked at time of process reload 
 and consuming again.as a result，it cannot gets messages.
2.when i add the unlink function,repeated comsuming will happens.

**Comment by nick-zh** [comment]
As FYI: According to the newest release of [librdkafka](https://github.com/edenhill/librdkafka/releases/tag/v1.0.0) offset.store.method=file is now deprecated. Unless we really have to, i think we should avoid using this option in the future

**Comment by nick-zh** [comment]
@snowonbridge do you need further help or can this be closed?
