### ISSUE TITLE
New release / future plans ?

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#209]
I see that the last release was November 2017, i love the extension and i see that stuff is being done. Is there any upcoming release planned?
In light of [librdkafka 1.0.0](https://github.com/edenhill/librdkafka/releases/tag/v1.0.0) being released, i am also wondering, do you have any plans on adding new features / capabilities that are now being supported.
I understand that you surely have other obligations as well, but i am very interested in what
your future plans with the extension are.
Thank you for your work on the extension :+1: 

Cheers,
Nick

**Comment by arnaud-lb** [comment]
Hi Nick

Thanks for the kind words. I'm super happy to see new contributions lately, I'm going to publish a new release to make the changes available to everyone.

I'm willing to accept contributions to fix bugs or to expose new features of librdkafka. I am open to suggestions as well :)

Cheers
