### ISSUE TITLE
Using SSL with Kafka

### ISSUE THREAD

**Issue by vchampion** [php-rdkafka/php-rdkafka#21]
Can anyone explain is it possible to use SSL with Kafka and this library?

**Comment by arnaud-lb** [comment]
Hi @vchampion,

I haven't tried yet, but building php-rdkafka against librdkafka 0.9/master should automatically bring SSL support to php-rdkafka. Following these steps should work: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

The properties referenced [here](https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka#configure-librdkafka-client) can be set on a `RdKafka\Conf` object and passing it to a `RdKafka\Consumer` or `RdKafka\Producer` instance.

**Comment by vchampion** [comment]
Ok, thank you, I'll try it later and reopen task if something went wrong.

**Comment by slootjes** [comment]
Just in case if someone is interested...I managed to make it work with:

```php
$conf = new RdKafka\Conf();
$conf->set('security.protocol', 'ssl');
$conf->set('ssl.ca.location', __DIR__.'/cacert.pem');
$conf->set('ssl.certificate.location', __DIR__.'/kafka.crt');
$conf->set('ssl.key.location', __DIR__.'/kafka.key');
```

**Comment by HamoonDBA** [comment]
@slootjes I got Uncaught exception 'RdKafka\Exception' with message 'No such configuration property: "security.protocol"'  Error.

But  examples/rdkafka_example -X builtin.features get me this result:

`builtin.features = gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins`
