### ISSUE TITLE
In the docker :failed: Host is unreachable

### ISSUE THREAD

**Issue by liuhanjia** [php-rdkafka/php-rdkafka#210]
WARNING: [pool www] child 18 said into stderr: "%3|1555660765.754|ERROR|rdkafka#producer-2| [thrd:192.168.4.99:32769/bootstrap]: 192.168.4.99:32769/bootstrap: Connect to ipv4#192.168.4.99:32769 failed: Host is unreachable (after 1002ms in state CONNECT)"

docker

1fa9482b6dfc kafkadocker_kafka "start-kafka.sh" 2 days ago Up 2 days 0.0.0.0:32769->9092/tcp kafkadocker_kafka_1

host ip ：192.168.4.99

code：

const TEST_KAFKA_BROKERS = "192.168.4.99:32769";

public function rkProduce()
{
    try {
            Log::info('生产消息：---');
            //$topicName = sprintf('test_rdkafka_%s', uniqid());
            $topicName = sprintf('test_0419_0616');
            $producer = new \RdKafka\Producer();
            $producer->addBrokers(self::TEST_KAFKA_BROKERS);
            $topic = $producer->newTopic($topicName);

 * PHP version:7.2
 * librdkafka version:1.0.0.0
 * php-rdkfaka version:3.0.5

**Comment by arnaud-lb** [comment]
This looks like a Docker-related issue. Make sure that this is the correct address and port, and that they are reachable from the client.
