### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#212]
Dear Arnaud

I was unable to find if i can create a PR to the documentation that is right now on github.io.
If that is not possible, maybe keeping the doc in the wiki or in the repo itself would be nice,
so we can help contribute to the documentation.
I opened an issue for a possible error a while back #178
Also it would be nice for 3.1.0 to have the new functions producev (support for headers), kafka_conf_consume_cb, kafka_conf_offset_commit_cb and RdKafka\KafkaConsumer::getCommittedOffsets(array $topics, int timeout_ms) documented.
Let me know what you think.

Cheers,
Nick

PS: Thx for releasing 3.1.0 :heart_eyes_cat:

**Comment by arnaud-lb** [comment]
Hi Nick

The docs repository can be found at https://github.com/arnaud-lb/php-rdkafka-doc. PRs welcome :)
