### ISSUE TITLE
Adjust release notes for 3.1.0

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#213]
Dear Arnaud,

I think it would be nice to have release notes for the versions, i took the liberty to compile them from what PRs i found since 3.0.5. Maybe you can add this to the 3.1.0 release?

# rdkafka v3.1.0 release

## Features
* add callback for offset_commit (RdKafka\Conf::setOffsetCommitCb) and consume (RdKafka\Conf::setConsumeCb) (#155)
* add support for message headers (RdKafka\ProducerTopic::producev) for Kafka >= 0.11.0.0 and librdkafka >= 0.11.4 (#206)
* get committed offsets (RdKafka\KafkaConsumer::getCommittedOffsets) (#208)

## Enhancements
* RdKafka\ProducerTopic::produce - allow payload or key to be null (#179)
* RdKafka\Message::errstr - prefer readable error over message payload (#181)

## Fixes
* fix arginfo of RdKafka\TopicConf::set (#188)
* multiple code example fixes (#193, #203)
* Parse message headers only on non error (#207)

**Comment by arnaud-lb** [comment]
Thanks @nick-zh ! I've added them: https://github.com/arnaud-lb/php-rdkafka/releases
