### ISSUE TITLE
Migrate documentation to Jekyll

### ISSUE THREAD

**Issue by Steveb-p** [php-rdkafka/php-rdkafka#218]
...so that common parts can be extracted to layout files and made more readable, so more people can get more easily involved in supplying documentation examples and comments.

And refactor it to be more human readable.

I've made some initial attempts and I think it should be easily doable for me, I'm willing to provide a PR if you give the go-ahead @arnaud-lb.

**Comment by arnaud-lb** [comment]
Hi Pawel,

Would the Jekyll based doc contain the reference as well as examples ? What would be the source format ? Do you have examples of projets using Jekyll for documentation ?

I was originally planning to push the [reference documentation](https://arnaud-lb.github.io/php-rdkafka/phpdoc/) on php.net (hence the [xml source](https://github.com/arnaud-lb/php-rdkafka-doc)), but I’m open to other options.

**Comment by Steveb-p** [comment]
> Would the Jekyll based doc contain the reference as well as examples ? What would be the source format ? Do you have examples of projets using Jekyll for documentation ?

It will look exactly the same as it looks today. I intended to simply look over existing html files, clean the structure and indentation, and take the main layout to a separate file to avoid repetition.  
Therefore, to respond properly to the question, I was thinking about keeping them in html format.

Technically speaking Jekyll is just a static site generator. It's suggested for github pages (https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages).  

> I was originally planning to push the reference documentation on php.net (hence the xml source), but I’m open to other options.

I only just know have seen this repository with - I assume - base xml code that is the source of current documentation.

If you intend to merge it with current php documentation then obviously it's pointless to produce a second documentation source, so all I'd do is add a reference to documentation source in readme (unless I'm blind and it's already there).

**Comment by nick-zh** [comment]
@Steveb-p what do you think, should we close this?

**Comment by Steveb-p** [comment]
> @Steveb-p what do you think, should we close this?

Yes, there is no reason to migrate to jekyll since documentation received your careful attention, and might actually be merged as part of PHP docs eventually.
