### ISSUE TITLE
Call unsubscribe at the end of consumption examples

### ISSUE THREAD

**Issue by Steveb-p** [php-rdkafka/php-rdkafka#227]
* PHP version: 7.2
 * librdkafka version: 1.0.0
 * php-rdkafka version: 3.1.0

In all examples there are calls for `subscribe` and `consume`. 
I've noticed in my application that if I leave it at that, it seems that there is a period of time before consumption from another process picks up. 
It looks to me like Kafka is still in the process of establishing that the original process has exited. Shouldn't all examples explicitly call `unsubscribe` to show how it can properly exit?

Or do I misunderstand the meaning behind `unsubscribe` method and what it does? I haven't found other calls to `rd_kafka_unsubscribe` in the phprdkafka codebase.

**Comment by nick-zh** [comment]
Do you have input regarding using `unsubscribe` @arnaud-lb ?
As far as i know the delay can sometimes happen anyway because the high level consumer does a rebalancing, but i don't know if this can be improved if consumers correctly unsubscribe, if so, let's add it to the examples.

**Comment by Steveb-p** [comment]
@nick-zh sorry I didn't write it up here, but my testing didn't result in performance increase when I started calling `unsubscribe` at the end of PHP process.

**Comment by nick-zh** [comment]
@Steveb-p so it probably really is due to the balancing, do you want to close it or dig in further?

**Comment by Steveb-p** [comment]
@nick-zh I'm pretty sure we should close this. I'm almost certain that consumers would deregister from Kafka brokers when they are destroyed at the end of the process, doing something similar to `unsubscribe` anyway. At least I assume they do.
