### ISSUE TITLE
TopicConf is invalid

### ISSUE THREAD

**Issue by clyquan** [php-rdkafka/php-rdkafka#23]
I'am using topic configuration for a comsumer, and get an error below:

PHP Fatal error:  Uncaught exception 'RdKafka\Exception' with message 'Local: Invalid argument or configuration' in /home/clyde/c.php:13
Stack trace:
#0 /home/clyde/c.php(13): RdKafka\ConsumerTopic->consumeStart(0, -1000)
#1 {main}

  thrown in /home/clyde/c.php on line 13

And I dumped the configuration as follows:
array(12) {
  ["request.required.acks"]=>
  string(1) "1"
  ["request.timeout.ms"]=>
  string(4) "5000"
  ["message.timeout.ms"]=>
  string(6) "300000"
  ["produce.offset.report"]=>
  string(5) "false"
  ["compression.codec"]=>
  string(7) "inherit"
  ["auto.commit.enable"]=>
  string(4) "true"
  ["auto.commit.interval.ms"]=>
  string(4) "1000"
  ["auto.offset.reset"]=>
  string(7) "largest"
  ["offset.store.path"]=>
  string(1) "."
  ["offset.store.sync.interval.ms"]=>
  string(2) "-1"
  ["offset.store.method"]=>
  string(6) "broker"
  ["consume.callback.max.messages"]=>
  string(1) "0"
}

Also I went through the https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md, but got nothing about this error.

**Comment by arnaud-lb** [comment]
Hi @clyquan,

Which configuration properties did you override ? Does the error disappear when not overriding one or more of these properties ?

**Comment by clyquan** [comment]
Actually, I just do changes below:
  auto.commit.interval.ms = 1000
  offset.store.sync.interval.ms = -1
When I call consumeStart(0, RD_KAFKA_OFFSET_STORED), the error aforementioned was thrown. If I use RD_KAFKA_OFFSET_BEGINNING, It's OK.

**Comment by arnaud-lb** [comment]
`offset.store.sync.interval.ms` might only be valid for `offset.store.method=file`, did you try with this setting ?

**Comment by arnaud-lb** [comment]
Also, you have to specify a `group.id` when setting `offset.store.method=borker`: https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management#broker-based-offsets

**Comment by clyquan** [comment]
Hi @arnaud-lb , I follow your suggestion and the error disappear now. There are several messages in kafka cluster, but I got nothing except some tips below:

Broker: No more messages

**\* rdkafka_timer.c:245:rd_kafka_timers_destroy: assert: TAILQ_EMPTY(&rkts->rkts_timers) ***

Also, I check the local storage file and find that the offset is zero. From the librdkafka, someone also have issues(https://github.com/edenhill/librdkafka/issues/491) like this.
Can you give me some details about this ?

**Comment by debug2012** [comment]
Hi @clyquan ,did you solve the problem ?  I meet the same problem with you

**Comment by MarinoRaul** [comment]
Hi @clyquan ,did you solve the problem ? I meet the same problem with you

**Comment by MarinoRaul** [comment]
Hi @debug2012 ,did you solve the problem ? I meet the same problem with you

**Comment by arnaud-lb** [comment]
@clyquan @debug2012 @MarinoRaul could you enable debugging and copy the resulting output ? `$conf->set("debug", "topic,fetch");`

**Comment by MarinoRaul** [comment]
Hello I could do save offset locally....

But I want to create this with broker offset storage... When I create a group.id I got this error....

Closet socket 127.0.0.1 (Kafka.network.processor) org.apache.kafka.protocol.common.types.SchemaException: error.reading.field topics : Java.nio.buffer.underflow.exception

Thanks a lot

**Comment by MarinoRaul** [comment]
My code is:

$conf = new RdKafka\Conf();
        $conf->set('group.id', 'GroupConsumerTest');
        $conf->set('metadata.broker.list', '127.0.0.1:9092');

```
   $consumer = new RdKafka\KafkaConsumer($conf);
    $consumer->subscribe([self::TOPIC]);

    while (true) {
        $message = $consumer->consume(3600e3);
        switch ($message->err) {
            case RD_KAFKA_RESP_ERR_NO_ERROR:
                var_dump($message);
                break;
            case RD_KAFKA_RESP_ERR__PARTITION_EOF:
                echo "No more messages; will wait for more\n";
                break;
            case RD_KAFKA_RESP_ERR__TIMED_OUT:
                echo "Timedout\n";
                break;
            default:
                throw new \Exception($message->errstr(), $message->err);
                break;
        }
    }
```

When I include "config->set group_id" for use kafka broker storage I got this error !

Thanks a lot.

**Comment by MarinoRaul** [comment]
array(54) {
  ["builtin.features"]=>
  string(21) "gzip,snappy,ssl,regex"
  ["client.id"]=>
  string(7) "rdkafka"
  ["metadata.broker.list"]=>
  string(14) "127.0.0.1:9092"
  ["message.max.bytes"]=>
  string(7) "1000000"
  ["receive.message.max.bytes"]=>
  string(9) "100000000"
  ["metadata.request.timeout.ms"]=>
  string(5) "60000"
  ["topic.metadata.refresh.interval.ms"]=>
  string(6) "300000"
  ["topic.metadata.refresh.fast.cnt"]=>
  string(2) "10"
  ["topic.metadata.refresh.fast.interval.ms"]=>
  string(3) "250"
  ["topic.metadata.refresh.sparse"]=>
  string(4) "true"
  ["debug"]=>
  string(11) "topic,fetch"
  ["socket.timeout.ms"]=>
  string(5) "60000"
  ["socket.blocking.max.ms"]=>
  string(3) "100"
  ["socket.send.buffer.bytes"]=>
  string(1) "0"
  ["socket.receive.buffer.bytes"]=>
  string(1) "0"
  ["socket.keepalive.enable"]=>
  string(5) "false"
  ["socket.max.fails"]=>
  string(1) "3"
  ["broker.address.ttl"]=>
  string(4) "1000"
  ["broker.address.family"]=>
  string(3) "any"
  ["reconnect.backoff.jitter.ms"]=>
  string(1) "0"
  ["statistics.interval.ms"]=>
  string(1) "0"
  ["log_cb"]=>
  string(14) "0x7f04a5c130e0"
  ["log_level"]=>
  string(1) "6"
  ["log.thread.name"]=>
  string(5) "false"
  ["log.connection.close"]=>
  string(4) "true"
  ["socket_cb"]=>
  string(14) "0x7f04a5c1a350"
  ["open_cb"]=>
  string(14) "0x7f04a5c292b0"
  ["internal.termination.signal"]=>
  string(1) "0"
  ["quota.support.enable"]=>
  string(5) "false"
  ["protocol.version"]=>
  string(1) "0"
  ["security.protocol"]=>
  string(9) "plaintext"
  ["group.id"]=>
  string(17) "GroupConsumerTest"
  ["partition.assignment.strategy"]=>
  string(16) "range,roundrobin"
  ["session.timeout.ms"]=>
  string(5) "30000"
  ["heartbeat.interval.ms"]=>
  string(4) "1000"
  ["group.protocol.type"]=>
  string(8) "consumer"
  ["coordinator.query.interval.ms"]=>
  string(6) "600000"
  ["enable.auto.commit"]=>
  string(4) "true"
  ["auto.commit.interval.ms"]=>
  string(4) "5000"
  ["enable.auto.offset.store"]=>
  string(4) "true"
  ["queued.min.messages"]=>
  string(6) "100000"
  ["queued.max.messages.kbytes"]=>
  string(7) "1000000"
  ["fetch.wait.max.ms"]=>
  string(3) "100"
  ["fetch.message.max.bytes"]=>
  string(7) "1048576"
  ["fetch.min.bytes"]=>
  string(1) "1"
  ["fetch.error.backoff.ms"]=>
  string(3) "500"
  ["offset.store.method"]=>
  string(6) "broker"
  ["queue.buffering.max.messages"]=>
  string(6) "100000"
  ["queue.buffering.max.ms"]=>
  string(4) "1000"
  ["message.send.max.retries"]=>
  string(1) "2"
  ["retry.backoff.ms"]=>
  string(3) "100"
  ["compression.codec"]=>
  string(4) "none"
  ["batch.num.messages"]=>
  string(4) "1000"
  ["delivery.report.only.error"]=>
  string(5) "false"
}

**Comment by MarinoRaul** [comment]
ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
        at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)

**Comment by debug2012** [comment]
@MarinoRaul  no , I use java client instead

**Comment by shengbinxu** [comment]
I meet the same question too, my librdkafka version is  0.11.0, After a long attempt, I found the following solution：
```
 $conf = new Conf();
 $conf->set('group.id', 'consumerGroup1');
 $rk = new Consumer($conf);
```
as the description in [link](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md):

> Offset commit store method: 'file' - local file store (offset.store.path, et.al), 'broker' - broker commit store (requires "group.id" to be configured and Apache Kafka 0.8.2 or later on the broker.). 

when offset.store.method is set to broker, group.id required to be configured .

My complete kafka consume code is as follows：

 ```
$conf = new Conf();
$conf->set('group.id', 'consumerGroup1');
$rk = new Consumer($conf);
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers('192.168.98.128:9092,192.168.98.128:9093,192.168.98.128:9094');
$topicConf = new TopicConf();
$topicConf->set('auto.offset.reset', 'smallest');
$topicConf->set("auto.commit.interval.ms", 1e3);
//        print_r($topicConf->dump());
$topic = $rk->newTopic(self::LOG_TOPIC, $topicConf);
$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);
$count = 0;
while (true) {
	// The first argument is the partition (again).
	// The second argument is the timeout.
	if ($msg = $topic->consume(0, 120 * 1000)) {
		switch ($msg->err) {
			case RD_KAFKA_RESP_ERR_NO_ERROR:
				print_r($msg) . "\r\n";
				$count++;
				break;
			case RD_KAFKA_RESP_ERR__PARTITION_EOF:
				echo "No more messages; will wait for more\n";
				break;
			case RD_KAFKA_RESP_ERR__TIMED_OUT:
				echo "Timed out\n";
				break;
			default:
				throw new \Exception($msg->errstr(), $msg->err);
				break;
		}
	}
}
$topic->consumeStop(0); # I red that this is necessary
print 'received msg count:' . $count . "\r\n";
```

I am hoping to help you
