### ISSUE TITLE
How to get latest mesaage from kafka topic witout while loop

### ISSUE THREAD

**Issue by sanjaygoyan** [php-rdkafka/php-rdkafka#230]
`while (true) {
    // The first argument is the partition (again).
    // The second argument is the timeout.
    $msg = $topic->consume(0, 1000);
    if (null === $msg) {
        continue;
    } elseif ($msg->err) {
        echo $msg->errstr(), "\n";
        break;
    } else {
        echo $msg->payload, "\n";
    }
}
`
I would like a scheduler who calling this php in every 5 min so i need to get latest kafka topic message please help me.

 * PHP version:
 * librdkafka version:
 * php-rdkafka version:

**Comment by nick-zh** [comment]
Hey @sanjaygoyan 
I don't know your use case, but as far as i know, you cannot consume a batch of the latest messages. 
What you can do is to set  `enable.partition.eof ` to `true` (if you are using librdkafka => 1.0.0, if you use lower than 1.0.0 you don't need to set this) you will get the this in the error `RD_KAFKA_RESP_ERR__PARTITION_EOF` if you reached the end of a partition.
Maybe this helps, i am assuming, you don't want to run forever and that's what you are asking.

**Comment by sanjaygoyan** [comment]
Hi Nick, thanks for the quick response.

Actually the problem i am facing is as i am working on php version 5.6, and are trying to integrate rd-kafka into our project, while writing the consumer, i see While(true) code in all rd kafka examples, as for every iteration it fetch the records individually, i want to avoid this indefinite loop and want to have a scheduler which fetch only the N new records only after every X seconds. I do not want to keep this thread continuously in running state, i need to schedule the job and want to fetch every X seconds, only the new records.

I hope i am able to explain the problem i am facing, do let me know in case of any other details.
Regards,
Sanjay Goyan

**Comment by nick-zh** [comment]
Hey @sanjaygoyan 
You can either run until you consumed all your messages in this topic / partition, check my comment here:
https://github.com/arnaud-lb/php-rdkafka/issues/229#issuecomment-504886767
Or you can of course count and break your loop, depending on what you are doing in the loop, you might want to consider commiting the offset manually if there can be an error after the consume and the message needs to be read again.
Let me know if that helps.

Cheers,
Nick

**Comment by sanjaygoyan** [comment]
See Nick, actually consume() is returning single record at a time, i want to have an api which returns me a list of records which have been published to the topic. Only then i can iterate over recently fetched list and schedule the same task into a crone. Right now its not possible as the consume() api returns a single record at a time so while(true) is a must, is there any alternative to consume api which can return me the complete list of newly published items.
I understand that committing manually will avoid the repetition of same records. This can be done once i have alternative to while(true) code or a list of recently published records.

I hope i have made the statement pretty clear ! let me know if there is some other api to fetch complete list of records rather than fetching it individually in a blind loop

**Comment by Steveb-p** [comment]
> Only then i can iterate over recently fetched list and schedule the same task into a crone

May I ask what's the point? Why do you need to put anything into cron, when you should be perfectly fine using the consuming process to perform any task that is put into Kafka topic and use it a sort of load balancing mechanism (with possible multiple consumers / consumer groups performing multiple tasks synchronously and independently from each other).

Also, if you're really only interested in batching Kafka messages, then why not simply use something along the lines:
```php
$messageCount = 0;
$messages = [];
while ($messageCount < 100) {
    $message = $consumer->consume(1000);
    if ($message === null) {
        break;
    }
    $messages[] = $message;
    $messageCount++;
}
// do whatever you want with $messages
```

There is nothing preventing you from breaking the `while(true)` loop.

**Comment by nick-zh** [comment]
I agree with @Steveb-p if we know more, we could suggest an approach, as it stands i have found nothing where you can consume more than one message, i checked the C lib as well (i might have missed something, but i also never heard of a batch consume). I would suggest as well, consume until the partition is empty and process (or loop until a certain amount is reached and then process).

**Comment by sanjaygoyan** [comment]
Thanks Steveb and Nick i have follow your idea and write following code but i get following error in commit part.
`$messageCount = 0;
$messages = [];
while ($messageCount < 100) {
    $message = $topic->consume(0, 1000);
    if ($message === null) {
        break;
    }
    $messages[] = $message;
    $messageCount++;
    $topic->commit();
}
`
PHP Fatal error:  Call to undefined method RdKafka\ConsumerTopic::commit() in /c1.php on line 23

I have taken comit code from below link.

https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-kafkaconsumer.commit.html

**Comment by Steveb-p** [comment]
You're calling `commit` on `ConsumerTopic` (which is usually the result of calling `KafkaConsumer::createTopic()`). You want to call `commit` on `KafkaConsumer` instance instead. 

Error message is enough to deduce as much - just look at the class name.

Also, unless you have it specifically disabled in configuration object passed when creating `KafkaConsumer`, client will automatically commit consumed messages, so you don't need to call this method yourself. This relies on `enable.auto.commit` setting (which is `true` by default). See https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management#configuration-properties

**Comment by sanjaygoyan** [comment]
Tried below code 
`RdKafka\Consumer::commit();`
`$rk->commit()`
`$rk->commit($message)`

Gives me following error
Call to undefined method RdKafka\Consumer::commit()

**Comment by Steveb-p** [comment]
`RdKafka\Consumer::commit();` notation is oftentimes used as shorthand to indicate calling of an **object's method**. You're code is trying to call **static function** instead, since you've copied it without understanding what it means.

You're expected to call **RdKafka\Consumer instance method called `commit`**. Calling it statically won't work (such a static function **does not exist**) and calling it on an object of a different class won't work either.

Errors are painfully descriptive and tell you exactly what you're doing wrong. We can't really help you with understanding of PHP's basics, with all due respect.

**Comment by sanjaygoyan** [comment]
`$topicConf = new RdKafka\TopicConf();
$topicConf->set("auto.commit.enable", 'false');

$rk = new RdKafka\Consumer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("localhost:9092");

$topic = $rk->newTopic("SFSToWeb");
$topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);



$messageCount = 0;
$messages = [];
while ($messageCount < 100) {
    $message = $topic->consume(0, 1000);
    if ($message === null) {
        break;
    }
    $messages[] = $message;
    $messageCount++;
    $rk->commit();
}`

here $rk object of $rk = new RdKafka\Consumer(); same thing i have mention in previous thread also.
Error came on the below line     RdKafka\Consumer::commit();

PHP Fatal error:  Call to undefined method RdKafka\Consumer::commit() in

**Comment by nick-zh** [comment]
@sanjaygoyan for the low level consumer in your example you need to call

```
$topic->offsetStore($message->partition, $message->offset);
```
instead of
```
$rk->commit();
```

**Comment by sanjaygoyan** [comment]
`<?php
$topicConf = new RdKafka\TopicConf();
$topicConf->set("auto.commit.enable", 'false');
$topicConf->set("auto.offset.reset", 'largest');

$rk = new RdKafka\Consumer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("localhost:9092");

$topic = $rk->newTopic("SFSToWeb");
$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);

$messageCount = 0;
$messages = [];
while ($messageCount < 5500) {
    $message = $topic->consume(0,1000);
    if ($message === null) {
        break;
    }
    $messages[] = $message;
    $messageCount++;
    //$rk->commit($messages);
    $topic->offsetStore($message->partition, $message->offset);
}`

Hi Nick this line gives no error `    $topic->offsetStore($message->partition, $message->offset);`
But i need to read only those message who are not read yet for that i am using $topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);

but its give error.

PHP Fatal error:  Uncaught exception 'RdKafka\Exception' with message 'Local: Invalid argument or configuration' in /usr/share/nginx/html/tj.adda52rummy.org/www/kafka/c1.php:13
Stack trace:
#0 /kafka/c1.php(13): RdKafka\ConsumerTopic->consumeStart(0, -1000)
#1 {main}
  thrown in //www/kafka/c1.php on line 13

**Comment by nick-zh** [comment]
@sanjaygoyan you may want to add this at the start of the file
```
$conf = new RdKafka\Conf();
$conf->set('group.id', 'myConsumerGroup');
```
and adjust consumer instantiation
```
$rk = new RdKafka\Consumer($conf);
```
More examples for low level consumer can also be found here:
http://arnaud.le-blanc.net/php-rdkafka/phpdoc/rdkafka.examples-low-level-consumer.html

**Comment by sanjaygoyan** [comment]
Hay Nick thanks its working now, can i integrate this rdkafka module into the code iginitor 2.1.2

**Comment by nick-zh** [comment]
@sanjaygoyan you are very welcome, i am not familiar with code igniter, but as it is a PHP framework (at least form what i read), integration should be possible since this is just a php module, so wherever you can use php you can use this :sunglasses:

**Comment by sanjaygoyan** [comment]
Thanks for your support Nick I have integrated rdkafka in codeiginitor also.
