### ISSUE TITLE
Create release 3.1.1

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#231]
Maybe another minor release (3.1.1) would be nice (especially since the segfault for producev was fixed), what do you think @arnaud-lb ?

As per 4th of June (was the last commit as of 26.6):

# rdkafka v3.1.1 release

## Features
* expose query watermark offsets (#219)

## Enhancements
* support sending timestamp (epoch ms) to producev (#228)

## Fixes
* fix KafkaTopic::producev causing segfault on librdkafka 1.0.0 (#222)
* fix version print (#224)

**Comment by nick-zh** [comment]
@arnaud-lb

**Comment by arnaud-lb** [comment]
Released 3.1.1 on github and pecl. 

Thank you for the change log. I just added usernames next to the PR numbers.

**Comment by nick-zh** [comment]
@arnaud-lb perfect, thank you very much. ah yes perfect, i forgot the usernames :stuck_out_tongue_closed_eyes:
