### ISSUE TITLE
Expose librdkafka version as string

### ISSUE THREAD

**Issue by Steveb-p** [php-rdkafka/php-rdkafka#232]
* PHP version: irrelevant
 * librdkafka version: irrelevant
 * php-rdkafka version: irrelevant

Is it worthwile to add a function or constant in phprdkafka that would expose build/runtime Kafka versions as a string, not only as their binary-ish representations? I would add it myself, but figured I'd ask before doing something that won't be accepted.

I'm using a library that probably would include below code just to detect incompatible versions (due to segfault).

```php
if (!defined('RD_KAFKA_VERSION')) {
    throw new \RuntimeException('RD_KAFKA_VERSION constant is not defined. Phprdkafka is probably not installed');
}
$major = (RD_KAFKA_VERSION & 0xFF000000) >> 24;
$minor = (RD_KAFKA_VERSION & 0x00FF0000) >> 16;
$patch = (RD_KAFKA_VERSION & 0x0000FF00) >> 8;
```

This is done to feed it further to `version_compare`. Also as far as I know it is something that is done for `phpinfo()` information display as well.

**Comment by arnaud-lb** [comment]
I would accept a PR adding a `rd_kafka_version_str(int $version): string` function (it would work with `RD_KAFKA_VERSION` and `RD_KAFKA_BUILD_VERSION`).

However, note that the binary/integer version is already comparable (you don't need `version_compare()`). For example, doing something like `RD_KAFKA_VERSION >= 0x03000100` checks that the version is >= 3.0.1.

**Comment by nick-zh** [comment]
@Steveb-p what is the current status on this?
