### ISSUE TITLE
how can I set the logger using rd_kafka_conf_set_log_cb

### ISSUE THREAD

**Issue by kirachen1991** [php-rdkafka/php-rdkafka#233]
* PHP version:7.3.6
 * librdkafka version:1.1.0
 * php-rdkafka version:3.1.0

It seems like that I can set logger by using the function rd_kafka_conf_set_log_cb

But I can not find the way to do

I read the document, that function RdKafka\Conf::set can set rd_kafka_conf_set_log_cb, but
I don't know how to set……

**Comment by nick-zh** [comment]
@kirachen1991 from what i see in the doc and the code, it seems this is not implemented in the lib yet, but if you have some C knowledge, here are the other callbacks, probably it would be not so hard to create a PR:
https://github.com/arnaud-lb/php-rdkafka/blob/master/conf.c
Relates to: https://github.com/arnaud-lb/php-rdkafka/issues/127

**Comment by Steveb-p** [comment]
Awesome work @nick-zh :) This issue might be closed and/or a documentation one should be opened?

**Comment by nick-zh** [comment]
@Steveb-p thank you, actually i already have a doc pr open for this: https://github.com/arnaud-lb/php-rdkafka-doc/pull/26
think this can be closed
