### ISSUE TITLE
[3.1.1] broken build with PHP 5.6 (ZVAL_DEREF)

### ISSUE THREAD

**Issue by remicollet** [php-rdkafka/php-rdkafka#235]
`PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/php56-php-pecl-rdkafka-3.1.1-1.fc29.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/rdkafka.so' - /builddir/build/BUILDROOT/php56-php-pecl-rdkafka-3.1.1-1.fc29.remi.x86_64/opt/remi/php56/root/usr/lib64/php/modules/rdkafka.so: undefined symbol: ZVAL_DEREF in Unknown on line 0
`

Indeed, ZVAL_DEREF is 7.0+ only

**Comment by nick-zh** [comment]
@arnaud-lb i saw you fixed some stuff, can this be resolved or still ongoing?

**Comment by remicollet** [comment]
I confirm 15bc0173ef7b06ef16e477e8b12c3eac5bcf2abc fixes this issue.

**Comment by nick-zh** [comment]
@remicollet perfect, thx, can be closed then? I guess until a new release is out, you need to build from the current master

**Comment by arnaud-lb** [comment]
Thanks @remicollet. I've just released 3.1.2, which fixes this.

**Comment by nick-zh** [comment]
https://github.com/arnaud-lb/php-rdkafka/releases/tag/3.1.2
