### ISSUE TITLE
how catch this error

### ISSUE THREAD

**Issue by xfmo** [php-rdkafka/php-rdkafka#237]
how to catch this error ，then restart the thread

%3|1562912413.181|ERROR|rdkafka#consumer-1| [thrd:1*:9092/bootstrap]: *:9092/1: Disconnected (after 1200007ms in state UP)

 * PHP version:7.0
 * librdkafka version:
 * php-rdkafka version:3.1.0

**Comment by nick-zh** [comment]
Probably the idle reaper is killing your connection (config is this i think: `connections.max.idle.ms`)
this can probably be handled with this callback https://arnaud.le-blanc.net/php-rdkafka/phpdoc/rdkafka-conf.seterrorcb.html
I am uncertain if it is possible / wise to reconnect in the CB for this case. Maybe just exiting the thread and kicking off a new one would be fine, this would have to be done by your overlaying logic that handles your threads

**Comment by xfmo** [comment]
In  my case,  set kafka 10 partition  and 10 consumer thread ，but some partition lag so much。I then restart consumer thread   kafka  no lag。
I only see   ‘%3|1562912413.181|ERROR|rdkafka#consumer-1| [thrd:1*:9092/bootstrap]: *:9092/1: Disconnected (after 1200007ms in state UP)’
How can I do  ？

I want to exit thread and then use supervisor to restart thead，Is my method feasible？

$conf->setErrorCb(function ($kafka, $err, $reason) {
            exit();
        });

**Comment by nick-zh** [comment]
@xfmo you closed this, have you resolved your issue?

**Comment by xfmo** [comment]
> @xfmo you closed this, have you resolved your issue?

I know how to log this error 。but i have above question 'some partition lag so much'，I'm sorry I didn't describe the problem clearly。

**Comment by nick-zh** [comment]
@xfmo so this is a new issue that you have? if so, you can open of course a new issue and maybe explain further what exactly is happening :)
