### ISSUE TITLE
RD_KAFKA_OFFSET_STORED not work

### ISSUE THREAD

**Issue by asaarashi** [php-rdkafka/php-rdkafka#24]
I ran /examples/producer.php and /examples/consumer.php and it worked well. But if I changes consumer.php:9 as the following:

``` php
// $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING); // Before
$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED); // After
```

It always output

```
Broker: No more messages
```

What's the possible reason?

I run it on CentOS 6.7/PHP 7.0.1.

**Comment by arnaud-lb** [comment]
Hi @thrieu,

I think you have to configure [`auto.offset.reset`](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). This defines where to start when no offset has been previously stored: smallest offset (older messages), or largest offset (latest message).

**Comment by asaarashi** [comment]
@arnaud-lb 
I've tried

``` php
        $topicConf->set("auto.offset.reset", 'largest');
```

and 

``` php
        $topicConf->set("auto.offset.reset", 'smallest');
```

But neither of them works.

Thank you for quick reply. I am a newbie of Kafka, I just do some test cases to determine whether to use Kafka in my project.

**Comment by vchampion** [comment]
By default RD_KAFKA_OFFSET_STORED stores position in the file near you php script. May be it's not enough permissions to folder where script stored for writing for your web server?

**Comment by asaarashi** [comment]
Hi, @vchampion , the mode of the offset file is 777, but it is always empty. Maybe this is a clue.
Thank you.

**Comment by vchampion** [comment]
So, that is my working script with kafka, please compare with your script

```
<?php
header('Content-type: text/plain');

$rk = new RdKafka\Consumer();

$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094");

$topicConf = new RdKafka\TopicConf();
$topicConf->set("auto.commit.interval.ms", 1e3);
$topicConf->set("offset.store.sync.interval.ms", 60e3);

$topic = $rk->newTopic("created-from-php", $topicConf);

$consumeOffset = $_REQUEST['offset'] ?: RD_KAFKA_OFFSET_STORED;

$topic->consumeStart(0, $consumeOffset);
// $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);

$count =0 ;
while (true) 
{
    // The first argument is the partition (again).
    // The second argument is the timeout.
    if($msg = $topic->consume(0, 1000)) {
       if ($msg->err) {
           break;
       } else {
       echo $msg->payload . PHP_EOL;
       $count++;
       }
    }
}

$topic->consumeStop(0); # I red that this is necessary

print $count;
```

**Comment by asaarashi** [comment]
Hi, @vchampion , I got the same result: error no `-191` whose corresponding message is `Broker: No more messages`. Maybe it is caused by some environment reason or unknown bug. 
Thanks for your help.

**Comment by vchampion** [comment]
So, as I understand you use php 7, can you try install php 5.6 and test with it? 
That's my environment

```
rdkafka      0.0.2
librdkafka   0.8.6.0
system       OS X Maverics
PHP          5.6.16
```

**Comment by vchampion** [comment]
>  the mode of the offset file is 777, but it is always empty

and so offset file is created by script but doesn't written with offset, yes? try set permissions to folder containing your script to 777

**Comment by asaarashi** [comment]
@vchampion The offset file's content is `0`, so it may not be due to permission problem.
I'll try running it on another PHP version when I have time.

**Comment by doubleycn** [comment]
I have the error msg!

`PHP Fatal error:  Uncaught exception 'RdKafka\Exception' with message 'Local: Invalid argument or configuration' in /home/xxx/soft/php-rdkafka/examples/consumer.php:18
Stack trace:
#0 /home/xxx/soft/php-rdkafka/examples/consumer.php(18): RdKafka\ConsumerTopic->consumeStart(0, -1000)
#1 {main}
  thrown in /home/xxx/soft/php-rdkafka/examples/consumer.php on line 18

Fatal error: Uncaught exception 'RdKafka\Exception' with message 'Local: Invalid argument or configuration' in /home/xxx/soft/php-rdkafka/examples/consumer.php:18
Stack trace:
#0 /home/xxx/soft/php-rdkafka/examples/consumer.php(18): RdKafka\ConsumerTopic->consumeStart(0, -1000)
#1 {main}
  thrown in /home/xxx/soft/php-rdkafka/examples/consumer.php on line 18
`
the code:
`<?php

$rk = new RdKafka\Consumer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("127.0.0.1:8092, 127.0.0.1:8093");

$topicConf = new RdKafka\TopicConf();
/* The frequency in milliseconds that the consumer offsets are commited (written) to offset storage. (0 = disable) */
$topicConf->set("auto.commit.interval.ms", 1e3);
$topicConf->set("offset.store.sync.interval.ms", 60e3);
//$topicConf->set("group.id", "test.id");

$topic = $rk->newTopic("test", $topicConf);

// The first argument is the partition to consume from.
// The second argument is the offset at which to start consumption. Valid values
// are: RD_KAFKA_OFFSET_BEGINNING, RD_KAFKA_OFFSET_END, RD_KAFKA_OFFSET_STORED.
$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);
`

In C code:
`
...
} else if (offset == RD_KAFKA_OFFSET_STORED) {
        /* offset manager */

                if (rkt->rkt_conf.offset_store_method ==
                    RD_KAFKA_OFFSET_METHOD_BROKER &&
                    RD_KAFKAP_STR_IS_NULL(rkt->rkt_rk->rk_conf.group_id)) { // I don't have group_id
                        /* Broker based offsets require a group id. */
                        rd_kafka_toppar_destroy(s_rktp);
                        errno = EINVAL;
                        return -1;
                }
...
`
PHP 5.5.9 (cli) (built: Feb 16 2016 17:03:43) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by keyurshah070** [comment]
Same issue happen with me . Any luck ? 

I am using this argument to get only new messages. But no luck

**Comment by evander-wang** [comment]
To use $topicConf
$topicConf->set('offset.store.method', 'broker');
$topicConf->set('auto.offset.reset', 'smallest');

**Comment by wendy-rose** [comment]
> Hi, @vchampion , the mode of the offset file is 777, but it is always empty. Maybe this is a clue. Thank you.

hello, where is the mode of the offset file?

**Comment by nick-zh** [comment]
This has been deprecated

**Comment by JoeByte** [comment]
```php
$topicConf->set('offset.store.method', 'file');
$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);
```
try this, it works 
If you set `RD_KAFKA_OFFSET_STORED`, 
you would better set `$topicConf->set('offset.store.method', 'file')`

this will auto create a file which record the offset
