### ISSUE TITLE
how to make 

### ISSUE THREAD

**Issue by ReturnLab** [php-rdkafka/php-rdkafka#25]
i use centos 6.7 64 system
when configure and make command like this

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged

/bin/sh /root/kafka/php-rdkafka-master/libtool --mode=compile cc  -I. -I/root/kafka/php-rdkafka-master -DPHP_ATOM_INC -I/root/kafka/php-rdkafka-master/include -I/root/kafka/php-rdkafka-master/main -I/root/kafka/php-rdkafka-master -I/data/bin/php/include/php -I/data/bin/php/include/php/main -I/data/bin/php/include/php/TSRM -I/data/bin/php/include/php/Zend -I/data/bin/php/include/php/ext -I/data/bin/php/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O0   -c /root/kafka/php-rdkafka-master/rdkafka.c -o rdkafka.lo
mkdir .libs
 cc -I. -I/root/kafka/php-rdkafka-master -DPHP_ATOM_INC -I/root/kafka/php-rdkafka-master/include -I/root/kafka/php-rdkafka-master/main -I/root/kafka/php-rdkafka-master -I/data/bin/php/include/php -I/data/bin/php/include/php/main -I/data/bin/php/include/php/TSRM -I/data/bin/php/include/php/Zend -I/data/bin/php/include/php/ext -I/data/bin/php/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O0 -c /root/kafka/php-rdkafka-master/rdkafka.c  -fPIC -DPIC -o .libs/rdkafka.o
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘kafka_init’:
/root/kafka/php-rdkafka-master/rdkafka.c:142: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: At top level:
/root/kafka/php-rdkafka-master/rdkafka.c:148: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘kafka_new’
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘get_kafka_object’:
/root/kafka/php-rdkafka-master/rdkafka.c:166: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘kafka_conf_free’:
/root/kafka/php-rdkafka-master/rdkafka.c:185: error: used struct type value where scalar is required
/root/kafka/php-rdkafka-master/rdkafka.c: At top level:
/root/kafka/php-rdkafka-master/rdkafka.c:202: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘kafka_conf_new’
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘get_kafka_conf_object’:
/root/kafka/php-rdkafka-master/rdkafka.c:220: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘kafka_conf_error_cb’:
/root/kafka/php-rdkafka-master/rdkafka.c:239: error: wrong type argument to unary exclamation mark
/root/kafka/php-rdkafka-master/rdkafka.c:247:35: error: macro "ZVAL_STRING" passed 3 arguments, but takes just 2
/root/kafka/php-rdkafka-master/rdkafka.c:247: error: ‘ZVAL_STRING’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:247: error: (Each undeclared identifier is reported only once
/root/kafka/php-rdkafka-master/rdkafka.c:247: error: for each function it appears in.)
/root/kafka/php-rdkafka-master/rdkafka.c:252: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
/root/kafka/php-rdkafka-master/rdkafka.c:253: warning: assignment from incompatible pointer type
/root/kafka/php-rdkafka-master/rdkafka.c:259: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/data/bin/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
/root/kafka/php-rdkafka-master/rdkafka.c:261: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/data/bin/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
/root/kafka/php-rdkafka-master/rdkafka.c:262: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/data/bin/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
/root/kafka/php-rdkafka-master/rdkafka.c: At top level:
/root/kafka/php-rdkafka-master/rdkafka.c:284: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘kafka_queue_new’
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘get_kafka_queue_object’:
/root/kafka/php-rdkafka-master/rdkafka.c:302: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘kafka_topic_free’:
/root/kafka/php-rdkafka-master/rdkafka.c:320: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/data/bin/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
/root/kafka/php-rdkafka-master/rdkafka.c: At top level:
/root/kafka/php-rdkafka-master/rdkafka.c:329: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘kafka_topic_new’
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘get_kafka_topic_object’:
/root/kafka/php-rdkafka-master/rdkafka.c:347: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Conf___construct’:
/root/kafka/php-rdkafka-master/rdkafka.c:401: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Conf_dump’:
/root/kafka/php-rdkafka-master/rdkafka.c:428: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:449:67: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
/root/kafka/php-rdkafka-master/rdkafka.c:449: error: ‘add_assoc_string’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Conf_set’:
/root/kafka/php-rdkafka-master/rdkafka.c:479: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Conf_setErrorCb’:
/root/kafka/php-rdkafka-master/rdkafka.c:525: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:530: error: incompatible type for argument 1 of ‘zval_addref_p’
/data/bin/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
/root/kafka/php-rdkafka-master/rdkafka.c:532: error: used struct type value where scalar is required
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeQueueStart’:
/root/kafka/php-rdkafka-master/rdkafka.c:579: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeStart’:
/root/kafka/php-rdkafka-master/rdkafka.c:624: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consumeStop’:
/root/kafka/php-rdkafka-master/rdkafka.c:662: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_consume’:
/root/kafka/php-rdkafka-master/rdkafka.c:702: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ConsumerTopic_offsetStore’:
/root/kafka/php-rdkafka-master/rdkafka.c:742: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Consumer___construct’:
/root/kafka/php-rdkafka-master/rdkafka.c:785: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_addBrokers’:
/root/kafka/php-rdkafka-master/rdkafka.c:813: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_metadata’:
/root/kafka/php-rdkafka-master/rdkafka.c:844: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_setLogLevel’:
/root/kafka/php-rdkafka-master/rdkafka.c:883: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_newQueue’:
/root/kafka/php-rdkafka-master/rdkafka.c:908: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:923: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_newTopic’:
/root/kafka/php-rdkafka-master/rdkafka.c:956: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:989: warning: cast to pointer from integer of different size
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_outqLen’:
/root/kafka/php-rdkafka-master/rdkafka.c:1014: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_poll’:
/root/kafka/php-rdkafka-master/rdkafka.c:1039: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Kafka_setLogger’:
/root/kafka/php-rdkafka-master/rdkafka.c:1065: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1085: warning: ‘rd_kafka_set_logger’ is deprecated (declared at /usr/local/include/librdkafka/rdkafka.h:2103)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Message_errstr’:
/root/kafka/php-rdkafka-master/rdkafka.c:1118: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1118: error: too few arguments to function ‘zend_read_property’
/root/kafka/php-rdkafka-master/rdkafka.c:1124: error: too few arguments to function ‘zend_read_property’
/root/kafka/php-rdkafka-master/rdkafka.c:1133:32: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/root/kafka/php-rdkafka-master/rdkafka.c:1133: error: ‘RETURN_STRING’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__ProducerTopic_produce’:
/root/kafka/php-rdkafka-master/rdkafka.c:1179: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Producer___construct’:
/root/kafka/php-rdkafka-master/rdkafka.c:1216: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Queue_consume’:
/root/kafka/php-rdkafka-master/rdkafka.c:1245: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__TopicConf___construct’:
/root/kafka/php-rdkafka-master/rdkafka.c:1286: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__TopicConf_setPartitioner’:
/root/kafka/php-rdkafka-master/rdkafka.c:1310: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zim_RdKafka__Topic_getName’:
/root/kafka/php-rdkafka-master/rdkafka.c:1355: error: ‘this_ptr’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1360:54: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/root/kafka/php-rdkafka-master/rdkafka.c:1360: error: ‘RETURN_STRING’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1384:32: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zif_rd_kafka_err2str’:
/root/kafka/php-rdkafka-master/rdkafka.c:1384: error: ‘RETURN_STRING’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c: In function ‘zm_startup_rdkafka’:
/root/kafka/php-rdkafka-master/rdkafka.c:1515: error: ‘kafka_new’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1518: error: too many arguments to function ‘zend_register_internal_class_ex’
/root/kafka/php-rdkafka-master/rdkafka.c:1521: error: too many arguments to function ‘zend_register_internal_class_ex’
/root/kafka/php-rdkafka-master/rdkafka.c:1525: error: ‘kafka_conf_new’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1534: error: ‘kafka_topic_new’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1537: error: too many arguments to function ‘zend_register_internal_class_ex’
/root/kafka/php-rdkafka-master/rdkafka.c:1540: error: too many arguments to function ‘zend_register_internal_class_ex’
/root/kafka/php-rdkafka-master/rdkafka.c:1554: error: ‘kafka_queue_new’ undeclared (first use in this function)
/root/kafka/php-rdkafka-master/rdkafka.c:1557: error: too many arguments to function ‘zend_register_internal_class_ex’

**Comment by arnaud-lb** [comment]
Hi @godla,

Which PHP version are you building against ? For PHP7, you need to use the php7 branch: https://github.com/arnaud-lb/php-rdkafka/tree/php7

If this doesn't fix your problem, could you try building with `CFLAGS="-Wall"` and post the result here ? e.g. `CFLAGS="-Wall -g -O0" ./configure && make`

**Comment by ReturnLab** [comment]
thank you
