### ISSUE TITLE
Call to undefined method RdKafka\ProducerTopic::producev()

### ISSUE THREAD

**Issue by harshadvichare** [php-rdkafka/php-rdkafka#260]
While sending message with headers we are getting following errors.

Fatal error: Uncaught Error: Call to undefined method RdKafka\ProducerTopic::producev()
 
PHP version: 7.0
librdkafka version: librdkafka-0.11.6
php-rdkafka version: php-rdkafka-3.0.5

Is any configuration parameters we need to pass while producing message ? 
Or  we are missing something else.

**Comment by Steveb-p** [comment]
![image](https://user-images.githubusercontent.com/3183926/62604169-c26f0780-b8f7-11e9-85cc-efa303028875.png)

Not really. Just update php-rdkafka ;)

https://arnaud.le-blanc.net/php-rdkafka/phpdoc/rdkafka-producertopic.producev.html
