### ISSUE TITLE
does it support the group feature?

### ISSUE THREAD

**Issue by lnparker** [php-rdkafka/php-rdkafka#27]
For example, there are two consumers in one group consuming one topic, so the two consumers can get different messages from the topic.  
Do this project support this group feature?
I use like following, but it seems does not work. The two consumers(two processes) get all the messages from the topic. 

$topicConf = new RdKafka\TopicConf();
$topicConf->set("auto.commit.interval.ms", 1e3);
$topicConf->set("offset.store.sync.interval.ms", 60e3);
$topicConf->set("group.id", 'group1'); 

$rk = new RdKafka\Consumer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("10.110.16.46:9092,10.110.16.47:9092,10.110.16.48:9092");

$topic = $rk->newTopic("test1", $topicConf);
$topic->consumeStart(1, RD_KAFKA_OFFSET_BEGINNING);

$queue = $rk->newQueue();

$topic->consumeQueueStart(0, RD_KAFKA_OFFSET_BEGINNING, $queue);
$topic->consumeQueueStart(1, RD_KAFKA_OFFSET_BEGINNING, $queue);

$i = 0;
while (true) {
    $msg = $queue->consume(1000);
    if ($msg->err) {
        echo "----------------" . $msg->errstr(), "\n";
    } else { 
        echo $msg->payload, "\n";
    }  
    echo " ======= " . $i++ .  " ===============  " . "\n";
    usleep(1000);
}

**Comment by arnaud-lb** [comment]
In librdkafka 0.8, the `group.id` is only used as a kind of namespace for storing offsets on the server. It doesn't automatically assign partitions to consumers. You have to manually consume specific partitions in each consumer. You can obtain the number of partitions by using $rk->metadata().

There is a work in progress on librdkafka edge to support the new Kafka 0.9 protocol. I'm planning on adding this to php-rdkafka.

**Comment by arnaud-lb** [comment]
https://github.com/arnaud-lb/php-rdkafka/pull/30 adds support for the new KafkaConsumer
