### ISSUE TITLE
Throw \InvalidArgumentException on invalid partitioner in TopicConf::setPartitioner?

### ISSUE THREAD

**Issue by dirx** [php-rdkafka/php-rdkafka#279]
Why not throwing \InvalidArgumentException in TopicConf::setPartitioner instead of \Exception?
\InvalidArgumentException is used, for example, when checking for partition or batch size ranges.

https://github.com/arnaud-lb/php-rdkafka/blob/e028db86f213befbe9b51265f0237ed7211f281d/conf.c#L809

**Comment by nick-zh** [comment]
@dirx thx for the report, makes sense :+1:
