### ISSUE TITLE
Segmentation fault with Conf::setLogCb

### ISSUE THREAD

**Issue by dirx** [php-rdkafka/php-rdkafka#280]
* PHP version: 7.2.21 & 7.4-rc1 (both with xdebug)
 * librdkafka version: v1.0.0
 * php-rdkafka version: master
 * kafka version: -

Script crashes with "segmentation fault" while all works fine when explicitly setting ```$conf->set('log.queue', 'true');```:

```php
<?php

use RdKafka\Conf;
use RdKafka\Consumer;

$loggerCallbacks = 0;

$conf = new Conf();
$conf->set('debug', 'consumer');
$conf->set('log_level', (string)LOG_DEBUG);
//$conf->set('log.queue', 'true');
$conf->setLogCb(function (Consumer $consumer, int $level, string $fac, string $buf) use (&$loggerCallbacks) {
    $loggerCallbacks++;
});

$consumer = new Consumer($conf);
do {
    $consumer->poll(0);
} while ($loggerCallbacks === 0);

var_dump($loggerCallbacks); // expect 1
```

**Comment by nick-zh** [comment]
@dirx thx for the report, the extension should do this on it's own, but it seems something is amiss then, i will check it out
