### ISSUE TITLE
consumer group cannot be set

### ISSUE THREAD

**Issue by ssi-anik** [php-rdkafka/php-rdkafka#285]
New to Apache Kafka. Trying to learn from other people's code. 
 * PHP version: `7.3.0RC6`
 * librdkafka version:
![librdkafka-version](https://user-images.githubusercontent.com/2676602/65893798-69d55b80-e3ca-11e9-8746-df95c4e601eb.png)
 * php-rdkafka version: 
![php-rdkafka](https://user-images.githubusercontent.com/2676602/65894008-ce90b600-e3ca-11e9-8857-70e89bdde3a2.png)

 * kafka version: `bitnami/kafka:2.3.0`
![php-docker](https://user-images.githubusercontent.com/2676602/65893672-24b12980-e3ca-11e9-98ea-fe4c03929de4.png)
---
1. I want to set `group.id` to consumer like in the Java tutorials. I took the code from [HERE](https://developpaper.com/kafka-php-uses-rdkafka-production-consumption-data/)
![php-conf-set-group.id](https://user-images.githubusercontent.com/2676602/65893339-9e94e300-e3c9-11e9-9b9a-ba06ae56d8b4.png)
2. From [HERE](https://stackoverflow.com/a/41645130/2190689) I can list and describe my consumer groups.
![consumer-group-answer](https://user-images.githubusercontent.com/2676602/65894268-46f77700-e3cb-11e9-997d-b7ad3516e436.png)
3. But when I run the command within my container, I find nothing.
![group-doesnt-exist-error](https://user-images.githubusercontent.com/2676602/65894359-773f1580-e3cb-11e9-8ed4-ee675c4e9353.png)
4. But when used from console-consumer command, it's shown in the list.
![console-consumer](https://user-images.githubusercontent.com/2676602/65894650-e7e63200-e3cb-11e9-8cf9-9676ec04e6ca.png)

Can you please inform how can I set the group id for my kafka consumer from PHP? TIA.

**Comment by ssi-anik** [comment]
I found how to do it. [HERE](https://developpaper.com/kafka-php-uses-rdkafka-production-consumption-data/) under `Consumer-High Level` section.

**Comment by nick-zh** [comment]
For future reference, the documentation with examples can be found here:
https://arnaud.le-blanc.net/php-rdkafka/phpdoc/book.rdkafka.html
Cheers
