### ISSUE TITLE
brew fail

### ISSUE THREAD

**Issue by sgpennebaker** [php-rdkafka/php-rdkafka#287]
* PHP version: 7.1.23
 * librdkafka version: 1.2.0
 * php-rdkafka version: none
 * kafka version: 2.3.0

tried a couple of other versions for fun, they also fail:

brew install php71-rdkafka

(skipping brew bookkeeping)

Error: No available formula with the name "php71-rdkafka" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

thanks!  sgpennebaker

**Comment by nick-zh** [comment]
i am not familiar with osx installation, with a quick search i only found this:
https://github.com/Homebrew/homebrew-core/issues/26875
I suspect, that the documentation might be outdated.
Maybe you could try installing it through PECL

**Comment by sgpennebaker** [comment]
you should probably take the brew documentation out then...

trying to do the manual build now (much comedy), will try PECL next.

**Comment by nick-zh** [comment]
@sgpennebaker i updated the doc. I am closing this for now, if you were not able to install through pecl, you can still let me know here :+1:
