### ISSUE TITLE
rdkafka 4.0 questions

### ISSUE THREAD

**Issue by Jukit-Barrett** [php-rdkafka/php-rdkafka#289]
* PHP version: docker  php:7.2.23-cli-alpine
 * librdkafka version: 
 * php-rdkafka version: 4.0.0
 * kafka version: 

## question 1:
````
/usr/src/php/ext/rdkafka/rdkafka.c: In function 'zim_RdKafka__Kafka_setLogger':
/usr/src/php/ext/rdkafka/rdkafka.c:728:5: warning: 'rd_kafka_set_logger' is deprecated [-Wdeprecated-declarations]
     rd_kafka_set_logger(intern->rk, logger);
     ^~~~~~~~~~~~~~~~~~~
In file included from /usr/src/php/ext/rdkafka/php_rdkafka.h:24,
                 from /usr/src/php/ext/rdkafka/rdkafka.c:28:
/usr/include/librdkafka/rdkafka.h:3792:6: note: declared here
 void rd_kafka_set_logger(rd_kafka_t *rk,
      ^~~~~~~~~~~~~~~~~~~
````

## question 2:
````
/usr/src/php/ext/rdkafka/conf.c: In function 'zim_RdKafka__Conf_setLogCb':
/usr/src/php/ext/rdkafka/conf.c:759:44: warning: passing argument 2 of 'rd_kafka_conf_set_log_cb' from incompatible pointer type [-Wincompatible-pointer-types]
     rd_kafka_conf_set_log_cb(conf->u.conf, kafka_conf_log_cb);
                                            ^~~~~~~~~~~~~~~~~
In file included from /usr/src/php/ext/rdkafka/php_rdkafka.h:24,
                 from /usr/src/php/ext/rdkafka/conf.c:26:
/usr/include/librdkafka/rdkafka.h:1733:13: note: expected 'void (*)(const rd_kafka_t *, int,  const char *, const char *)' {aka 'void (*)(const struct rd_kafka_s *, int,  const char *, const char *)'} but argument is of type 'void (*)(rd_kafka_t *, int,  const char *, const char *)' {aka 'void (*)(struct rd_kafka_s *, int,  const char *, const char *)'}
      void (*log_cb) (const rd_kafka_t *rk, int level,
      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           const char *fac, const char *buf));
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

## question 3:
````
/usr/src/php/ext/rdkafka/fun.c: In function 'zif_rd_kafka_errno2err':
/usr/src/php/ext/rdkafka/fun.c:143:5: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
     RETURN_LONG(rd_kafka_errno2err(errnox));
     ^~~~~~~~~~~
In file included from /usr/src/php/ext/rdkafka/php_rdkafka.h:24,
                 from /usr/src/php/ext/rdkafka/fun.c:24:
/usr/include/librdkafka/rdkafka.h:640:21: note: declared here
 rd_kafka_resp_err_t rd_kafka_errno2err(int errnox);
                     ^~~~~~~~~~~~~~~~~~
````

**Comment by nick-zh** [comment]
Dear @jiegege 

Question 1 + 3 relate to this: #251 and #254, in version 4.0 we deprecated stuff that is deprecated in librdkafka as well. There was erroneous behaviour while using errno stuff. For logging, as you already figured out, you can use `RdKafka\Conf::setLogCb` where you can pass a `callable`.
Question 2: I will check what is going wrong here, seems arguments are amiss.

**Comment by nick-zh** [comment]
@jiegege can you maybe give more input on how i can reproduce this with `setLogCb`, i tried it with:

PHP version:php:7.3.10-fpm-alpine3.10
librdkafka version: 1.2.0.255
php-rdkafka version: 4.0.0

Using the following:
```
$conf->setLogCb(function ($kafka, $level, $facility, $message) {
    echo $facility;
});
```
Seems to work fine. Can you also please state which `librdkafka` version you are using?
Please not, that anything below `librdkafka:0.11.x` is not supported anymore.

**Comment by Jukit-Barrett** [comment]
My librdkafka version:
````
$ apk info librdkafka
librdkafka-1.0.1-r1 description:
The Apache Kafka C/C++ library

librdkafka-1.0.1-r1 webpage:
https://github.com/edenhill/librdkafka

librdkafka-1.0.1-r1 installed size:
921600
````

**Comment by nick-zh** [comment]
@jiegege as a side note: you should probably avoid using a release candidate.
I think i found the problem, i opened a PR, can you maybe checkout the branch `fix-log-cb-argument` and build it locally to see if that solves your problem?
If you can't do that, let me know how i can reproduce the error on my side, so i can test it.

**Comment by nick-zh** [comment]
@jiegege nevermind i found the warning, the open PR gets rid of it.
You should be fine either way, `setLogCb` should work regardless.
Same goes for the other warnings, we deprecated some functions but, since we didn't delete them, some warnings will pop up.
Thanks for the hint though :heart:

**Comment by Jukit-Barrett** [comment]
Ok, I understand
You are right, although issued a warning, but can install correctly
I just want to be perfect

**Comment by nick-zh** [comment]
@jiegege that's a very good quality :wink: my PR will get rid of one warning, the others sadly will stay until we delete the deprecated functions.
