### ISSUE TITLE
How to build php_rdkafka extension on Windows

### ISSUE THREAD

**Issue by vchampion** [php-rdkafka/php-rdkafka#29]
I placed sources downloaded from pecl and changed config.w32 to 

```
ARG_ENABLE('rdkafka', 'enable rdkafka support', 'no');

if (PHP_RDKAFKA != 'no')
{
    EXTENSION('rdkafka', 'rdkafka.c');
}

```

Then I run configure --disable-all --enable-cli --enable-rdkafka all is good, but then I try nmake in console appears message that it's needed librdkafka/rdkafka.h, when I downloaded it and placed in the folder with php-rdkafka extension in console appers error that reached 100 count of errors compilation stopped.. (fatal error c1003)

How I can build it together? I found that in librdkafka exists Visual Studio project.. Should I use it somehow?

**Comment by arnaud-lb** [comment]
@vchampion, did you succeed at building the extension on Windows ?

**Comment by arnaud-lb** [comment]
Fixed by https://github.com/arnaud-lb/php-rdkafka/pull/76, builds are available at http://windows.php.net/downloads/pecl/snaps/rdkafka/2.0.0/

**Comment by ericnilo** [comment]
I've put it in my php folder but I cannot see it in my phpinfo,

Is the build compatible for php 5?

**Comment by Rkm11** [comment]
@arnaud-lb 
http://windows.php.net/downloads/pecl/snaps/rdkafka/2.0.0/ link is not available tried almost all dll files but not yet succeed its always saying  
Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_rdkaf
ka.dll' - %1 is not a valid Win32 application.
