### ISSUE TITLE
thousands of logs in broker but calls "consume" returns RD_KAFKA_RESP_ERR__PARTITION_EOF

### ISSUE THREAD

**Issue by dengxianjie** [php-rdkafka/php-rdkafka#299]
* PHP version:PHP 7.1.9
 * librdkafka version:
 * php-rdkafka version:3.0.6-dev
 * kafka version:

Sir,
    I use High-level consumer and my code likes below, omit the process of instancing object.

```
<?php
while(true){
    for($i=0;$i<100;$i++){
        $msg = $KafkaConsumer->consume(10000);
        $json = json_encode($msg);
        file_put_contents('/log.txt', "{$i} , {$json}\n" , FILE_APPEND);
    }
    sleep(1);
}
```

In my log.txt, after consume several minutes, I found that regular consume results and RD_KAFKA_RESP_ERR__PARTITION_EOF results appears alternately and continuously . I sure that there is still thousands of messages in Kafka brokers because I was watching the Kafka-Manager monitor and lots of Lag exists obviously. 

Why this phenomenon would happen? Is this a bug or could I solve it?

**Comment by nick-zh** [comment]
Good morning @dengxianjie 

There are multiple things that could cause, this, but might first assumption would
be, that in the conf you used to instantiate your consumer, you didn't set:
```
$conf->set('auto.offset.reset', 'earliest');
``` 
The default for this setting is `latest`, which means you only read new messages.
Let me know if that helps.

Cheers,
Nick

**Comment by dengxianjie** [comment]
> Good morning @dengxianjie
> 
> There are multiple things that could cause, this, but might first assumption would
> be, that in the conf you used to instantiate your consumer, you didn't set:
> 
> ```
> $conf->set('auto.offset.reset', 'earliest');
> ```
> 
> The default for this setting is `latest`, which means you only read new messages.
> Let me know if that helps.
> 
> Cheers,
> Nick

Thanks for your reply :)
I have set that
`$topicConf->set('auto.offset.reset', 'largest');`
in my program.
And I found from documentation (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)
 that describe the "auto.offset.reset" means below, 

 _Action to take when there is no initial offset in offset store or the desired offset is out of range:
  'smallest','earliest' - automatically reset the offset to the smallest offset,
  'largest','latest' - automatically reset the offset to the largest offset_
       
So if I want to use High-level consumer , and I want to begin consuming the latest message whenever I startup my consumer daemon, does any way for me to choose the "auto.offset.reset" parameter?
Obviously 'earliest' is not the best choice, because when I restart the consumer daemon and it will pull lots of message that has been computed before.

**Comment by nick-zh** [comment]
heya @dengxianjie 
Well it depends on your usecase, basically `auto.offset.reset` applies when you have no offset stored, so the very first time you start your consumer.
If you care about previous messages, choose `earliest`. If you only care about new messages, choose `latest`.
But again, this setting is only used for the very first time you connect. After that, your consumer will always continue from the last offset you did commit.
I hope this helps to clear things up :smile_cat: 
**Edit:** Please also note, that `setDefaultTopicConf` is deprecated and that you can set this on the `RdKafka::Conf` directly.

**Comment by dengxianjie** [comment]
Oh sorry ,I confused about the `auto.offset.reset` meaning and I am very grateful to you for helping me clear things up. But it seems not helping for solving the problem. Excuse me and I would like to show the detail logs which based on my code in the very beginning comment. 

I have logged the loop number and time, and obviously offset in return is continuously but RD_KAFKA_RESP_ERR__PARTITION_EOF occurred abnormally (**I sure that there is thousands of Lag at that moment**).

```
for 0 20:41:11 
{"err":0,"topic_name":"topic_abc","timestamp":1570884002291,"partition":1,"payload":"message_abc","len":540,"key":null,"offset":2631640}
for 1 20:41:11 
{"err":-191,"topic_name":"topic_abc","timestamp":-1,"partition":1,"payload":"Broker: No more messages","len":24,"key":null,"offset":2631641}
for 0 20:41:12
{"err":0,"topic_name":"topic_abc","timestamp":1570884002786,"partition":1,"payload":"message_abc","len":567,"key":null,"offset":2631641}
for 1 20:41:12 
{"err":-191,"topic_name":"topic_abc","timestamp":-1,"partition":1,"payload":"Broker: No more messages","len":24,"key":null,"offset":2631642}
for 0 20:41:13 
{"err":0,"topic_name":"topic_abc","timestamp":1570884003874,"partition":1,"payload":"message_abc","len":528,"key":null,"offset":2631642}
for 1 20:41:13 
{"err":0,"topic_name":"topic_abc","timestamp":1570884004051,"partition":1,"payload":"message_abc","len":528,"key":null,"offset":2631643}
for 2 20:41:13 
{"err":-191,"topic_name":"topic_abc","timestamp":-1,"partition":1,"payload":"Broker: No more messages","len":24,"key":null,"offset":2631644}
```

Am I describe my situation clearly? Are there anybody has met it bofore? Thank you for replying again sincerely :)

**Comment by nick-zh** [comment]
@dengxianjie no worries man, we are here to help. It is a bit hard for me to help regarding this, but i will try my best. So it could be, that with your tests before, you maybe read one message, the problem then is, that you might have already committed an offset.
To be sure, to read every message from beginning, change your consumer group to something new, since your current group might have already committed stuff.
```
$conf->set('auto.offset.reset', 'earliest');
$conf->('group.id', 'your-new-consumer-group');
```
Then you should surely get all the messages in your topic.
If not, i would assume, that maybe you have a low retention time on your topic and messages got deleted in the meantime. Offset `2631642` does not necessarily mean, that 2.5 million messages are available. Let me know how it works out.

**Comment by dengxianjie** [comment]
ok, I will try the 'earliest' way firstly . Further more i will try manually handle the offset instead.

**Comment by nick-zh** [comment]
@dengxianjie how is it going? Do you need further assistance with this?
