### ISSUE TITLE
Is flush() and purge() only Producer thing?

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#302]
I don't get `flush()` in https://github.com/arnaud-lb/php-rdkafka/pull/264/files

Is it only for producer? It's exposed in RdKafka class, I'd expect it in Producer only 🤔 Same for `purge()`

Thanks!

**Comment by nick-zh** [comment]
@simPod you are correct, it is for producer only. As stated in the doc, when called from a consumer, `RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED` will be returned. This is the same behaviour that `librdkafka` has.
Cheers,
Nick
