### ISSUE TITLE
err_code: -195, err_msg: Local: Broker transport failure

### ISSUE THREAD

**Issue by luowencai** [php-rdkafka/php-rdkafka#304]
* PHP version:7.2.19
 * librdkafka version:1.1.0.255
 * php-rdkafka version:3.1.2
 * kafka version:2.3
we refer to hight level example`s code and occurs the following error
```
INFO - err_code: -195, err_msg: Local: Broker transport failure
RdKafka\Exception: Local: Broker transport failure
```
hight level example  treat RD_KAFKA_RESP_ERR__TRANSPORT=-195 as exception and kafka log did not find any error or warn.
should we treat  itg as normal info? it seems this error will automaticly resume

**Comment by Steveb-p** [comment]
@luowencai I'm fairly certain your RdKafka instance (client) is unable to communicate with Kafka broker. Are you actually producing or consuming any messages?

What do you mean by high-level example? High-level consumer does not handle this return code: https://arnaud.le-blanc.net/php-rdkafka/phpdoc/rdkafka.examples-high-level-consumer.html

**Comment by luowencai** [comment]
yes，in our application， this error happen a day or two，it seems it was network instable or other, and after our process restart because of exception，it will resume.
i have find this issue，https://github.com/edenhill/librdkafka/issues/64 ，and it show`s we colud tignore this error  RD_KAFKA_RESP_ERR__TRANSPORT. 
i wolud like to ask your suggestion if it`s necessary...

**Comment by luowencai** [comment]
yes，in our application， this error happen a day or two，it seems it was network instable or other, and after our process restart because of exception，it will resume.
i have find this issue，edenhill/librdkafka#64 ，and it shows we could ignore this error RD_KAFKA_RESP_ERR__TRANSPORT. i wolud like to ask your suggestion if its necessary...

**Comment by luowencai** [comment]
when this error happen too many times like 5 or 10，we will restart the app，other wise ignore it，continue to watch it
