### ISSUE TITLE
consumer->close() not equal consumer->__destroy()?

### ISSUE THREAD

**Issue by jeferwang** [php-rdkafka/php-rdkafka#312]
`KafkaConsumer->close()` method cannot close kafka tcp connect but `unset($soncumer)` can do it

my php  is run as a daemon process ，when I use `consumer->close()` method，the tcp connect is established status; but use unset($consumer) ,the tcp connect will be close.

sorry for my bad english~

**Comment by nick-zh** [comment]
It can take some time, but it should actually close the connection.
Please provide everything from the issue template, otherwise it is hard to help this.
 * PHP version:
 * librdkafka version:
 * php-rdkafka version:
 * kafka version:

Also please let me know how i can reproduce this.

**Comment by nick-zh** [comment]
Ok sry, so i had a quick, so i think you might be right, until the object is destroyed, rdkafka may hold some stuff, close only ensures that the consumer has commited everything and left the consumer group. The object itself will only be released on destruct, hope that helps.
