### ISSUE TITLE
dll files for php 7.3 on windows

### ISSUE THREAD

**Issue by eailyass** [php-rdkafka/php-rdkafka#313]
* PHP version: 7.3
 * librdkafka version: any
 * php-rdkafka version: any 
 * kafka version: any
OS: windows x64

is it any valid rdkafka extension for php 7.3 on windows?
I tried different combination of the link below:
https://windows.php.net/downloads/pecl/snaps/rdkafka/4.0.0/
but none of them seems to work I always get my php-cli broken.

**Comment by nick-zh** [comment]
With the next release, there should a working version for PHP7.3 on pecl, there was work being done to fix this (#162), i can't say atm when the next release will be though

**Comment by nick-zh** [comment]
@eailyass can you maybe elaborate what is breaking for the ones you tried from the provided link?
They have a segfault problem during shutdown, which has been fixed, but not released yet.

**Comment by eailyass** [comment]
Not sure if it's gonna help but by only typing php -v I get this:

![41CDFB35](https://user-images.githubusercontent.com/10117393/68946950-81b74200-07b4-11ea-8c52-f16021946448.PNG)

**Comment by nick-zh** [comment]
@eailyass yeah i see, not really usable then, i will check regarding upcoming releases and get back to you

**Comment by eailyass** [comment]
Thank you

**Comment by nick-zh** [comment]
i am going to close this duplicate, please check #162 for updates. It seems with the releases today, we got dlls for `php-rdkafka:3.1.3` for php 7.2,7.3 and 7.4. I am following up in #162 about `php-rdkafka:4.0.1`
