### ISSUE TITLE
Conceptual question using the extension

### ISSUE THREAD

**Issue by istvano** [php-rdkafka/php-rdkafka#32]
Hi Guys,

I am very sorry if my question seems irrelevant, but I though I would ask the question here first as perhaps you have experience with this or it might be useful for other users too.

I would like to send log data to a Kafka cluster from PHP although I have a question on a potential problem.

1, if I have events generated on the server running PHP regularly. so What happens if the box goes offline ( no internet or can not reach Kafka) but it generates tons of events which will be sent to librdkafka.
- Does it have a buffer to hold messages until the connection to the Kafka cluster is back online ?
- Is this buffer in memory only. Does the buffer have any fail-over?

Do I need to come up with  a persistence solution in case for such failover scenario to make sure that my events will be sent **at least once** ?

Thanks for any suggestions!

**Comment by arnaud-lb** [comment]
Hi @istvano,

The `queue.buffering.max.messages` configuration defines the number of messages waiting to be sent. `RdKafka\Topic::produce()` throws a `RdKafka\Exception` whose code is `RD_KAFKA_RESP_ERR__QUEUE_FULL` if the buffer is full. By default the buffer can hold up to 100000 messages.

This is memory only, and there is no fail over - if the process crashes before sending the messages, the messages are lost.

**Comment by istvano** [comment]
Hi,

Thanks a lot for taking the time. It is good news. so I guess the best way for me to actually have a local redis queue and push messages from there to kafka to be safe.

Thanks again!
