### ISSUE TITLE
Dropping PHP EOL versions with next major, prepare for PHP8

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#328]
With `php:8.0` approaching next year, i think it would make sense to deprecate all
php versions that have reached EOL.
The versions that are or will be EOL when 8.0 comes out are:
- `php:5.6` (EOL since 12/2018)
- `php:7.0` (EOL since 12/2018)
- `php:7.1` (EOL since 12/2019)
- `php:7.2` (EOL with `php:8.0`)

I think this would help clean the code up and also reduce CI time.
It would probably make sense, to start a branch for this later next year,
to clean stuff up and make it `php:8.0` compatible.
We probably should also drop support for anything before `librdkafka:1.2.0` by then.
What are your thoughts @arnaud-lb ?

**Comment by nick-zh** [comment]
PHP8.0 is planned for December this year.

So my suggestion for `php-rdkafka:5.0`, which will support it, is:
- support only `php:7.3` or greater
- support only `librdkafka:1.4` or greater

I am open to support `librdkafka:1.3.x` but in December it will be already one year old and librdkafka is evolving quickly.
Please everybody, share your thoughts on this.

**Comment by nick-zh** [comment]
With the last feature (producer transactions) being ready, i will move forward with working on this in the coming days and weeks.
@arnaud-lb please let me know if you have any additional input to my above comment :v:

**Comment by nick-zh** [comment]
Just wanted to drop a short update, the current open PR should work fine with the current PHP8 beta.  Release of this will take some time though, since i want to get some other things into the next major as well :v: and we also need to release `php-rdkafka:4.1` first

**Comment by nick-zh** [comment]
The open PR should be working fine with the current PHP8rc. I will do some heavy testing on the weekend

**Comment by Jeroeny** [comment]
What's the current status of the PR?

**Comment by nick-zh** [comment]
Ready for review :smile:

**Comment by nick-zh** [comment]
My PR was split into smaller PRs:  #401, #403, #405, and #406 and merged

**Comment by andypost** [comment]
Are you going to create 5.1 branch?

**Comment by nick-zh** [comment]
@arnaud-lb has yet to release `php-rdkafka:5.0`, normally we kept the latest major on master until now.

**Comment by nick-zh** [comment]
The release is finally here, enjoy :tada:
