### ISSUE TITLE
Throw \InvalidArgumentException "Out of range" for partition in ConsumerTopic::offsetStore()?

### ISSUE THREAD

**Issue by dirx** [php-rdkafka/php-rdkafka#329]
Why not checking for correct partition range first (and throwing \InvalidArgumentException if out of range) before calling librdkafka like in other methods (::produce, etc.)?

**Comment by nick-zh** [comment]
fair point, thx @dirx i added a pr for this

**Comment by dirx** [comment]
@nick-zh Thank you.
