### ISSUE TITLE
Fatal error on KafkaConsumerTopic deconstruction

### ISSUE THREAD

**Issue by dirx** [php-rdkafka/php-rdkafka#330]
Stumbled over `Fatal error: Uncaught Exception: RdKafka\Kafka::__construct() has not been called in [no active file] on line 0` after php script ended.

Seems like strange behavior in KafkaConsumerTopic deconstruction. Works for ConsumerTopic & ProducerTopic.

You may re-try with (additionally unsetting $topic explicitly):

```php
<?php

declare(strict_types=1);

use RdKafka\Conf;
use RdKafka\KafkaConsumer;

$conf = new Conf();
$conf->set('group.id','test');
$consumer = new KafkaConsumer($conf);
$topic = $consumer->newTopic('test');
//sleep(2);
//unset($topic);
```

 * PHP version: 7.4.1
 * librdkafka version: 1.3.0
 * php-rdkafka version: 4.0.3-dev & 3.1.3
 * kafka version:

Same on:

 * PHP version: 7.3.13
 * librdkafka version: 1.3.0
 * php-rdkafka version: 3.1.3
 * kafka version:

**Comment by nick-zh** [comment]
@dirx another good find, thx :+1: 
i am almost certain we actually shouldn't use this, because with the high level consumer you don't need to care about the topic object :smile:

**Comment by nick-zh** [comment]
Correction, we need it for metadata, I'll have another look today

**Comment by dirx** [comment]
@nick-zh My ffi based librdkafka binding tests did run successfully against latest rdkafka extension 4.0.4-dev on this issue (see https://travis-ci.org/dirx/php-ffi-librdkafka/jobs/649612863#L1472).

Thank you for fixing this.
