### ISSUE TITLE
RdKafka\KafkaConsumer::consume timeout parameter should be of int type

### ISSUE THREAD

**Issue by nicofff** [php-rdkafka/php-rdkafka#337]
The signature according to the [docs](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-kafkaconsumer.consume.html) is 
`public RdKafka\KafkaConsumer::consume ( string $timeout_ms ) : RdKafka\Message`

The parameter description then says it's an int, which is consistent with the librdkafka [docs](https://docs.confluent.io/2.0.0/clients/librdkafka/classRdKafka_1_1Consumer.html#a0afd32e342283fc10fa6f32cc25950b7)

**Comment by nick-zh** [comment]
@nicofff thank you very much! I opened a PR for the doc to fix this.
