### ISSUE TITLE
I keep getting RD_KAFKA_RESP_ERR__TIMED_OUT

### ISSUE THREAD

**Issue by daemyn** [php-rdkafka/php-rdkafka#342]
* PHP version: 7.0.3
 * librdkafka version: 1.3.0
 * php-rdkafka version: latest
 * kafka version: 2.11-2.1.1

I keep getting error code -185 (RD_KAFKA_RESP_ERR__TIMED_OUT) after I use `$producer->flush(100)`
The library should be working fine since `$producer->newTopic("test");` is adding the topic to kafka topics list.
For more context, i'm compiling rdkafka library and using php-rdkafka inside a docker container.
It also might be a misunderstanding of the usage of the library or a wrong version selection.
Sorry if this is not the appropriate place to ask this question but i tried everything i can with no result.

Thank you in advance

EDIT:
Changed the error constant

**Comment by nick-zh** [comment]
Dear @daemyn 
No worries, we are here to help, this might be a bit misleading, but
`RD_KAFKA_RESP_ERR_NO_ERROR` as the name suggests, means
everything went fine, you can find all possible return codes in the doc as well:
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.flush.html

Hope that helps!

Cheers,
Nick

**Comment by daemyn** [comment]
Thank you for the quick answer
Sorry, I meant RD_KAFKA_RESP_ERR__TIMED_OUT i already mentioned that the error code is -185
Again, the client is connected to kafka since the topic was created, but when i send a message i receive timeout error even when i use the same example in the docs

**Comment by nick-zh** [comment]
@daemyn apologies, may I ask how many messages you produced before you flush? How high is the timeout you set for flush?
If you can provide a piece of code with which I can reproduce this, that would be most helpful.

**Comment by nick-zh** [comment]
To be sure, you used the code example from here:
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.examples-producer.html
?

**Comment by daemyn** [comment]
I used the exact same code from the example and still get TIMED_OUT when i flush

**Comment by nick-zh** [comment]
Ok so i tried to reproduce this with:

os: alpine
php: 7.0.33
librdkafka: 1.3.0
rdkafka: 4.0.2

But everything seems to work properly with the example code. Maybe you could check, either with a consumer or an inspection tool, to check if the messages ended up in Kafka. To get more debug output, you can also set:
```
$conf->set('log_level', '7');
$conf->set('debug', 'all');
```

**Comment by nick-zh** [comment]
Only way i can reproduce this, if the broker is down, then i get:
```
int(-185)
int(-185)
int(-185)
int(-185)
int(-185)
%3|1580883712.100|FAIL|rdkafka#producer-1| [thrd:kafka:9096/bootstrap]: kafka:9096/bootstrap: Failed to resolve 'kafka:9096': Try again (after 5003ms in state CONNECT)
%3|1580883712.100|ERROR|rdkafka#producer-1| [thrd:kafka:9096/bootstrap]: kafka:9096/bootstrap: Failed to resolve 'kafka:9096': Try again (after 5003ms in state CONNECT)
%3|1580883712.101|ERROR|rdkafka#producer-1| [thrd:kafka:9096/bootstrap]: 1/1 brokers are down
int(-185)
int(-185)
int(-185)
int(-185)
int(-185)

Fatal error: Uncaught RuntimeException: Was unable to flush, messages might be lost! in /var/www/html/src/issue280.php:29
```
