### ISSUE TITLE
Produce newTopic() how expensive it is?

### ISSUE THREAD

**Issue by simPod** [php-rdkafka/php-rdkafka#344]
Hello, I have a question about `newTopic()` method. 

Is it safe if called in a loop? Or does it open a connection or something so it's encouraged to initiate only once before the loop?

The thing is I want to route messages to tens of topics so I'm wondering whether I have to initiate those topics before the loop or can do it within.

**Comment by nick-zh** [comment]
Hey @simPod 
I think this should be safe to do so, the connection will / should already be open at that time. To improve you can keep the topics in memory somehow to avoid always recreating it. Hope that helps.

**Comment by simPod** [comment]
Thank you for answer! That will do.
