### ISSUE TITLE
Minor documentation / implementation difference in TopicPartition::__construct

### ISSUE THREAD

**Issue by dirx** [php-rdkafka/php-rdkafka#345]
Documentation: offset = null, when not set explicitly:

`public RdKafka\TopicPartition::__construct ( string $topic , integer $partition [, integer $offset = NULL ] )`

(see https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-topicpartition.construct.html)

Implementation: sets default offset = 0:

https://github.com/arnaud-lb/php-rdkafka/blob/95780b9938b7e47ba9e22b3d43168e945298ca92/topic_partition.c#L206

 * PHP version: 7.4.2
 * librdkafka version: 1.0.0
 * php-rdkafka version: 4.0.4-dev
 * kafka version:

**Comment by nick-zh** [comment]
Thx @dirx as always, i will have a look

**Comment by nick-zh** [comment]
Finally got the time to fix this: https://github.com/arnaud-lb/php-rdkafka-doc/pull/43
Thx again for reporting this!
