### ISSUE TITLE
librdkafka version (runtime) => 1.1.0-26-gb4a3da-dirty

### ISSUE THREAD

**Issue by luowencai** [php-rdkafka/php-rdkafka#347]
* PHP version:7.2.19
 * librdkafka version:1.1.0.255
 * php-rdkafka version:3.1.2
 * kafka version:
rdkafka

rdkafka support => enabled
version => 3.1.2
build date => Jul 26 2019 10:58:46
librdkafka version (runtime) => 1.1.0-26-gb4a3da-dirty
librdkafka version (build) => 1.1.0.255
 
What does dirty mean, how can we make it right

**Comment by Steveb-p** [comment]
It basically means it's been built from specific source code, maybe with some changes added. Usually it's nothing to worry about, unless you don't trust your system admin or you encounter any issues.
