### ISSUE TITLE
Making repository tests faster

### ISSUE THREAD

**Issue by Steveb-p** [php-rdkafka/php-rdkafka#351]
I've fiddled with test times and apparently valgrind memory check takes 75% of the time.
When it was enabled it cost us 10 mins to execute tests
With it disabled tests lasted 2.5 mins
So I'd say we should only run memory checks in selected tests, and drop them for all others. I looked how redis extension library does it and they use a different tool for testing.

**Comment by nick-zh** [comment]
This is very good input @Steveb-p! As pointed out, [redis](https://github.com/phpredis/phpredis/blob/develop/.travis.yml) seems to run valgrind at the end.

Looking at this i could imagine the following approach. Split our tests in two folders, to run some without valgrind and some with. Right now our test.sh always runs with `-m` (valgrind).
Tests with valgrind should probably have this:
- normal produce (maybe with callbacks)
- produce with headers
- consume
I think with this we cover everything the ext does. I will try to consolidate our tests where possible and try this approach to see how much we gain. Even though we will drop some versions with #328 i still think this will benefit us greatly.

@arnaud-lb any thoughts on this?

**Comment by nick-zh** [comment]
With numerous improvements from @Steveb-p and @arnaud-lb time, for a single job run, was brought down from 5h to 1h.
This will only decrease with upcoming work on `php:8.x` support, where we will drop more PHP and librdkafka versions.
Thanks guys, will be closing this for now.
