### ISSUE TITLE
No such configuration property: "message.max.bytes" for Topic Conf

### ISSUE THREAD

**Issue by maks-rafalko** [php-rdkafka/php-rdkafka#353]
* PHP version: 7.4.2
 * librdkafka version: 1.2.1
 * php-rdkafka version: 4.0.3
 * kafka version: 2.2.0

This documentation page of `php-rdkafka` https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/class.rdkafka-topicconf.html says that **Topic** Conf can use properties from https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

We want to set a max message size for a particular topic, that's why we tried to do:

```php
$conf = new TopicConf();
$conf->set('message.max.bytes', '10000000');

$producer->newTopic('topicName', $topicConf);
```

but it doesn't work, producing the following error:

```
No such configuration property: "max.message.bytes"
```

Note, that there is a mess with this parameter being named differently in [`librdkafka`](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) documentation:

* `max.message.bytes`
* `message.max.bytes`

But both cases produce the same error.

However, this setting works when it's passed to Producer directly.

* Do we need to update the docs to **not** say all the parameters can be used for Topic Conf?
* How do you suggest to apply this setting only for particuler topic?

**Comment by nick-zh** [comment]
@maks-rafalko the code snippet below, should work. Be aware, that setting this alone will not work, your broker also needs to be configured to accept that message size.
Hope that helps!

```
$conf = new RdKafka\Conf();
$conf->set('message.max.bytes','10000000');
$producer = new Producer($conf);
```

**Comment by nick-zh** [comment]
i will adjust the link to have the correct anchor, which is:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties

**Comment by maks-rafalko** [comment]
As I said, it works on Producer level (as shown in your snippet), but it should also work for Topic Conf as per Kafka's documentation:

https://kafka.apache.org/documentation/

    [...] This can be set per topic with the topic level max.message.bytes config.

> i will adjust the link to have the correct anchor, which is:

nice!

**Comment by maks-rafalko** [comment]
is it that `librdkafka` just does not support it on Topic level?

**Comment by nick-zh** [comment]
@maks-rafalko so from the documentation `message.max.bytes` is the broker config. `max.message.bytes` is indeed a `TopicConf` option
**Edit** If i remember correctly, there was a discussion about adding this in `librdkafka` but i think in the end it was decided to not add this

**Comment by maks-rafalko** [comment]
> **Edit** If i remember correctly, there was a discussion about adding this in `librdkafka` but i think in the end it was decided to not add this

didn't find anything in the `librdkafka` repo. 

How do you suggest to apply this setting only for particular topic then?

Thank you for your answers. Since this is not supported in `librdkafka` (and consequently in `php-rdkafka`) - feel free to close the issue

**Comment by nick-zh** [comment]
@maks-rafalko sadly i think this is truly not possible on topic level only on producer level. Since you need to adjust the topic as well anyway, producing will still fail with `RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE` if i remember correctly, if you try sending something too big. Sry that i couldn't help more.
