### ISSUE TITLE
RdKafka\Conf OK in file but not in Laravel

### ISSUE THREAD

**Issue by bastienuh** [php-rdkafka/php-rdkafka#356]
Hi everyone,

Here is a strange behavior, and I dont understand why.
I'm using Laravel and, in one of my controller I have the following code :
```php
public function consumer()
{
    $conf = new \RdKafka\Conf();
    dd($conf->dump());
}
```

When I load the page, an exception is thrown :
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'RdKafka\Conf' not found
```

---

Now, I'm creating a file, named kafka.php with the following code : 
```php
<?php
    $conf = new \RdKafka\Conf();
    print_r($conf->dump());
```

When I `php kafka.php`, here is the result : 
```sh
Array
(
    [builtin.features] => gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer
    [client.id] => rdkafka
    [message.max.bytes] => 1000000
    [message.copy.max.bytes] => 65535
    [receive.message.max.bytes] => 100000000
    [max.in.flight.requests.per.connection] => 1000000
    [metadata.request.timeout.ms] => 60000
    [topic.metadata.refresh.interval.ms] => 300000
    [metadata.max.age.ms] => 900000
    [topic.metadata.refresh.fast.interval.ms] => 250
    (...)
    [queue.buffering.max.kbytes] => 1048576
    [queue.buffering.max.ms] => 0.5
    [message.send.max.retries] => 2
    [retry.backoff.ms] => 100
    [queue.buffering.backpressure.threshold] => 1
    [compression.codec] => none
    [batch.num.messages] => 10000
    [delivery.report.only.error] => false
)
```

---

I have already put the following line `extension=/usr/lib/php/20180731/rdkafka.so` in my two files :
* `/etc/php/7.3/cli/php.ini`
* `/etc/php/7.3/fpm/php.ini`

I have restarded `php7.3-fpm`, `apache2` and `nginx`.

So, do you know what's going on ? Why one is working and the other not ?

Thanks for you help :-)

---

**My configuration :**
 * PHP version: 7.3
 * librdkafka version: 1.4
 * php-rdkafka version: 4.0.3
 * kafka version: 2.4.0

**Comment by nick-zh** [comment]
@bastienu this sounds kind of strange, so i am assuming when you do `php-fpm -m` and `php -m` you can find the extension in both?

**Comment by nick-zh** [comment]
i noticed you also mention apache, so i am unsure if you use fpm or apache, but be sure for apache to also add it there (e.g. ` /etc/php/7.3/apache/php.ini`) and you can check with `var_dump(get_loaded_extensions());`

**Comment by bastienuh** [comment]
Oh god, many thanks @nick-zh ! I didn't add `extension=/usr/lib/php/20180731/rdkafka.so` in `/etc/php/7.3/apache/php.ini` !

Thanks a lot !

**Comment by nick-zh** [comment]
No worries, always glad to help :v:
