### ISSUE TITLE
Call to undefined method RdKafka\KafkaConsumer::newTopic()

### ISSUE THREAD

**Issue by breath-co2** [php-rdkafka/php-rdkafka#36]
php version is 5.6.16
rdkafka

```
rdkafka support => enabled
version => 0.9.1
build date => Mar  4 2016 17:43:12
librdkafka version => 0.9.1.0
```

code:

``` php
<?php
$conf = new RdKafka\Conf();
$conf->set('group.id', 'test');
$conf->set('metadata.broker.list', '127.0.0.1');
$consumer = new RdKafka\KafkaConsumer($conf);
$topic = $consumer->newTopic('test');
var_dump($topic);
```

**Comment by doubleycn** [comment]
$consumer is object ?
metadata.broker.list must like this, 127.0.0.1:port

**Comment by breath-co2** [comment]
it's not the problem.

I found the code not registered function newTopic in file kafka_consumer.c

``` c
PHP_ME(RdKafka__KafkaConsumer, newTopic, arginfo_kafka_kafka_consumer_new_topic, ZEND_ACC_PUBLIC)
```

in line 635 It is that: 

``` c
static const zend_function_entry fe[] = { /* {{{ */
    PHP_ME(RdKafka__KafkaConsumer, __construct, arginfo_kafka_kafka_consumer___construct, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, assign, arginfo_kafka_kafka_consumer_assign, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, getAssignment, arginfo_kafka_kafka_consumer_getAssignment, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, commit, arginfo_kafka_kafka_consumer_commit, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, commitAsync, arginfo_kafka_kafka_consumer_commit_async, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, consume, arginfo_kafka_kafka_consumer_consume, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, subscribe, arginfo_kafka_kafka_consumer_subscribe, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, getSubscription, arginfo_kafka_kafka_consumer_getSubscription, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, unsubscribe, arginfo_kafka_kafka_consumer_unsubscribe, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, getMetadata, arginfo_kafka_kafka_consumer_getMetadata, ZEND_ACC_PUBLIC)
    PHP_ME(RdKafka__KafkaConsumer, __destruct, arginfo_kafka_kafka_consumer___destruct, ZEND_ACC_PUBLIC | ZEND_ACC_FINAL)
    PHP_FE_END
}; /* }}} */
```

**Comment by doubleycn** [comment]
@breath-co2 high level interface use **subscribe** like this:
$this->rk = new \RdKafka\KafkaConsumer($this->conf);
$this->rk->subscribe([$topic]);

newTopic is simple insterface. the code at rdkafka.c

**Comment by breath-co2** [comment]
@doubleycn I need get object \RdKafka\KafkaConsumerTopic

[https://arnaud-lb.github.io/php-rdkafka/phpdoc/class.rdkafka-kafkaconsumertopic.html](https://arnaud-lb.github.io/php-rdkafka/phpdoc/class.rdkafka-kafkaconsumertopic.html)
The document page write that:

```
This class represents a topic when using the RdKafka\KafkaConsumer. It can not be instantiated directly, RdKafka\KafkaConsumer::newTopic() should be used instead.
```

**Comment by doubleycn** [comment]
@breath-co2 do you want to use RdKafka\KafkaConsumerTopic::offsetStore ? you can use this methed.
`
ZEND_BEGIN_ARG_INFO_EX(arginfo_kafka_kafka_consumer_commit, 0, 0, 0)
    ZEND_ARG_INFO(0, message_or_offsets)
ZEND_END_ARG_INFO()

PHP_METHOD(RdKafka__KafkaConsumer, commit)
{
    consumer_commit(0, INTERNAL_FUNCTION_PARAM_PASSTHRU);
}
`
example:
`
$conf = new RdKafka\Conf();
$conf->set("metadata.broker.list", "xxxx:8092");
$conf->set("group.id", "test-group");
//$conf->set("enable.auto.commit", "false");
//$conf->set("enable.auto.offset.store", "false");
//$conf->set("auto.offset.reset", 'smallest');

$consumer = new RdKafka\KafkaConsumer($conf);
$consumer->subscribe(["test"]);

while (true) {
    $message = $consumer->consume(100e2);
    switch ($message->err) {
        case RD_KAFKA_RESP_ERR_NO_ERROR:
            $consumer->commit($message);
            var_dump($message);
            break;
        case RD_KAFKA_RESP_ERR__PARTITION_EOF:
            break;
        default:
            var_dump($message->errstr());
    }
    break;
}

`
if not.I can't help you! wait author!

**Comment by breath-co2** [comment]
@doubleycn Yes, I see, thank you very much.
