### ISSUE TITLE
Executing consumer without loop

### ISSUE THREAD

**Issue by parveenbadoni** [php-rdkafka/php-rdkafka#365]
* PHP version:
 * librdkafka version:
 * php-rdkafka version:
 * kafka version:

**Comment by parveenbadoni** [comment]
Hi,

PHP version: 7.1
librdkafka version: 0.11.3
php-rdkafka version:4.0.3
kafka version:0.10.0

I want to use consumer without while loop. My consumer will run at a particular time interval, like at every minute. I will use cronjob for it. If i use consumer without while loop, it does not consume messages. With while loop, it is consuming messages. Is there a way to consume messages without while loop?

**Comment by parveenbadoni** [comment]
@nick-zh Can you please advice on this issue?

**Comment by Steveb-p** [comment]
@parveenbadoni may you please explain your reasoning as to **why** you're not willing to use while loop?

And don't get me wrong, if there is a reason for it, you can use a while loop that you `break` out of under some condition, like reaching a particular time elapsed. 

While loop is primarily used to read another message and / or wait for new messages to arrive (if there are none). You can do it any other way you like, normal PHP syntax rules apply.

Using a long-running process over cronjob is prefered to allow that process to pick up immediately once the message arrives. For cronjob, worst case scenario you will be waiting 59 seconds until message starts processing. To keep the process running `supervisord` or similar tools can be used to monitor process state and restart it when it stops.

**Comment by nick-zh** [comment]
Hey @parveenbadoni 
Can you maybe elaborate why you can't use a while loop?
But maybe [consumeBatch](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-consumertopic.consumebatch.html) could help you?

Cheers

**Edit:** i agree with @Steveb-p when possible, always use a running process, since Kafka is all about streaming data in real time. On an unreleated note, `librdkafka:0.11.3` is quite old and you might want to update :v:

**Comment by parveenbadoni** [comment]
Thanks for reply @Steveb-p @nick-zh 
I will try to explain my use-case. I have a scheduler that will be executing every 15 minutes or so. There is a separate producer who will be pushing messages to kafka topic. My consumer will run in that scheduler and will consume messages sent within last 15 minutes. Frequency of producer publishing messages is not known yet. So, i dont want my consumer to keep on running. instead, i would like it to run at some time interval and consume messages. 

```
$starttime = time();

while (true) {
    if(time() - $starttime > 10) {
        break;
    }
    $message = $consumer->consume(120*10000);
    switch ($message->err) {
        case RD_KAFKA_RESP_ERR_NO_ERROR:
            $messages[] = $message;
            break;
        case RD_KAFKA_RESP_ERR__PARTITION_EOF:
            echo "No more messages; will wait for more\n";
            break;
        case RD_KAFKA_RESP_ERR__TIMED_OUT:
            echo "Timed out\n";
            break;
        default:
            throw new \Exception($message->errstr(), $message->err);
            break;
    }
}
print_r($messages);
```

This is what i tried to stop consumer after 10 seconds, but consumer did not stop.

**Comment by parveenbadoni** [comment]
@nick-zh I guess consumeBatch will also be used inside while loop, Right?

**Comment by nick-zh** [comment]
@parveenbadoni you can use `consumeBatch` outside a loop, you will just get the amount you specified, so if you use `consumeBatch` with a `batchSize` 100 messages you will get max. 100 messages, so if there are only 50 new messages, you will only get 50. Also the problem with your example code is, that you have a consume timeout of 20m, so if there is no new message for 20m your consumer will hang for 20m.

**Comment by parveenbadoni** [comment]
@nick-zh For consumeBatch method, I will also have to provide partition number? What if I do not know partition number.

**Comment by nick-zh** [comment]
@parveenbadoni `consumeBatch` is part of the low level consumer, for which you must know your partitions, so you would need to do this for every existing partition.
My advice is to have a constant process running.
If not possible / desired, you can use your approach for which i would advise your `consumeTimeout` should be lower than your `maxRuntime` (in your example 10s).
Hope this helps.

**Comment by parveenbadoni** [comment]
@nick-zh Thanks for the suggestion. It worked.
