### ISSUE TITLE
auto.commit.enable or enable.auto.commit?

### ISSUE THREAD

**Issue by autowp** [php-rdkafka/php-rdkafka#373]
Documentation says

```
If you need control and want to commit manually, then you want to set auto.commit.enable to 'false'
```

But [here](https://docs.confluent.io/current/clients/librdkafka/md_CONFIGURATION.html) that option named `enable.auto.commit` .

In my environment only `enable.auto.commit` works with high-level consumer

 * PHP version: 7.3.11-0ubuntu0.19.10.6
 * librdkafka version: v0.11.6
 * php-rdkafka version: 4.0.3

**Comment by nick-zh** [comment]
legacy consumer: `auto.commit.enable`
high level consumer: `enable.auto.commit`

hope that helps :v:

**Comment by nick-zh** [comment]
I additionally updated the doc, to better reflect his:
https://github.com/arnaud-lb/php-rdkafka/tree/improve-doc-consumer-settings#consumer-settings

Please let me know if the doc is clearer with this :v:
