### ISSUE TITLE
connection down brokers. t try catch connection fail message. but can`t work

### ISSUE THREAD

**Issue by seth-shi** [php-rdkafka/php-rdkafka#379]
PHP version: 7.1.9
librdkafka version: 0.9.1
php-rdkafka version: 3.1.2
kafka version: 2.5.0
my php code

```
$kafkaBrokers = 'debian-server:9092';
$kafkaTopic = 'test';

$producer = new \RdKafka\Producer();
$producer->addBrokers($kafkaBrokers);
        
$topicConfig = new \RdKafka\TopicConf();
$topic = $producer->newTopic($kafkaTopic, $topicConfig);

// here block my web api, 
// i try catch exception, but can`t work
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'i am message');
```

i get error message
```
%3|1596426822.744|FAIL|rdkafka#producer-1| debian-server:9092/bootstrap: Failed to resolve 'debian-server:9092': %3|1596426822.
756|ERROR|rdkafka#producer-1| debian-server:9092/bootstrap: Failed to resolve 'debian-server:9092': %3|1596426822.767|ERROR|rdk
afka#producer-1| 1/1 brokers are down
```

I want to be able to return a response to the API after the connection fails

**Comment by nick-zh** [comment]
Use `logCb`:
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-conf.setlogcb.html
and anything with fatal level, you can react accordingly.
Or alternatively flush would return a timeout in this case too if you are doing this directly in your api and you can react on this.

**Comment by seth-shi** [comment]
@nick-zh Can an exception be thrown in the callback to interrupt the connection and return the response, because I see this is an event callback and the code is not synchronized

**Comment by Steveb-p** [comment]
Also, I'd highly suggest upgrading your librdkafka dependency. 0.9 as far as I know is no longer supported by phprdkafka and versions before 0.11.6 are known to have issues.

**Comment by nick-zh** [comment]
@seth-shi if you are sending from the API directly, i would just call `flush` at the end with a reasonable timeout as parameter and react to the return code of `flush`
the alternative would be throwing and catching an exception from the callback and polling for all events, but it's more work and flush does pretty much the same :smile:

**Comment by seth-shi** [comment]
```
$kafkaBrokers = 'debian-server:9092';
$kafkaTopic = 'test';

$producer = new \RdKafka\Producer();
$producer->addBrokers($kafkaBrokers);
        
$topicConfig = new \RdKafka\TopicConf();
$topic = $producer->newTopic($kafkaTopic, $topicConfig);

// here block my web api, 
// i try catch exception, but can`t work
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'i am message');

while ($producer->getOutQLen() > 0) {
        
 
      $producer->poll(10);
 }
```

I mean, code is not blocking at `flush`. in`$topic::product` method block

**Comment by nick-zh** [comment]
so you can replace this:
```
while ($producer->getOutQLen() > 0) {
        
 
      $producer->poll(10);
 }
```
with this:
```
$result = $producer->flush(5000);
if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    // throw exception or return appropriate api response, whatever suits your usecase
}
```

**Comment by nick-zh** [comment]
Yeah and i forgot, also absolutely do what @Steveb-p said, upgrade librdkafka to a more current version :v:

**Comment by seth-shi** [comment]
no, code no run to `flush`.
code block to `produce`
block time out, my api request always timeout.

**Comment by nick-zh** [comment]
Yeah probably because the default message timeout for produce is 5s:
```
request.timeout.ms: 5000
```
and with flush also taking max. 5s (if broker is down), that is a total of 10s which is probably letting your request time out.
So you should probably not let your request time out and probably also  adjust the timeout.
To be clear though, during these 5s, librdkafka is retrying to send your message. In most cases where Kafka is setup properly, it will not take that long even if a broker goes offline. In a proper cluster setup this will have no to minimal impact.

**Comment by seth-shi** [comment]
i try run code in the cli. 
get notice
Even after 10s, the program cannot be stopped
```
%3|1596436852.140|FAIL|rdkafka#producer-1| debian-server:9092/bootstrap: Failed to resolve 'debian-server:9092': %3|1596436852.
144|ERROR|rdkafka#producer-1| debian-server:9092/bootstrap: Failed to resolve 'debian-server:9092': %3|1596436852.148|ERROR|rdk
afka#producer-1| 1/1 brokers are down
```

**Comment by nick-zh** [comment]
So just to be clear, you are running this code:
```
$kafkaBrokers = 'debian-server:9092';
$kafkaTopic = 'test';

$producer = new \RdKafka\Producer();
$producer->addBrokers($kafkaBrokers);
        
$topicConfig = new \RdKafka\TopicConf();
$topic = $producer->newTopic($kafkaTopic, $topicConfig);

// here block my web api, 
// i try catch exception, but can`t work
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'i am message');

$result = $producer->flush(5000);
if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    // throw exception or return appropriate api response, whatever suits your usecase
}
```
Also i noticed you run `php-rdkafka:3.1.2` which doesn't have flush yet.
I suggest you upgrade to the following versions:
- rdkafka:4.0.3
- librdkafka:1.5

**Comment by seth-shi** [comment]
```
// 1
$kafkaBrokers = 'debian-server:9092';
$kafkaTopic = 'test';

 // 2
$producer = new \RdKafka\Producer();
$producer->addBrokers($kafkaBrokers);
       
// 3 
$topicConfig = new \RdKafka\TopicConf();
$topic = $producer->newTopic($kafkaTopic, $topicConfig);

// 4
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'i am message');

// 5
$result = $producer->flush(5000);
if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    // throw exception or return appropriate api response, whatever suits your usecase
}
```

The code timeout is blocked at 4 and cannot reach 5

**Comment by nick-zh** [comment]
I cannot reproduce this with:
- `php:7.1.33`
- `rdkafka:4.0.3`
- `librdkafka:1.5.0`

With the following code you provided:
```
// 1
$kafkaBrokers = 'kafka:9097';
$kafkaTopic = 'test';

// 2
$producer = new \RdKafka\Producer();
$producer->addBrokers($kafkaBrokers);

// 3
$topicConfig = new \RdKafka\TopicConf();
$topic = $producer->newTopic($kafkaTopic, $topicConfig);

// 4
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'i am message');

// 5
$result = $producer->flush(5000);
if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    // throw exception or return appropriate api response, whatever suits your usecase
}
```
I get the following output and the script exits successfully from cli:
```
%5|1596439067.083|CONFWARN|rdkafka#producer-1| [thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
bash-5.0# php issue.php 
%5|1596439092.178|CONFWARN|rdkafka#producer-1| [thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
%3|1596439092.182|FAIL|rdkafka#producer-1| [thrd:kafka:9097/bootstrap]: kafka:9097/bootstrap: Connect to ipv4#172.20.0.4:9097 failed: Connection refused (after 2ms in state CONNECT)
%3|1596439092.182|ERROR|rdkafka#producer-1| [thrd:app]: rdkafka#producer-1: kafka:9097/bootstrap: Connect to ipv4#172.20.0.4:9097 failed: Connection refused (after 2ms in state CONNECT)
%3|1596439092.183|ERROR|rdkafka#producer-1| [thrd:kafka:9097/bootstrap]: 1/1 brokers are down
%3|1596439093.178|FAIL|rdkafka#producer-1| [thrd:kafka:9097/bootstrap]: kafka:9097/bootstrap: Connect to ipv4#172.20.0.4:9097 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
%3|1596439093.179|ERROR|rdkafka#producer-1| [thrd:app]: rdkafka#producer-1: kafka:9097/bootstrap: Connect to ipv4#172.20.0.4:9097 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
```

**Comment by nick-zh** [comment]
I can only reproduce this if i revert `flush` back to:
```
while ($producer->getOutQLen() > 0)
{
    $producer->poll(100);
    echo 'stuck in poll';
}
```
This will run forever when your broker is down, since it cannot send the message, this is why i advised to upgrade to `php-rdkafka:4.x` and use flush :v:

**Comment by seth-shi** [comment]
> I can only reproduce this if i revert `flush` back to:
> 
> ```
> while ($producer->getOutQLen() > 0)
> {
>     $producer->poll(100);
>     echo 'stuck in poll';
> }
> ```
> 
> This will run forever when your broker is down, since it cannot send the message, this is why i advised to upgrade to `php-rdkafka:4.x` and use flush ✌️

thanks,
