### ISSUE TITLE
configure: error: Please reinstall the rdkafka distribution

### ISSUE THREAD

**Issue by iyaozhen** [php-rdkafka/php-rdkafka#38]
First, Thx @arnaud-lb create this extension. But I have problem to build it.

```
$ ./configure --with-php-config=/home/work/local/app/php7/bin/php-config 

checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /home/work/local/app/php7
checking for PHP includes... ...
checking for PHP extension directory... ...
checking for PHP installed headers prefix... /home/work/local/app/php7/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking for rdkafka support... yes, shared
checking for librdkafka/rdkafka.h" in default path... not found
configure: error: Please reinstall the rdkafka distribution
```

```
$ php7 -v

PHP 7.0.4 (cli) (built: Mar 11 2016 17:01:16) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

My system is `CentOS release 6.3 (Final)`.

I down php-rdkafka-php7.zip from git clone and `https://github.com/arnaud-lb/php-rdkafka/archive/0.9.1-php7.zip`, But both build failure.

Someone who help me? Thx.

**Comment by iyaozhen** [comment]
Oh no, I am sorry, my mistake. I have not build [librdkafka](https://github.com/edenhill/librdkafka).

Now, I get rdkafka ext success.

**Comment by bingtanghulu** [comment]
because you need another package [librdkafka](https://github.com/edenhill/librdkafka),you should install [librdkafka](https://github.com/edenhill/librdkafka) first

- $ git clone https://github.com/edenhill/librdkafka.git
- $ cd librdkafka
- $ ./configure
- $ make && make install

this way can resolve your problem

**Comment by denisrocks** [comment]
Just install Kafka client under [official repository ](https://github.com/edenhill/librdkafka)instructions.

**Comment by Acing-Boy** [comment]
> because you need another package [librdkafka](https://github.com/edenhill/librdkafka),you should install [librdkafka](https://github.com/edenhill/librdkafka) first
> 
> * $ git clone https://github.com/edenhill/librdkafka.git
> * $ cd librdkafka
> * $ ./configure
> * $ make && make install
> 
> this way can resolve your problem

i have problem, i got this error.
<img width="912" alt="Screen Shot 2022-01-06 at 12 52 56" src="https://user-images.githubusercontent.com/16059037/148335486-ac30e7d3-4a6e-4a6e-a0c7-43a46282d09e.png">

**Comment by adriangronau** [comment]
I had the same issue. Using a specific, stable version fixed the problem.   
E.g. `git clone --branch v1.8.2 https://github.com/edenhill/librdkafka.git`

**Comment by Akshaykore95** [comment]
> > because you need another package [librdkafka](https://github.com/edenhill/librdkafka),you should install [librdkafka](https://github.com/edenhill/librdkafka) first
> > 
> > * $ git clone https://github.com/edenhill/librdkafka.git
> > * $ cd librdkafka
> > * $ ./configure
> > * $ make && make install
> > 
> > this way can resolve your problem
> 
> i have problem, i got this error. <img alt="Screen Shot 2022-01-06 at 12 52 56" width="912" src="https://user-images.githubusercontent.com/16059037/148335486-ac30e7d3-4a6e-4a6e-a0c7-43a46282d09e.png">

how to resolve this ?
