### ISSUE TITLE
how to retry the message?

### ISSUE THREAD

**Issue by askie** [php-rdkafka/php-rdkafka#380]
* PHP version: 7.1
 * librdkafka version: 1.5.0.1
 * php-rdkafka version:4.0.3
 * kafka version:2.4

if set
```
$conf->set('enable.auto.commit', 'false');
```
but not run 
```
 $consumer->commit($message);
```

is that possible other consumer or self to re consume this message?

**Comment by Steveb-p** [comment]
@askie yes, disabling automatic commit and not commiting manually pretty much results in **other consumer group members** to be able to consume the same message again **once this consumer disconnects**.

**Comment by nick-zh** [comment]
Perfect answer from @Steveb-p, i will elaborate a bit more, just to be on the safe side:

1. Commit is only for your consumer group, if you don't commit and the consumer stops / crashes, it will re-read that message the next time. If the same consumer continues though (without crashing / stopping), it will still read the next message.
2. Other consumer groups are not affected, they have their own offsets stored separately. Compared to other messaging systems, as long as the message is in Kafka, as many consumers as you like can consume it, it won't disappear after commit.

Hope this helps :v:

**Comment by askie** [comment]
@Steveb-p @nick-zh   thxs
