### ISSUE TITLE
Segmentation fault on php_request_shutdown

### ISSUE THREAD

**Issue by loggres** [php-rdkafka/php-rdkafka#381]
PHP version: 7.1.20
librdkafka version: 1_0.11.3
php-rdkafka version: 4.0.3

Php extension is installed but is not used in php code.
Sometimes Segmentation fault occur in different web requests. I have not found any pattern in this. All of these requests don't use php-rdkafka library.
Segmentation fault will disappear when php-rdkafka library is disabled.
I understand that this report looks strange, but there is definitely an issue. Unfortunately I can't provide a specific simple example for reproducing this issue. 

Please see this dump for one of Segmentation fault:
GNU gdb (Ubuntu 8.1-Oubuntu3.2) 8.1.0.20180409-git Copyright (C) 2018 Free Software  [Thread debugging using libthread_db enabled] Using host libthread_db library "flib/x86_64-linux-gnu/libthread_db.so.1". Core was generated by 'php-fpm: pool test Program terminated with signal SIGSEGV, Segmentation fault. 
#0 Ox000055ea2da59aee in shutdown_executor () (gdb) bt 
#0 Ox000055ea2da59aee in shutdown_executor () 
#1 Ox000055ea2da6aaab in zend_deactivate () 
#2 Ox000055ea2da06618 in php_request_shutdown () 
#3 Ox000055ea2d8de7bb in main () (gdb) 1

Issue is not reproduced at php-rdkafka 4.0.2. It's reproduced only at last version - 4.0.3

**Comment by Steveb-p** [comment]
@loggres thanks for the report.

Does it actually impact any requests, or is it "just" on shutdown? Was librdkafka library changed between versions?

**Comment by loggres** [comment]
@Steveb-p thanks for the quick response

Librdkafka was not changed between versions. All segmentation faults were at php_request_shutdown for random requests. Requests are processed to the end, but response for these requests is an error, because php-fpm returns an error on segmentation fault.
The same requests randomly produce this error. One of two equal requests may have this error and another will not.

**Comment by nick-zh** [comment]
Sounds like this could be related to #367 which is fixed, but not yet released
You could try building the extension from the master branch and check if this still happens

**Comment by nick-zh** [comment]
I am closing this, please reopen if this still happens for you, if you build from master
