### ISSUE TITLE
Re-check deprecation of setDefaultTopicConf

### ISSUE THREAD

**Issue by nick-zh** [php-rdkafka/php-rdkafka#384]
If seems for the low level consumer, some settings till need to be set over [setDefaultTopicConf](https://github.com/jobcloud/php-kafka-lib/issues/19).  
Check in librdkafka if we can get around using `rd_kafka_conf_set_default_topic_conf` which is said to be deprecated.

**Comment by nick-zh** [comment]
Got feedback from the maintainer of librdkafka:

> You can set it on the global config object unless you pass a topic config object or a default topic config object.
> In those two cases the global config for the topic will be ignored

I will check on our side if this happens somewhere, since it seems like the global config is ignored atm

**Comment by nick-zh** [comment]
So this is the current finding, after setting `auto.offset.reset`, a dump of the conf object will result in having:
```
...
    ['default_topic_conf'] = '0x55fd2d9260a0',
...
```
Which as mentioned above would cause a setting like `auto.commit.interval.ms` to be ignored on a global level.
Will further investigate if this happens inside `librdkafka` since i was unable to find code on our side that could cause this to happen.

**Comment by nick-zh** [comment]
`auto.commit.interval.ms` is a topic configuration for a low level consumer unlike the high level consumer where this is a global setting.
For libraries based on `php-rdkafka` or pure PHP implementations, this setting must be set on a topic config that can be passed to `newTopic`.
With this, i think it is fair to remove `setDefaultTopicConf` for the next major (was deprecated).

**Comment by Steveb-p** [comment]
@nick-zh we should remember to include this in upgrade path document, if it's created.

**Comment by nick-zh** [comment]
#387
