### ISSUE TITLE
Feature request: support producing messages with opaque

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [php-rdkafka/php-rdkafka#389]
librdkafka supports the concept of supplying an "opaque" value to a message when producing it.  This opaque value is a pointer to any application-defined object, and is not transmitted to the broker.  It is, however, provided in the delivery report.  One common use for this would be for the application to be able to link the delivery report with the original call to `producev`.  For example, one might want to do some metrics tracking in delivery report processing with additional information not directly available from the other message fields (e.g. tracking where in the code a message was produced).

Unfortunately, php-rdkafka does not support producing messages with opaque values.  I can work around this by using a special header when producing, but this does result in storing some garbage/useless headers in the topic.

I suppose the ideal state would be if any PHP object could be used as a message opaque, and be properly reference counted.  However, even supporting simple primitive types like integers and strings would be better than nothing.

**Comment by nick-zh** [comment]
Thanks a lot for the input, I will check this out.
Right now we are using opaques in the callback (for internal reasons) to pass the registered callback closures.

On the subject of headers, it is meant as metadata imho, so i do not think what you are sending is total garbage / useless, especially if there is important information like an originator, etc. in there.

There is some stuff that needs to be done for `php-rdkafka:5.0` so this might take some time, just as a heads up.

**Comment by james-johnston-thumbtack** [comment]
Here's an example from the Go producer client: https://godoc.org/github.com/confluentinc/confluent-kafka-go/kafka#Message --- The `Message` structure has an `Opaque` field.  This value is ultimately passed to the produce function in librdkafka, and is then seen in the delivery report when the `Message` structure is reconstituted.  In fact that particular framework has its own opaque values it needs to pass through, so they actually use a structure composed of both the user-provided opaque and their own opaque values.  In our Go services, I am currently planning on using this `Opaque` field to pass through a half-way initialized InfluxDB point, which is then completed in the delivery report handler.

By using headers, what I mean is I could have my client code maintain a simple auto-incrementing "next message ID" integer for the lifetime of the PHP script.  This can be put in the headers.  Simultaneously, I can also maintain a mapping of message ID to message & opaque values (whatever I need).  When I get the delivery report, I can examine the header for the message ID and then look in that map.  However, that message ID will have no meaning after the PHP script exits, and it's also not globally unique, which is why I say it's garbage afterwards.  After production, I would think partition ID + offset is a better identifier and more commonly used.

> There is some stuff that needs to be done for php-rdkafka:5.0 so this might take some time, just as a heads up.

No problem; I think the header workaround will work in practice for now, even if it seems ugly to me.

**Comment by nick-zh** [comment]
Ah i see, thanks a for the elaboration on this, this always helps a lot :v:

**Comment by arnaud-lb** [comment]
Implemented in #424. The produce() and producev() methods now have an $opaque parameter. The passed value is visible in Message::$opaque in dlivery report callbacks.

**Comment by arnaud-lb** [comment]
Released in version 5.0.0
