### ISSUE TITLE
Fatal error: Class 'RdKafka\KafkaConsumer' not found 

### ISSUE THREAD

**Issue by kushalhalder** [php-rdkafka/php-rdkafka#39]
All the other classes are working except this High Level Consumer Class. I installed using pecl.

**Comment by arnaud-lb** [comment]
Hi @kushalhalder,

RdKafka\KafkaConsumer is only available in the master branch of php-rdkafka right now. You need to install the extension from source. Also, make sure you have the latest librdkafka version.

**Comment by kushalhalder** [comment]
Yeah, working now. Thanks.

**Comment by martygan** [comment]
Hi there,

I'd like to use the High Level consumer class, but I git the same error as above:
> [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Class 'RdKafka\KafkaConsumer' not found

Here is my packages details: (working on PHP 7)

> $ pecl list
> Installed packages, channel pecl.php.net:
> Package Version State
> rdkafka 3.0.1   stable

> $ apt-cache policy librdkafka1
> librdkafka1:
>   Installé : 0.9.3-1~ bpo8+1
>   Candidat : 0.9.3-1~ bpo8+1

I think I'm up to date, and It looks like it's now included in the pecl package (http://pecl.php.net/package-changelog.php?package=rdkafka&release=3.0.1).

Do I still have to compile it myself ?
Maybe the doc/examples are outdated ?

`
        $conf = new RdKafka\Conf();

        // Set the group id. This is required when storing offsets on the broker
        $conf->set('group.id', 'demo.group');
        // Initial list of Kafka brokers
        $conf->set('metadata.broker.list', 'Kafka.cluster.lan');

        $rk = new RdKafka\Consumer($conf);
        $rk->addBrokers($brokerList);

        $topicConf = new RdKafka\TopicConf();
        $topicConf->set('auto.commit.interval.ms', 1e3);
        $topicConf->set("offset.store.sync.interval.ms", 60e3);

        // Set the offset store method to 'file'
        $topicConf->set('offset.store.method', 'file');
        $topicConf->set('offset.store.path', storage_path());

        // Alternatively, set the offset store method to 'broker'
        // $topicConf->set('offset.store.method', 'broker');

        // Set where to start consuming messages when there is no initial offset in
        // offset store or the desired offset is out of range.
        // 'smallest': start from the beginning
        $topicConf->set('auto.offset.reset', 'smallest');

        // Set the configuration to use for subscribed/assigned topics
        //$conf->setDefaultTopicConf($topicConf);

        $consumer = new RdKafka\KafkaConsumer($conf);

        $consumer->subscribe(['test']);

        //$topic = $rk->newTopic('test', $topicConf);

        //$topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);

        while (true) {
            // The first argument is the partition (again).
            // The second argument is the timeout.
            $message = $consumer->consume(120*1000);
            switch ($message->err) {
                case RD_KAFKA_RESP_ERR_NO_ERROR:
                    $this->processMessage($message);
                    // After successfully consuming the message, schedule offset store.
                    // Offset is actually committed after 'auto.commit.interval.ms'
                    // milliseconds.
                    //$consumer->offsetStore($message->partition, $message->offset);
                    break;
                case RD_KAFKA_RESP_ERR__PARTITION_EOF:
                    echo "No more messages; will wait for more\n";
                    break;
                case RD_KAFKA_RESP_ERR__TIMED_OUT:
                    echo "Timed out\n";
                    break;
                default:
                    throw new \Exception($message->errstr(), $message->err);
                    break;
            }
        }
`

**Comment by dhanashreeshetty19** [comment]
> have the latest librdkafka version.

hi latest version means which?? is  0.11.3 ok

**Comment by nick-zh** [comment]
@dhanashreeshetty19 latest version is `1.1.0`. You might still be fine, but there have been a lot of fixes since `0.11.3` i suggest to upgrade to at least to `0.11.6`, you can check all the fixes in the release notes:
https://github.com/edenhill/librdkafka/releases
**Edit**: no need to install from source anymore btw, this is an old issue, install through pecl is fine now.

**Comment by dhanashreeshetty19** [comment]
thanks @nick-zh. Actually my PHP version was 7.3, which i downgraded to 7.1. After this I again re-installed RD Kafka library the same version and now it's working. 

Thank-you!
