### ISSUE TITLE
MSG_TIMED_OUT with error code -192 in DrMsgCb normal?

### ISSUE THREAD

**Issue by xxm404** [php-rdkafka/php-rdkafka#391]
log:
```
[thrd:main]: test_cdc: 1 message(s) from 1 toppar(s) timed out
```
 * PHP version: 7.2.26
 * librdkafka version: 0.11.3
 * php-rdkafka version: 4.0.3
 * kafka version: 2.2.1

**Comment by Steveb-p** [comment]
@xxm404 Please upgrade librdkafka and try again.

**Comment by xxm404** [comment]
> @xxm404 Please upgrade librdkafka and try again.

@Steveb-p Thanks for the reply, update librdkafka to 1.1.0, still with error code -192 in DrMsgCb

**Comment by Steveb-p** [comment]
Please add debug logs from librdkafka. You can get those by adjusting your `Conf` object:

```php
<?php
$conf = new RdKafka\Conf();
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
$rk = new RdKafka\Producer($conf);
$rk->addBrokers("10.0.0.1:9092,10.0.0.2:9092");
```
(excerpt from readme)

Are you able to work with the broker using different tools? For example, can you commit messages using Kafka's `bin/kafka-console-producer.sh` script (https://kafka.apache.org/quickstart#quickstart_send)?

**Comment by nick-zh** [comment]
Yeah so `RD_KAFKA_RESP_ERR__MSG_TIMED_OUT` or `-192` means that the producer was not able to successfully send your message to the broker. Cause can be many things, you can find out more with the log instructions @Steveb-p provided to narrow it down or maybe you can see something from your broker logs.

**Comment by xxm404** [comment]
I add debug log for librdkafka, when `RD_KAFKA_RESP_ERR__MSG_TIMED_OUT` occurs, just get this log
```
[thrd:main]: test_cdc: 1 message(s) from 1 toppar(s) timed out
```
no other useful logs.

**Comment by Steveb-p** [comment]
@xxm404 that's strange. Make sure that you've actually passed that config to producer, because librdkafka is usually really, really verbose about what it's doing once it's put into debug mode.

Those logs will be output to stdout if I remember correctly.

**Comment by xxm404** [comment]
@Steveb-p Thanks for the reply.
This my producer code.
![image](https://user-images.githubusercontent.com/46340314/93741312-c6a2d500-fc1e-11ea-9cb3-c21dda2e2b1e.png)

**Comment by nick-zh** [comment]
@xxm404 `logCb` intercepts those messages right now, so if `DLog` is not logging to stdout you need to check where it ends up.
Quick fix would be to quickly remove `logCb` so it ends up in stdout again

**Comment by nick-zh** [comment]
Additionally, unless you have a good reason to adjust the defaults of `librdkafka`, like `max.retries`, `queue.buffering.max.ms`, etc. i would use the defaults.

If you are just staring out, also have a look at the examples here:
https://github.com/nick-zh/php-kafka-examples

**Comment by xxm404** [comment]
> @xxm404 `logCb` intercepts those messages right now, so if `DLog` is not logging to stdout you need to check where it ends up.
> Quick fix would be to quickly remove `logCb` so it ends up in stdout again

`DLog` will output the log to file.

**Comment by nick-zh** [comment]
Could you add your code here and also contents of your log file? But again, it points to an issue with broker communication.
You have set retries to only 3 (i think the default is quite higher), just wanted to point it out.

**Comment by xxm404** [comment]
@nick-zh Many thanks, the kafka doc `message.send.max.retries` default `3`
![image](https://user-images.githubusercontent.com/46340314/93746793-497c5d80-fc28-11ea-88e8-1f1fcc86cf19.png)
https://kafka.apache.org/08/documentation.html

**Comment by nick-zh** [comment]
@xxm404 best resource to check is:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
Since the extension is a wrapper for this c library. Also your link is for Apache Kafka `0.8.x` which is quite old 😉 
Unless you have already deep knowledge and know how to fine tune your settings, i advise to leave the defaults (so not setting them in conf).

**Comment by xxm404** [comment]
@nick-zh Thanks for the reply. I will modify the config to defalut value try to reproduce this error.

**Comment by nick-zh** [comment]
@xxm404 cool, if it still happens, post code and log out put so we can have a look what seems to go wrong ✌️

**Comment by nick-zh** [comment]
I will close this due to inactivity, feel free to reopen if you still have problems
