### ISSUE TITLE
php-rdkafka 4.1.0 requires librdkafka >= 1.4.0

### ISSUE THREAD

**Issue by cmb69** [php-rdkafka/php-rdkafka#402]
I've noticed that the PECL builds for php-rdkafka 4.1.0 were failing, because `rd_kafka_error_t` is not defined. Apparently, 4.1.0 requires at least librdkafka 1.4.0, what is not documented in the [changelog](https://pecl.php.net/package-changelog.php?package=rdkafka&release=4.1.0). The [setup documentation](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.requirements.html) even says that librdkafka >= 0.11.x would be supported.

**Comment by nick-zh** [comment]
Thanks @cmb69 for reporting this, i'll have a look. We should have if blocks to exclude all code for older `librdkafka` versions, but maybe i overlooked something

**Comment by cmb69** [comment]
Not sure if helpful for you, but the [build logs](https://windows.php.net/downloads/pecl/releases/rdkafka/4.1.0/logs/) are publicly available.

**Comment by cmb69** [comment]
Wow, that was fast. :) I can confirm that PR #404 solves the issue.

**Comment by nick-zh** [comment]
The least i could do, sry for the inconvenience. @arnaud-lb is busy with merging the `php8` branch atm, but i am pretty sure we can get this out soon :v:

**Comment by arnaud-lb** [comment]
Thank you @cmb69 @nick-zh . I will release a fixed 4.1.1 later today.

**Comment by nick-zh** [comment]
Thx a lot, added PR for the master branch as well ✌️

**Comment by arnaud-lb** [comment]
I've just released version 4.1.1

**Comment by nick-zh** [comment]
DLL's were successfully generated :tada: 
Thx again @cmb69 for letting us know :+1:
