### ISSUE TITLE
Generate php files to include

### ISSUE THREAD

**Issue by MarinoRaul** [php-rdkafka/php-rdkafka#41]
Hello !

I need to include PHP files in my PHP script for daemon!

How can i do this for not execute the following error:

"RKafka\Consumer not found in directory"

Thanks a lot!

**Comment by arnaud-lb** [comment]
Hi @MarinoRaul,

Make sure that the rdkafka extension is loaded. You likely have to add this to your php.ini:

`extension=rdkafka.so`

Then restart apache/nginx/php-fpm.

**Comment by MarinoRaul** [comment]
Hello. I refer when I run in Linux console CLI. "php myScript.php" how can I include , require php library files because I got that not found RdKafka/Producer when I instance that. I have in my PHP.ini RdKafka.so

Thanks a lot

**Comment by arnaud-lb** [comment]
You don't have to include any file, the extension defines all the `RdKafka\`\* classes alrady. All you have to do is to make sure that the extension is loaded by php-cli. You can find which extensions are being loaded by running `php -m`. You can find the path of the `php.ini` used by php-cli by running `php -i` (the beginning of the output lists the php.ini files that have been loaded).
