### ISSUE TITLE
Local: Host resolution failure

### ISSUE THREAD

**Issue by dinohrascanec** [php-rdkafka/php-rdkafka#413]
**Problem**
We're having a problem connecting to a remote broker from local environment. There is a remote producer that created a topic and put some content in it. We created a consumer and added previously mentioned IP and topic. However, we get error "Local: Host resolution failure". 

**Info**
 * PHP version: 7.1
 * librdkafka version: 1.2.1
 * php-rdkafka version: latest
 * kafka version: latest

**Code**
```
<?php
$conf = new RdKafka\Conf();
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
$rk = new RdKafka\Consumer($conf);
$rk->addBrokers("XX.XX.XX.XX:9092");
$topic = $rk->newTopic("test-topic-1");

$topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);
while (true) {
    $msg = $topic->consume(0, 1000);
    if (null === $msg || $msg->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
        continue;
    } elseif ($msg->err) {
        var_dump($msg);
        echo $msg->errstr(), "\n";
        break;
    } else {
        echo $msg->payload, "\n";
        exit;
    }
}

```

**Error:**
```
object(RdKafka\Message)[4]
   'err' => int -193
   'topic_name' => string 'test-topic-1' (length=12)
   'timestamp' => null
   'partition' => int 0
   'payload' => null
   'len' => null
   'key' => null
   'offset' => int -1
   'headers' => null
Local: Host resolution failure
```

**Comment by nick-zh** [comment]
I would advice using the hostname (advertised host name) of the broker instead of the ip.
Check if you can reach the IP / hostname from your local evn.
I remember there was an error for older librdkafka versions (but you are stating you are using `1.5.3`),  on osx because of `getaddrinfo`.
If the above doesn't fix it, try searching issues in `librdkafka` with this error, since we are just a wrapper.
So far i haven't had any problems connecting to external brokers.

**Comment by dinohrascanec** [comment]
Hey @nick-zh , thank you for response.

Yes, I can reach IP. I've tried pinging it through terminal and it works.

Advertised host name should be set and provided to us by producer, right?

I'm using Linux Ubuntu, and librdkafka version is 1.2.1, my phpinfo() says it's from December the 3rd, 2020. When I try updating it, it says "librdkafka-dev is already the newest version (1.2.1-1ubuntu1)".

**Comment by nick-zh** [comment]
`librdkafka:1.2.1` should be new enough, yeah you can set the hostname and port with `addBroker` or in the conf as `metadata.broker.list` maybe if you enable additional output you can see more:
```
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
```

**Comment by nick-zh** [comment]
as a side note, just noticed you are using the low level consumer, i would advise using the high level consumer instead, not related to your problem though :smile:
