### ISSUE TITLE
IDE helper for php-rdkafka (stubs)

### ISSUE THREAD

**Issue by cjhlai** [php-rdkafka/php-rdkafka#418]
Hi，arnaud，can  U provide the php-rdkafka-helper for the phpstorm.it will be very usefull .thanks!

**Comment by cjhlai** [comment]
@arnaud-lb  hope for your reply.tks

**Comment by nick-zh** [comment]
Can you elaborate? [phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs) already includes stubs for autocompletion, also there is [kwn/php-rdkafka-stubs](https://github.com/kwn/php-rdkafka-stubs)

**Comment by cjhlai** [comment]
but i can not jump the function to declaration.how can i install.thanks@nick-zh

**Comment by nick-zh** [comment]
Please check the readme of either projects mentioned above

**Comment by hiteshrsdigitech** [comment]
> but i can not jump the function to declaration.how can i install.thanks@nick-zh

install kwn/php-rdkafka-stubs by running this command

`composer require kwn/php-rdkafka-stubs --dev
`
