### ISSUE TITLE
PHP Kafka Consumer - Reading AVRO Data

### ISSUE THREAD

**Issue by dinohrascanec** [php-rdkafka/php-rdkafka#428]
Is it possible to read Kafka AVRO data and parse it to JSON through Kafka Consumer?

If yes, please some guidelines.

**Comment by nick-zh** [comment]
This is not possible with the extension only, you can check this example how to do it with a 3rd party library:
https://github.com/php-kafka/php-kafka-examples/blob/main/src/ext-php-rdkafka/php-kafka-lib/avroHighLevelConsumer.php

Alternatively you can use another php avro implementation that is available
