### ISSUE TITLE
why $topic->consume(0, 1000) return with NULL

### ISSUE THREAD

**Issue by changg-1991** [php-rdkafka/php-rdkafka#43]
I run the demo code but found the function below return with NULL 
$msg = $topic->consume(0, 1000);
I can't find why
help, please
%>_<%

**Comment by arnaud-lb** [comment]
Hi @changg-1991,

NULL means that consume() timed out: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-consumertopic.consume.html#refsect1-rdkafka-consumertopic.consume-returnvalues

The timeout is specified as second parameter.
