### ISSUE TITLE
optional parameter

### ISSUE THREAD

**Issue by athaden** [php-rdkafka/php-rdkafka#432]
Hello,
https://github.com/arnaud-lb/php-rdkafka/blob/62193e91c28bfed8b417dd22021f2e2c46612003/kafka_consumer.c#L544
I have a question about method "getMetadata". The parameter $only_topic is optional in documentation: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-kafkaconsumer.getmetadata.html is this correct? the following parameter  $timeout_ms is required.
Best regards, Andreas

**Comment by nick-zh** [comment]
You need to pass all three, but only_topic can be null, switching the order could be an improvement

**Comment by arnaud-lb** [comment]
Hello @athaden 

This is a documentation issue: The argument is nullable, but not optional.

This is fixed now. Thanks !
