### ISSUE TITLE
Documentation for php-rdkafka

### ISSUE THREAD

**Issue by kwn** [php-rdkafka/php-rdkafka#44]
Hi guys,

I'm building stubs for rdkafka 0.9.1. I'm using that docs: https://arnaud-lb.github.io/php-rdkafka/phpdoc/

I've found some issues/typos and I'm happy to fix them, but I can't really find sources for this documentation. Where do you store it? How do you generate and deploy it?

**Comment by arnaud-lb** [comment]
Hi @kwn,

That would be much appreciated! I put the documentation's sources at https://github.com/arnaud-lb/php-rdkafka-doc :)

**Comment by kwn** [comment]
Oh, I can see it now. Thanks :+1:
