### ISSUE TITLE
Undefined namespace 'RdKafka' 

### ISSUE THREAD

**Issue by GabrielCHEN1** [php-rdkafka/php-rdkafka#441]
* PHP version:
 ```
➜  7.2 php -v
PHP 7.2.33 (cli) (built: Aug  7 2020 18:29:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33, Copyright (c) 1999-2018, by Zend Technologies
```
 * librdkafka version:
 * php-rdkafka version:
 ```
➜  7.2 php --ri rdkafka

rdkafka

rdkafka support => enabled
version => 4.1.2
build date => Jan 25 2021 14:39:20
librdkafka version (runtime) => 1.5.0
librdkafka version (build) => 1.5.0.255
```
 * kafka version:

first,  i write example code in `testk.php`
```
<?php
$conf = new RdKafka\Conf();
?>
```
IDE(phpstorm) show warning `Undefined namespace 'RdKafka' `

Is there a way to remove the prompt ?

**Comment by nick-zh** [comment]
PHPStorm should already come with stubs for `php-rdkafka`, if somehow this doesn't work for you, you can install the 3rd party stubs mentioned in the readme

**Comment by GabrielCHEN1** [comment]
This problem has been resolved, thank you very much 👍

**Comment by daxiongmama** [comment]
> This problem has been resolved, thank you very much 👍

Hello, I have the same problem as you, do you solve the problem with “composer require kwn/php-rdkafka-stubs --dev”？

**Comment by NeilMasters** [comment]
Hi all, just a note to say that I had to enable the stubs manually in phpstorm. You can enable this by going to Preferences -> PHP -> PHP Runtime -> Pecl and tick rdkafka.
