### ISSUE TITLE
How to use php to achieve batch consumer ？

### ISSUE THREAD

**Issue by xxm404** [php-rdkafka/php-rdkafka#442]
* PHP version: 7.2.26
 * librdkafka version: 1.5.0
 * php-rdkafka version: 3.1.2
 * kafka version: 2.2.0

How to use php to achieve batch consumer like `librdkafka` example https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consume_batch.cpp

**Comment by nick-zh** [comment]
This can be done in the low level consumer:
https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-consumertopic.consumebatch.html
But i would discourage to consume this way since it is a deprecated / outdated API :v:

**Comment by xxm404** [comment]
Thanks for the reply. @nick-zh
