### ISSUE TITLE
 How to achieve exactly-once consumer use subscribe？

### ISSUE THREAD

**Issue by xxm404** [php-rdkafka/php-rdkafka#443]
* PHP version: 7.2.26
 * librdkafka version: 1.5.0
 * php-rdkafka version: 3.1.2
 * kafka version: 2.2.0

How to achieve exactly-once consumer use subscribe？

**Comment by nick-zh** [comment]
This has nothing to do with the extension or the library, but it is up to the application to handle this, maybe this article helps:
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/
