### ISSUE TITLE
Support for OAUTHBEARER mechanism

### ISSUE THREAD

**Issue by prasam60** [php-rdkafka/php-rdkafka#447]
* PHP version: 7.4
 * librdkafka version:1.6.1
 * php-rdkafka version: 5.0.0
 * kafka version:

It seems like the Conf class is missing setter function for librdkafka configuration property `oauthbearer_token_refresh_cb`. This needs to be similar to how there are setter for other callback options. ex.
` setRebalanceCb` `setStatsCb` etc.

This is currently blocking me from using OAUTHBEARER SASL Mechanism. When I try to set this property directly, the below error is thrown
`Property "oauthbearer_token_refresh_cb" must be set through dedicated .._set_..() function`

**Comment by prasam60** [comment]
Hi Nick, 
Sorry couldn't provide a PR since I haven't worked in C for more than a decade. 
Do you have a rough estimate of the effort involved here? as well as when can this be expected to be released?

Thanks,
Pratik

**Comment by nick-zh** [comment]
@prasam60 effort should be small, but atm i do not have a lot of time for open source work, if this is of high importance to you, you can reach out privately

**Comment by pmmaran** [comment]
Guys,
Any update, would be great if you can build this feature 😉 at moment I am stuck without this

**Comment by ciaran-moore** [comment]
It looks like I need to get this to work for a project we have coming, however, being messed around with credentials.
I have added the callback for `oauthbearer_token_refresh_cb` but don't have a way of testing. If anyone could try it and let me know if this update resolves this issue, I will raise a pull request.
https://github.com/ciaran-moore/php-rdkafka  <-- repository
https://github.com/ciaran-moore/php-rdkafka/commit/dea8497d9eb600bf5db76c0b2f67568a2fe391a7 <-- commit

**Comment by arnaud-lb** [comment]
Implemented in https://github.com/arnaud-lb/php-rdkafka/pull/546 and https://github.com/arnaud-lb/php-rdkafka/pull/547
