### ISSUE TITLE
Using this lib in long running process

### ISSUE THREAD

**Issue by raph007** [php-rdkafka/php-rdkafka#448]
Hi,

What is your recommendation for managing Kafka consumer, witch is long-running process, with this lib? 

Should it be restarted from time time to minimize memory leaks or solution such as Supervisord in case consumer went down, is enough?

**Comment by nick-zh** [comment]
I did not have any problems so far and we have consumers running for a very long time

**Comment by Steveb-p** [comment]
@raph007 if you don't have any memory leaks in your application, then it's usually fine to allow it to run a long time (in my case, I often had processes that were alive for days).

Supervisord is the way to go. You can also use other similar tools. For example I use pm2 (nodejs based)
```shell
pm2 start --name="process-name" --interpreter=php -- bin/console app:process
```
