### ISSUE TITLE
Question: Usage offsetsForTimes

### ISSUE THREAD

**Issue by dondon00** [php-rdkafka/php-rdkafka#449]
* PHP version: PHP 7.4.3
 * php-rdkafka version: 5.0.0
 * kafka version: 2.2.1

I'm trying to get the offset closest to the timestamp with offsetsForTimes. But I can't get it to work. For me it's also not clear in the manual how to use this. Even converting the object to array didn't work. What's wrong?

```php
<?php
$conf = new RdKafka\Conf();
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('security.protocol', 'SASL_SSL');
$conf->set('sasl.mechanism', 'SCRAM-SHA-512');
$conf->set('sasl.username', 'XXXXX');
$conf->set('sasl.password', 'XXXXX');
$conf->set('metadata.broker.list','XXXXX:9096');
$conf->set('group.id', 'offset_times');

$consumer = new RdKafka\KafkaConsumer($conf);
$partition = new RdKafka\TopicPartition("debug_partition",1);
echo $consumer->offsetsForTimes($partition,1546300861000);
```

```
PHP Warning:  RdKafka\KafkaConsumer::offsetsForTimes() expects parameter 1 to be array, object given
```

**Comment by nick-zh** [comment]
Heya @dondon00 
So from the doc:
```
Is an array of RdKafka\TopicPartition, assign your timestamp to the offset during instantiation of RdKafka\TopicPartition
```
So this means you need to:
```
$topicPartition = new  RdKafka\TopicPartition($topic, $partition, $timestamp);
var_dump($consumer->offsetsForTimes([$partition],$timeout));
```
The result you get is a TopicPartition object, but the timestamp will be replaced with an actual offset.
Hope that helps :v:

**Comment by dondon00** [comment]
@nick-zh 

Thank you, that did the trick! For me also [$partition] was unclear, as I tried to typecast it with $array = (array)$topicPartition;
I get the output now, but not the right offset. Tried also a timestamp before/ after the log with correct timestamp, but no correct result. I will play a bit more with it to see how it's behaving.

**Comment by nick-zh** [comment]
No worries, just to be clear, this will be an approximate result not an exact one, Kafka will try it's best to get as close as possible, but you might read a few messages more, or if there is no offset for this timestamp, it will return the next greater one, according to doc:
```
a mapping from partition to the timestamp and offset of the first message with timestamp greater than or equal to the target timestamp. null will be returned for the partition if there is no such message.
```
