### ISSUE TITLE
Write HHVM extension glue

### ISSUE THREAD

**Issue by adamwight** [php-rdkafka/php-rdkafka#45]
I'm looking at using this extension to replace aging ActiveMQ infrastructure in our production application.  We're planning to migrate our servers to HHVM in the next year, so I'd be very interested in helping write HHVM glue for your module.  There's a decent overview of the process [here](http://www.sklar.com/software/php/2015/05/07/converting-a-php-extension-to-hhvm/), it includes some slightly annoying details like renaming all of the C files ".cpp", and repeating the function declarations in a new .php file.

Please let me know if this is a direction you'd like to pursue, and I'll start looking at writing the glue.

Nice work on this extension, thank you!

**Comment by arnaud-lb** [comment]
Hi @adamwight,

I would happily accept such a contribution :)

**Comment by adamwight** [comment]
@arnaud-lb 
Great, thanks for the note!  We're still deciding which data store to use, and I'll let you know if we choose Kafka, in which case I'm certain we'll be using your extension.  That question should be resolved within a month.

**Comment by arnaud-lb** [comment]
Let me know if you need help :)

**Comment by danielmitd** [comment]
> That question should be resolved within a month.

So I guess the decision was against kafka 😉

**Comment by tPl0ch** [comment]
@arnaud-lb I guess this can be closed too? If somebody needs an HHVM glue (I don't believe so), they can reopen the issue.
