### ISSUE TITLE
Question: Is php-rdkafka compatible with redpanda?

### ISSUE THREAD

**Issue by denisgolius** [php-rdkafka/php-rdkafka#451]
I want to try use redpanda instead of using rabbitmq  because it Kafka compatible. Does **php-rdkafka** is compatible with [redpanda](https://vectorized.io/docs/faq/#What-clients-do-you-recommend-to-use-with-Redpanda)?

We use php7.4/symfony 4 and think about migration to new symfony framework version 5.x  under php 8

**Comment by nick-zh** [comment]
As it seems to be compatible with `librdkafka` i would say yes, since we are only a wrapper for `librdkafka`

**Comment by nick-zh** [comment]
Quickly tested it, seems to work fine

**Comment by denisgolius** [comment]
Thank you for fast feedback.👍
