### ISSUE TITLE
Call to undefined method RdKafka\ProducerTopic::producev() - v5.0.0

### ISSUE THREAD

**Issue by mvaliolahi-work** [php-rdkafka/php-rdkafka#453]
Hello, 

I face this error: `Call to undefined method RdKafka\ProducerTopic::producev()`.

 * PHP version: 7.4.9
 * php-rdkafka version: 5.0.0
 * kafka version: 2.7.0
 * OS:  Linux

**Comment by Steveb-p** [comment]
Hello @mvaliolahi-work.

Check the librdkafka library your system uses. In most cases this indicates you're using a librdkafka version that is obsolete (and phprdkafka was built against it).

You can check it in the output of `phpinfo()` or by calling `php -i | grep librdkafka`.

**Comment by mvaliolahi-work** [comment]
@Steveb-p

here are my current version:

librdkafka version (runtime) => 0.11.3
librdkafka version (build) => 0.11.3.255

**Comment by Steveb-p** [comment]
Install newer version (preferably from the 1.x) and rebuild phprdkafka. You should be fine then.

**Comment by mvaliolahi-work** [comment]
Thanks @Steveb-p

**Comment by nick-zh** [comment]
What @Steveb-p said, oldest supported version is `librdkafka:0.11.6` suggested is `librdkafka:1.x`
