### ISSUE TITLE
Support to alter offsets

### ISSUE THREAD

**Issue by KlimTodrik** [php-rdkafka/php-rdkafka#454]
* PHP version: any
 * librdkafka version: any
 * php-rdkafka version: 1.6.1
 * kafka version: 0.10+

Can you create support for [seek](https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#seek(org.apache.kafka.common.TopicPartition,%20long)) method? 

It allows to shift offset on consumer. 

As you can see this method alerady [implemented](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L2746) in rdkafka

**Comment by nick-zh** [comment]
You can read from specific offsets using `KafkaConsumer:assign`.
Also as mentioned in Gitter, if you really want to change the offset, use the scripts provided with Kafka, in this case `kafka-consumer-groups.sh`.

**Comment by KlimTodrik** [comment]
Yes I know about CLI, but I need to update offsets via rdkafka

**Comment by nick-zh** [comment]
As i said in Gitter, from what i understand, neither `assign` nor `seek` changes the commited offset on Kafka, but simply allows the consumer to read from a previous offset. If this is all you need to do, then `assign` should do the job.

**Comment by KlimTodrik** [comment]
No, seek allows to shift offset for selected group. Like CLI `--reset-offsets --to-offset`

**Comment by nick-zh** [comment]
I am fairly certain it does not, the [doc block](https://github.com/edenhill/librdkafka/blob/8bacbc0b4c357193288c81277bfcc815633126ea/src/rdkafka.h#L3499) in librdkafka suggest that it will simply refetch messges from an offset, but it does not mention anything about changing the offset. [This](https://github.com/edenhill/librdkafka/issues/2965#issuecomment-654198538) comment from Magnus suggests the same. I am open though if you can point me to a source which mentions that the commited offset is actually changed.

**Comment by nick-zh** [comment]
What you are looking for can only be achieved with the AdminApi from what i know and we do not support that yet (see #215)

**Comment by nick-zh** [comment]
I am closing this, since what you want is a possibility to alter offsets and as mentioned, we'll solve this in #215 :v:
