### ISSUE TITLE
 Uncaught RdKafka\KafkaErrorException: _STATE on the RdKafka/Producer

### ISSUE THREAD

**Issue by Emik123dsa** [php-rdkafka/php-rdkafka#456]
- PHP version: 8.0.6
- librdkafka version: 1.6.1
- php-rdkafka version: 5.0.0
- kafka version: 6.1.1-ccs;

Hello,
I'm using a Coroutine client with Swoole extension and trying to send a transaction in the example below:
  $this->server->on(DatagramWorkerEnum::WORKERSTART, function() {
                /** @var ConnectionPool create pool connection; */
                $this->pool->init();
                $this->addConnectionPool(KafkaProducerPoolInterface::class, $this->pool);
  });
```
/** @var ConnectionPool $pool */
  $this->server->on(DatagramWorkerEnum::PACKET, function(Server $server, string $data) {
            $pool = $this->getConnectionPool(KafkaProducerPoolInterface::class);
            /** @var KafkaProducerService $producerService */
            $data = [];
            $producerService = $pool->borrow();
            $producerService->setTopic(env("...") ?? "default");
            $producerService->initTransactions((int) env("..."));
            try {
               $producerService->beginTransaction();
               $producerService->produce(json_encode($data, JSON_FORCE_OBJECT));
               $producerService->commitTransaction((int) env("..."));
            } catch(\RdKafka\KafkaErrorException $e) {
            if ($e->transactionRequiresAbort()) $producerService->abortTransaction((int) env("..."));
            } finally {
               $producerService->flush((int) env("..."));
            }
});
```
My first transaction on the request works well, but on the second I'm getting an error like this:
Fatal error: Uncaught RdKafka\KafkaErrorException: _STATE ...

**Comment by nick-zh** [comment]
`$e->getErrorString()` and `$e->getMessage()` should reveal more information in what's going wrong, additionally you might also want to upgrade to the freshly released `librdkafka:1.7.0` which fixed a lot of issues for the transactional producer :v:

**Comment by Emik123dsa** [comment]
Thank you so much for mentioning it! I just reinstalled libradkafka-dev from the src on my docker image, but it gave the same result like before.
First time transaction is comitting correctly, but on the second time my initTransactions is throwing an error **"Operation not valid in state Ready"** ($e->getErrorString()). I have also tried to change 'transaction.id' to the same/different names, but still the same.

**Comment by nick-zh** [comment]
`initTransactions` only needs to be called at the very beginning you don't need to re-call it for every transaction, let me know if that doesn't resolve it

**Comment by Emik123dsa** [comment]
Great! Finally it works, Thank you so much!

**Comment by nick-zh** [comment]
Glad to hear it works :v:
