### ISSUE TITLE
Log Location for php-rdkafka

### ISSUE THREAD

**Issue by xxm404** [php-rdkafka/php-rdkafka#458]
When I set
```
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
```
Kafka log will output to STDERR，I want to output the log to file, my php-rdkafka version < 4.0.0 I can not use the `setLogCb` how can I output the log to file?

 * PHP version: 7.2.26
 * librdkafka version: 1.5.0.255
 * php-rdkafka version: 3.1.2
 * kafka version: 2.2.1

If possible, add debug logs from librdkafka, which you can obtain by adjusting your configuration:
```php
<?php
$conf = new RdKafka\Conf();
// Add the two settings below for a more verbose output
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
```

**Comment by nick-zh** [comment]
I would try to pipe stdout/stderr of that process to a file or something like that, i am sure there are several ways to do this :v:
