### ISSUE TITLE
Consumer not working

### ISSUE THREAD

**Issue by durgatiwari** [php-rdkafka/php-rdkafka#46]
Consumer on start gives an error:
%4|1461081921.391|PROTOERR|rdkafka#consumer-1| xx.xxx.xx.xx:9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3042
%4|1461081921.391|PROTOERR|rdkafka#consumer-1| xx.xxx.xx.xx:9092/0: expected 7298525 bytes > 1048600 remaining bytes.
Unable to figure out the reason for such an error. Tried different configuration for consumer setting still the same issue.

**Comment by arnaud-lb** [comment]
Hi @durgatiwari,

What's your librdkafka version, and Kafka server version ?

**Comment by durgatiwari** [comment]
Hi @arnaud-lb ,
librdkafka version - 0.9.1
kafka server version - 0.8.2.2

**Comment by arnaud-lb** [comment]
Could you try setting the `broker.version` property to `0.8.2` ?

**Comment by durgatiwari** [comment]
Hi @arnaud-lb,
Awesome it worked. Thank you.
