### ISSUE TITLE
KafkaConsumer->commit() crash

### ISSUE THREAD

**Issue by lucabrunox** [php-rdkafka/php-rdkafka#48]
Whenever `commit()` is called php-rdkafka crashes with segmentation fault.
Calling `commit(null)` says that null is not a valid operation.
Calling `commit($message)` works.

So basically the two cases that are most interesting are not working. I'm using php-rdkafka commit 6ad5fea24cb697a9 and rdkafka 0.8.6-1 compiled from librdkafka-confluent-debian-0.9.0.99 release, php 5.6.19+dfsg-0+deb8u1.

Last frame of the crash:

```
#0  consumer_commit (async=0, ht=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>, return_value_ptr=<optimized out>, 
    return_value=<optimized out>) at php-rdkafka/kafka_consumer.c:439
439         if (Z_TYPE_P(zarg) == IS_OBJECT && instanceof_function(Z_OBJCE_P(zarg), ce_kafka_message TSRMLS_CC)) {
(gdb) l
434     if (!intern) {
435         return;
436     }
437 
438     if (zarg) {
439         if (Z_TYPE_P(zarg) == IS_OBJECT && instanceof_function(Z_OBJCE_P(zarg), ce_kafka_message TSRMLS_CC)) {
440             zval *zerr;
441             zval *ztopic;
442             zval *zpartition;
443             zval *zoffset;
```

**Comment by arnaud-lb** [comment]
Hi @lethalman 

Thanks for your report. I'll investigate. 

> using php-rdkafka commit 6ad5fea and rdkafka 0.8.6-1 compiled from librdkafka-confluent-debian-0.9.0.99 release

Are you sure you are using librdkafka 0.8.6 ? This version doesn't have the symbols for the high level consumer.

**Comment by lucabrunox** [comment]
@arnaud-lb I'm using the latest release from github `confluent-debian-0.9.0.99`, but it's still versioned 0.8.6 in the `debian/changelog` :)

**Comment by arnaud-lb** [comment]
I believe I've just fixed this, could you confirm?

**Comment by lucabrunox** [comment]
@arnaud-lb I will check tomorrow at work, thanks!

**Comment by lucabrunox** [comment]
Confirming thanks a lot.
