### ISSUE TITLE
close() not shutting down consumer all the way (?)

### ISSUE THREAD

**Issue by mrubin** [php-rdkafka/php-rdkafka#507]
### Description

I have code like the below

```php
$consumer = new RdKafka\KafkaConsumer($conf);

// consume some data into a file

$consumer->close();

// some time-consuming processing on the file that was retrieved (by consuming data from Kafka)
```

During the post-consumption processing, after the consumer has been closed, I consistently see output like:

```
%3|1642302561.466|ERROR|rdkafka#consumer-3| [thrd:kafka-2.mysite.private:9092/bootstrap]: 3/3 brokers are down
```

Is `$consumer->close();` not shutting librdkafka down "all the way" or something like that? Why am I seeing this message in the logs? When I have the above code running in a loop (create consumer, consume, close consumer, process, repeat), I consistently see the above error message some time after consumption ends... yet in the next run through the loop, I'm able to consume from Kafka without issue. The brokers aren't down.

I should note that I call `$consumer->offsetsForTimes(...)` and then assign those partitions. Once I'm done with each partition (I'm consuming between two dates), I remove it and call `assign()` again (without that partition). When there are no more partitions, I call `assign(NULL)` and stop consuming (after which time `$consumer->close();` is called).

### php-rdkafka Version

6.0.0

### librdkafka Version

1.6.2.255

### PHP Version

7.4.27

### Kafka Version

2.6

**Comment by arnaud-lb** [comment]
Hi @mrubin 

`KafkaConsumer::close()` is calling [`rd_kafka_consumer_close()`](https://github.com/edenhill/librdkafka/blob/8e1353ccb00b9d0d3cc3205ff2de45c91da80626/src/rdkafka.h#L3970-L3988) internally.

This function causes this KafkaConsumer instance to leave the consumer group. However, it will not destroy the rd_kafka_t handle immediately.

Currently the only way to destroy the rd_kafka_t handle is to make sure that your code has no reference to the KafkaConsumer, or any Topic object created by it.

**Comment by mrubin** [comment]
Thank you for the quick response.

I'm quite sure I'm not retaining any references to consumer or topic... I've even tried:

```php
$consumer->close();
unset($consumer);
$consumer = null;
```

But after reading about it a bit, I understand there's no way to force PHP to destroy/reclaim an object on demand... it's a GC kind of process. Sounds like you're doing the right thing as far as calling `rd_kafka_consumer_close()`.
