### ISSUE TITLE
Exception : RdKafka\Metadata::__construct() has not been called

### ISSUE THREAD

**Issue by daavelar** [php-rdkafka/php-rdkafka#530]
### Description

The following code:

```php
<?php

$metadata = new Metadata;
$metadata->getTopics()
```

Resulted in this output:
```
Exception : RdKafka\Metadata::__construct() has not been called
```

But I expected to get the topics list.

### php-rdkafka Version

php-rdkafka 6.0.3

### librdkafka Version

1.8.2~1confluent7.2.1-1

### PHP Version

php 8.1.8

### Operating System

Ubuntu 22.04

### Kafka Version

2.6.3

**Comment by nick-zh** [comment]
This might be misleading, you need to call an `RdKafka` or `KafkaConsumer` instance to get metadata, see [doc](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/class.rdkafka-metadata.html)
Maybe docs or examples can be improved to make this more clear
