### ISSUE TITLE
Problem of consuming messages

### ISSUE THREAD

**Issue by ghost** [php-rdkafka/php-rdkafka#54]
Hi, I have some problems of consuming messages.

```
 * PHP version:  5.4.45
 * librdkafka version: 0.9.1.0
 * php-rdkfaka version: 0.9.1
```

Here is my code:

```
<?php

$conf = new RdKafka\Conf();

$conf->set('group.id', 'testgroup');

$rk = new RdKafka\Consumer();
$rk->addBrokers("10.1.14.15");

$queue = $rk->newQueue();

$topicConf = new RdKafka\TopicConf();

$topic = $rk->newTopic("my-test3", $topicConf);

$topic->consumeQueueStart(0, RD_KAFKA_OFFSET_STORED, $queue);

while (true) {

    $msg = $queue->consume(1000);

    if ($msg->err) {
        echo $msg->errstr(), "<br>";
        return;

    } else {

        echo $msg->payload, "<br>";
    }

}
```

And it gets an error like this:

```
PHP Fatal error:  Uncaught exception 'RdKafka\Exception' with message 'Local: Invalid argument or configuration' in /home/www/site/consumer_2.php:16
Stack trace:
#0 /home/www/site/consumer_2.php(16): RdKafka\ConsumerTopic->consumeQueueStart(0, -1000, Object(RdKafka\Queue))
#1 {main}
  thrown in /home/www/site/consumer_2.php on line 16
```

It seems that RD_KAFKA_OFFSET_STORED is an Invalid argument.

**Comment by arnaud-lb** [comment]
Hi @SuperDo-Zergling,

It seems that you didn't pass the $conf object to `new RdKafka\Consumer()`. As a result, the consumer doesn't have a `group.id`. `group.id` is required when using the broker's offset storage, which is the default in librdkafka 0.9.

Passing $conf to `new RdKafka\Consumer()` should fix the issue :)

**Comment by ghost** [comment]
Thanks. I forgot to pass $conf object. Now it works.
But another question, When I restart this consumer, the consumer still return the same data we have consumed in the kafka. 
In order to let the consumer always get the data we have not consumed,  I use RD_KAFKA_OFFSET_STORED. but it does't work. Is it right?

**Comment by arnaud-lb** [comment]
librdkafka stores offset at an interval controlled by the value of `auto.commit.interval.ms`. By default it's 60000ms, meaning that if you kill the program before 60000ms, it will not store the offset.
