### ISSUE TITLE
My producer executed once,but it produced 3 records.

### ISSUE THREAD

**Issue by 305983806** [php-rdkafka/php-rdkafka#56]
- PHP version: 5.5.35
- Kafka version: 0.8.2
- librdkafka version: master
- php-rdkfaka version: master
## PHP Code

``` php
<?php
    $rk = new \RdKafka\Producer();
    $rk->setLogLevel(LOG_DEBUG);
    $rk->addBrokers(env("KAFKA_HOST"));
    $topic = $rk->newTopic($topic);
    $topic->produce(RD_KAFKA_PARTITION_UA, 0, $content);
```
## My Issues

```
# bin/kafka-console-consumer.sh --zookeeper localhost:2181 --from-beginning --topic AppAccess
123 ua12555354  1464766008000
123 ua12555354  1464766008000
123 ua12555354  1464766008000
```
## Question

My producer executed once,but it produced 3 records.
I don't know in which part the problem occurs.

**Comment by arnaud-lb** [comment]
Hi,

Could you try with the latest master and see if you still have the same issue ?
