### ISSUE TITLE
PHP 7.0 to 7.2: undefined symbol: zval_get_tmp_string

### ISSUE THREAD

**Issue by remicollet** [php-rdkafka/php-rdkafka#562]
### Description

During build
```
/builddir/build/BUILD/php-pecl-rdkafka6-6.0.4/rdkafka-6.0.4/rdkafka.c: In function 'zim_RdKafka_oauthbearerSetToken':
/builddir/build/BUILD/php-pecl-rdkafka6-6.0.4/rdkafka-6.0.4/rdkafka.c:492:46: warning: implicit declaration of function 'zval_get_tmp_string'; did you mean 'zval_get_string'? [-Wimplicit-function-declaration]
             zend_string *extension_val_str = zval_get_tmp_string(extension_zval, &tmp_extension_val_str);
                                              ^~~~~~~~~~~~~~~~~~~
                                              zval_get_string

```

At runtime:

```
# php  extension=php/modules/rdkafka.so --modules
PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/php-pecl-rdkafka6-6.0.4-4.el8.remi.7.2.x86_64/usr/lib64/php/modules/rdkafka.so' (tried: /builddir/build/BUILDROOT/php-pecl-rdkafka6-6.0.4-4.el8.remi.7.2.x86_64/usr/lib64/php/modules/rdkafka.so (/builddir/build/BUILDROOT/php-pecl-rdkafka6-6.0.4-4.el8.remi.7.2.x86_64/usr/lib64/php/modules/rdkafka.so: undefined symbol: zval_get_tmp_string), /usr/lib64/php/modules//builddir/build/BUILDROOT/php-pecl-rdkafka6-6.0.4-4.el8.remi.7.2.x86_64/usr/lib64/php/modules/rdkafka.so.so (/usr/lib64/php/modules//builddir/build/BUILDROOT/php-pecl-rdkafka6-6.0.4-4.el8.remi.7.2.x86_64/usr/lib64/php/modules/rdkafka.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

```

### php-rdkafka Version

6.0.4

### librdkafka Version

2.6.0

### PHP Version

7.0 to 7.2

**Comment by remicollet** [comment]
Also, with 7.0:   `undefined symbol: zend_strpprintf`

`zend_strpprintf` was introduced in 7.2

Perhaps simpler to raise minimal supported version to 7.3 ?

especially for EOL versions not covered by CI

**Comment by remicollet** [comment]
If you want to fix this issue, I have already a patch for 7.2, but forgive for older versions
[0001-add-zval_get_tmp_string-for-PHP-7.3.txt](https://github.com/user-attachments/files/17516939/0001-add-zval_get_tmp_string-for-PHP-7.3.txt)

**Comment by arnaud-lb** [comment]
Thank you! Fixed in https://github.com/arnaud-lb/php-rdkafka/commit/6c1a72c93812bf53515ff9293e3ab4849c09b282.

I've decided to preserve php 7.0 compatibility in 6.x for now. This branch is now bug fix only. Branch 7.x drops support for php < 8.1.

**Comment by remicollet** [comment]
> I've decided to preserve php 7.0 compatibility in 6.x for now. 

Fine

And I confirm the patch is OK (tested against 7.0, 7.1 and 7.2 on RHEL-8)
