### ISSUE TITLE
Merge PHP5/7 branches, or version separately

### ISSUE THREAD

**Issue by dzuelke** [php-rdkafka/php-rdkafka#58]
The current practice of having two different tags of the same version for PHP 5 and PHP 7 has the obvious fault of not allowing a PECL release for both.

Either the codebases should be merged into one (like some extensions do), or e.g. version 1.x should be for PHP 5, and 2.x for PHP 7 (like other extensions do). Option #1 is the better choice IMO :)

**Comment by arnaud-lb** [comment]
Merging codebases would be awesome, however it seems difficult to do properly. https://github.com/flaupretre/pecl-compat or https://github.com/sgolemon/zeval may help on that.

Shorter-term, I would rather publish separate versions on PECL.

**Comment by arnaud-lb** [comment]
Released pecl version 2.x for PHP 7, version 1.x for PHP 5: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.installation.pecl.html
