### ISSUE TITLE
configure --includedir not work?

### ISSUE THREAD

**Issue by iyaozhen** [php-rdkafka/php-rdkafka#62]
configure:

```
./configure --with-php-config=/home/work/odp/bin/php-config --includedir=/home/work/libkafka/include --libdir=/home/work/libkafka/lib
```

but:

```
checking for librdkafka/rdkafka.h" in default path... not found
configure: error: Please reinstall the rdkafka distribution
```

rdkafka.h in this dir:

```
# ls -l /home/work/libkafka/include/librdkafka/
-rwxr-xr-x  1 work root 53740 Jul  6 15:37 rdkafkacpp.h
-rwxr-xr-x  1 work root 77704 Jul  6 15:37 rdkafka.h
```

**Comment by arnaud-lb** [comment]
Hi @iyaozhen,

`configure` is searching for `include/librdkafka/rdkafka.h` in the directory specified in `--with-rdkafka` (or in /usr and /usr/local by default).

I think that `--includedir` and `--libdir` specify the directories where PHP's include files and library files will be installed (not directories where the configure or build will search for include files or libraries).

**Comment by shengbinxu** [comment]
I hava same problem, as @arnaud-lb said, you command should be:
`
./configure --with-php-config=/home/work/odp/bin/php-config --with-rdkafka=/home/work/libkafka/
`
have to be aware of is the value of "--with-rdkafka" is the installed root path。

https://stackoverflow.com/questions/3958904/how-to-specify-include-directory-for-configure-script

**Comment by bingtanghulu** [comment]
because you need another package [librdkafka](https://github.com/edenhill/librdkafka),you should install [librdkafka](https://github.com/edenhill/librdkafka) first

- $ git clone https://github.com/edenhill/librdkafka.git
- $ cd librdkafka
- $ ./configure
- $ make && make install

this way can resolve your problem

**Comment by snriud** [comment]
I have the same problem, I installed librdkafka and librdkafka-devel firstly and solved the problem.
or you can follow @bingtanghulu advice, compile it from source, it will also solve the problem.
