### ISSUE TITLE
producer can not produce message when the loop count > 25

### ISSUE THREAD

**Issue by jiweibin** [php-rdkafka/php-rdkafka#63]
hi,arnaud-lb：

  My producer can not produce message to kafka broker when the look count > 25.
- PHP version:5.5.35 on CentOS
- librdkafka version:0.9.1
- php-rdkfaka version:master branch

this is my test script:

```
<?php

$conf = new RdKafka\Conf();
$conf->set('queue.buffering.max.ms','600000');
$kafka = new RdKafka\Producer($conf);
$kafka->setLogLevel(LOG_DEBUG);
$kafka->addBrokers("172.16.10.236:9092");

$topicConf = new RdKafka\TopicConf();
$topic = $kafka->newTopic("topic1");

$i = 1;
while ($i <= 25) {
    $topic->produce(0, 0, "Message $i");
    $i++;
}

?>
```

then run the consume shell,i can not see any message from the topic "topic1":

`bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic topic1 --from-beginning`

but if i adjust the loop count to 20,it works.

i wonder why the different loop count can have different performance. is the produce queue related?

**Comment by arnaud-lb** [comment]
Hi @jiweibin 

Could you try with the later master and see it you still have the same problem ?
