### ISSUE TITLE
unknown type name 'rd_kafka_metadata_t'

### ISSUE THREAD

**Issue by gnh1201** [php-rdkafka/php-rdkafka#65]
Thank you for creating a ticket!

Before submitting the ticket, please consider asking a question on the
Gitter channel at https://gitter.im/arnaud-lb/php-rdkafka

If you are reporting a bug, please provide the following informations:
- PHP version: 5.x
- librdkafka version: latest (librdkafka-dev)
- php-rdkfaka version: git-latest

> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /usr
> checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
> checking for PHP extension directory... /usr/lib/php5/20121212
> checking for PHP installed headers prefix... /usr/include/php5
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... no
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
> checking for gawk... gawk
> checking for rdkafka support... yes, shared
> checking for librdkafka/rdkafka.h" in default path... found in /usr
> checking for rd_kafka_new in -lrdkafka... yes
> checking for rd_kafka_msg_partitioner_consistent in -lrdkafka... no
> configure: WARNING: no rd_kafka_msg_partitioner_consistent, the consistent partitioner will not be available
> checking how to print strings... printf
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking for fgrep... /bin/grep -F
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... yes
> checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking for gawk... (cached) gawk
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for sysroot... no
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC -DPIC
> checking if cc PIC flag -fPIC -DPIC works... yes
> checking if cc static flag -static works... yes
> checking if cc supports -c -o file.o... yes
> checking if cc supports -c -o file.o... (cached) yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> configure: creating ./config.status
> config.status: creating config.h
> config.status: executing libtool commands
> running: make
> /bin/bash /tmp/pear/temp/pear-build-rootCIFrHu/rdkafka-0.9.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/rdkafka -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootCIFrHu/rdkafka-0.9.1/include -I/tmp/pear/temp/pear-build-rootCIFrHu/rdkafka-0.9.1/main -I/tmp/pear/temp/rdkafka -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/rdkafka/rdkafka.c -o rdkafka.lo
> libtool: compile:  cc -I. -I/tmp/pear/temp/rdkafka -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootCIFrHu/rdkafka-0.9.1/include -I/tmp/pear/temp/pear-build-rootCIFrHu/rdkafka-0.9.1/main -I/tmp/pear/temp/rdkafka -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/rdkafka/rdkafka.c  -fPIC -DPIC -o .libs/rdkafka.o
> In file included from /tmp/pear/temp/rdkafka/rdkafka.c:32:0:
> /tmp/pear/temp/rdkafka/metadata.h:20:1: error: unknown type name 'rd_kafka_metadata_t'
>  void kafka_metadata_init(zval _return_value, const rd_kafka_metadata_t *metadata TSRMLS_DC);
>  ^
> /tmp/pear/temp/rdkafka/rdkafka.c:73:5: error: unknown type name 'rd_kafka_queue_t'
>      rd_kafka_queue_t    *rkqu;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Kafka_metadata':
> /tmp/pear/temp/rdkafka/rdkafka.c:837:5: error: unknown type name 'rd_kafka_metadata_t'
>      const rd_kafka_metadata_t *metadata;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Kafka_newQueue':
> /tmp/pear/temp/rdkafka/rdkafka.c:900:5: error: unknown type name 'rd_kafka_queue_t'
>      rd_kafka_queue_t *rkqu;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c:913:10: warning: assignment makes pointer from integer without a cast [enabled by default]
>      rkqu = rd_kafka_queue_new(intern->rk);
>           ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Queue_consume':
> /tmp/pear/temp/rdkafka/rdkafka.c:1250:13: warning: assignment makes pointer from integer without a cast [enabled by default]
>      message = rd_kafka_consume_queue(intern->rkqu, timeout_ms);
>              ^
> In file included from /usr/include/php5/main/php.h:404:0,
>                  from /tmp/pear/temp/rdkafka/rdkafka.c:25:
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zm_startup_rdkafka':
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:19: error: 'RD_KAFKA_RESP_ERR__ISR_INSUFF' undeclared (first use in this function)
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>                    ^
> /usr/include/php5/Zend/zend_constants.h:41:103: note: in definition of macro 'REGISTER_LONG_CONSTANT'
>  #define REGISTER_LONG_CONSTANT(name, lval, flags)  zend_register_long_constant((name), sizeof(name), (lval), (flags), module_number TSRMLS_CC)
>                                                                                                        ^
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:5: note: in expansion of macro 'COPY_CONSTANT'
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:19: note: each undeclared identifier is reported only once for each function it appears in
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>                    ^
> /usr/include/php5/Zend/zend_constants.h:41:103: note: in definition of macro 'REGISTER_LONG_CONSTANT'
>  #define REGISTER_LONG_CONSTANT(name, lval, flags)  zend_register_long_constant((name), sizeof(name), (lval), (flags), module_number TSRMLS_CC)
>                                                                                                        ^
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:5: note: in expansion of macro 'COPY_CONSTANT'
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>      ^
> make: *_\* [rdkafka.lo] 오류 1
> ERROR: `make' failed
> root@ubuntu:/opt/php-rdkafka# pecl install channel://pecl.php.net/rdkafka-alpha
> downloading rdkafka-0.9.1.tgz ...
> Starting to download rdkafka-0.9.1.tgz (22,978 bytes)
> ........done: 22,978 bytes
> 16 source files, building
> running: phpize
> Configuring for:
> PHP Api Version:         20121113
> Zend Module Api No:      20121212
> Zend Extension Api No:   220121212
> building in /tmp/pear/temp/pear-build-rootKxmhXr/rdkafka-0.9.1
> running: /tmp/pear/temp/rdkafka/configure
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /usr
> checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usrext/date/lib
> checking for PHP extension directory... /usr/lib/php5/20121212
> checking for PHP installed headers prefix... /usr/include/php5
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... no
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate
> checking for gawk... gawk
> checking for rdkafka support... yes, shared
> checking for librdkafka/rdkafka.h" in default path... found in /usr
> checking for rd_kafka_new in -lrdkafka... yes
> checking for rd_kafka_msg_partitioner_consistent in -lrdkafka... no
> configure: WARNING: no rd_kafka_msg_partitioner_consistent, the consistent parti
> checking how to print strings... printf
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking for fgrep... /bin/grep -F
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... yes
> checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-li
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format.
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking for gawk... (cached) gawk
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for sysroot... no
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC -DPIC
> checking if cc PIC flag -fPIC -DPIC works... yes
> checking if cc static flag -static works... yes
> checking if cc supports -c -o file.o... yes
> checking if cc supports -c -o file.o... (cached) yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libra
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> configure: creating ./config.status
> config.status: creating config.h
> config.status: executing libtool commands
> running: make
> /bin/bash /tmp/pear/temp/pear-build-rootKxmhXr/rdkafka-0.9.1/libtool --mode=compXr/rdkafka-0.9.1/include -I/tmp/pear/temp/pear-build-rootKxmhXr/rdkafka-0.9.1/maphp5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/e
> libtool: compile:  cc -I. -I/tmp/pear/temp/rdkafka -DPHP_ATOM_INC -I/tmp/pear/tekafka-0.9.1/main -I/tmp/pear/temp/rdkafka -I/usr/include/php5 -I/usr/include/phpinclude/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/rdkafka/rdkaf
> In file included from /tmp/pear/temp/rdkafka/rdkafka.c:32:0:
> /tmp/pear/temp/rdkafka/metadata.h:20:1: error: unknown type name 'rd_kafka_metad
>  void kafka_metadata_init(zval *return_value, const rd_kafka_metadata_t *metadat
>  ^
> /tmp/pear/temp/rdkafka/rdkafka.c:73:5: error: unknown type name 'rd_kafka_queue_
>      rd_kafka_queue_t    *rkqu;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Kafka_metadata':
> /tmp/pear/temp/rdkafka/rdkafka.c:837:5: error: unknown type name 'rd_kafka_metad
>      const rd_kafka_metadata_t *metadata;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Kafka_newQueue':
> /tmp/pear/temp/rdkafka/rdkafka.c:900:5: error: unknown type name 'rd_kafka_queue
>      rd_kafka_queue_t *rkqu;
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c:913:10: warning: assignment makes pointer from
>      rkqu = rd_kafka_queue_new(intern->rk);
>           ^
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zim_RdKafka__Queue_consume':
> /tmp/pear/temp/rdkafka/rdkafka.c:1250:13: warning: assignment makes pointer from
>      message = rd_kafka_consume_queue(intern->rkqu, timeout_ms);
>              ^
> In file included from /usr/include/php5/main/php.h:404:0,
>                  from /tmp/pear/temp/rdkafka/rdkafka.c:25:
> /tmp/pear/temp/rdkafka/rdkafka.c: In function 'zm_startup_rdkafka':
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:19: error: 'RD_KAFKA_RESP_ERR__ISR_INSUFF'
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>                    ^
> /usr/include/php5/Zend/zend_constants.h:41:103: note: in definition of macro 'RE
>  #define REGISTER_LONG_CONSTANT(name, lval, flags)  zend_register_long_constant(
> 
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:5: note: in expansion of macro 'COPY_CONST
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>      ^
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:19: note: each undeclared identifier is re
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>                    ^
> /usr/include/php5/Zend/zend_constants.h:41:103: note: in definition of macro 'RE
>  #define REGISTER_LONG_CONSTANT(name, lval, flags)  zend_register_long_constant(
> 
> /tmp/pear/temp/rdkafka/rdkafka.c:1475:5: note: in expansion of macro 'COPY_CONST
>      COPY_CONSTANT(RD_KAFKA_RESP_ERR__ISR_INSUFF);
>      ^
> make: **\* [rdkafka.lo] Error 1
> ERROR: `make' failed

**Comment by arnaud-lb** [comment]
Hi!

It seems that the `./configure` found the file `librdkafka/rdkafka.h` in `/usr/include`, but that the file doesn't contain the declaration of the type `rd_kafka_metadata_t`.

You should check the content of the file `/usr/include/librdkafka/rdkafka.h`.

Als try installing librdkafka again.

**Comment by elnur** [comment]
Hitting the same on Ubuntu 14.04.

**Comment by fredsted** [comment]
Me too. My conclusion is that php-rdkafka can't be installed on Ubuntu 14.04.
