### ISSUE TITLE
Produce Topic variable destroy time

### ISSUE THREAD

**Issue by shaunxq** [php-rdkafka/php-rdkafka#66]
Hello,

a simple produce example cost me at least 150ms.
message is quickly send to broker, but the program is ended about 150ms after.
i tried to 

unset($rk);
unset($topic);

the time cost in that
could you tell me the point in this case.
(sorry about my terrible english)

$rk = new RdKafka\Producer();
$rk->addBrokers("127.0.0.1:9092");
$topic = $rk->newTopic('test_topic');
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'test');

**Comment by arnaud-lb** [comment]
Hello,

Reducing the value of the `socket.blocking.max.ms` config variable should reduce shutdown time.

This setting is used as a sleep time in this loop that checks for termination: https://github.com/edenhill/librdkafka/blob/0ff40cc08bc6c3ba35cc5205c91131618a58a0c7/src/rdkafka.c#L975
