### ISSUE TITLE
Trigger error callback in produce method

### ISSUE THREAD

**Issue by white-bear** [php-rdkafka/php-rdkafka#68]
Hello!
My environment:
    PHP version: 5.6.16
    librdkafka version: 0.9.1
    php-rdkfaka version: master

Problem description:
1. set error callback via RdKafka\Conf::setErrorCb
2. create producer
3. start producing messages
4. stop kafka server
5. callback doesn't receive any error

Problem solving:
We need to call rd_kafka_poll right after rd_kafka_produce.
This method will trigger error callback and message delivery report callback (this is described in librdkafka INTRODUCTION.md, threads and callbacks section).
If you look at librdkafka produce examples (e.g. examples/rdkafka_example.c), you will see, how to properly produce messages and trigger error callback after producing.
Screenshot with described section is attached.
![kafka_poll](https://cloud.githubusercontent.com/assets/1451319/18310980/639c46a2-750a-11e6-8b8d-442cfc393d9b.png)

Thanks!

**Comment by arnaud-lb** [comment]
Hi!

Thanks for your report.

The RdKafka\Producer class has a poll() method allowing your to call rd_kafka_poll() from PHP: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.poll.html

php-rdkafka is trying to remain as close as possible to librdkafka's behavior, and I don't think I should add implicit rd_kafka_poll() calls. Instead, the user should call $producer->poll() eventually.

**Comment by white-bear** [comment]
This behavior is a bit confusing. As a common user I don't know, what I must call this method after producing a message. Some usage examples should fix this ;)
For now in produce example not a word about this.

**Comment by arnaud-lb** [comment]
You are right, documentation and examples need updates

**Comment by nick-zh** [comment]
@white-bear @arnaud-lb doc was updated, can be closed
