### ISSUE TITLE
Can't find how to set a number of partitions to a topic

### ISSUE THREAD

**Issue by NastasiaSaby** [php-rdkafka/php-rdkafka#69]
Hi,
We don't success to set a number of partitions to topic.
We try different things, but without success.

Could you give an example please?

**Comment by arnaud-lb** [comment]
Hi,

This is done during topic creation, using Kafka's command line tools (the `--partitions` argument to the `kafka-topics.sh` tool).

**Comment by NastasiaSaby** [comment]
Ok thank you very much.

So,

Can I ask 2 things : 
- You create topics with their partitions only from the kafka command line, do you?
- For what do you use "TopicPartition"? Its use is not to create partitions, I guess, but so what it is its utility?
