### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by white-poto** [php-rdkafka/php-rdkafka#7]
/data/software/php-rdkafka/rdkafka.c: In function ‘zim_RdKafka__TopicConf_setPartitioner’:
/data/software/php-rdkafka/rdkafka.c:1207: error: ‘rd_kafka_msg_partitioner_consistent’ undeclared (first use in this function)
/data/software/php-rdkafka/rdkafka.c:1207: error: (Each undeclared identifier is reported only once
/data/software/php-rdkafka/rdkafka.c:1207: error: for each function it appears in.)
make: **\* [rdkafka.lo] Error 1

# cat /proc/version 
Linux version 2.6.32-279.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Fri Jun 22 12:19:21 UTC 2012

**Comment by arnaud-lb** [comment]
Hi @huyanping 

`rd_kafka_msg_partitioner_consistent` has been added in a very recent version of librdkafka, please make sure that you have the lastest version.

We should compile this conditionally.

**Comment by white-poto** [comment]
Hi @arnaud-lb 
  I am sure that I used the lastest version.  
  librdkafka-0.8.6.

**Comment by arnaud-lb** [comment]
Hi @huyanping,

Apparently `rd_kafka_msg_partitioner_consistent` exists only in master for now. I've made sure that the extension can be built without `rd_kafka_msg_partitioner_consistent` (you will have to re-run phpize and ./configure).
