### ISSUE TITLE
Not able to push message with producer.

### ISSUE THREAD

**Issue by t3chboy** [php-rdkafka/php-rdkafka#70]
I am able to connect to my kafka broker and create topic, but not able to store messages via producer.
Following is my code : 

```
$conf = new RdKafka\Conf();
//$conf->set('debug','topic');
$conf->set('delivery.report.only.error','true');
$rd = new RdKafka\Producer($conf);

$c = $rd->addBrokers("192.168.0.XX:9092");

//created topics for all orders data
$topic = $rd->newTopic("order_datas");

//start loop for data
for($i=0;$i<=10;$i++){
    $msg = "msg_order_id_"+$i;
    $message = [
    'type' => 'account-created',
    'id' => $msg
];
    $payload = json_encode($message);

    $a = $topic->produce(RD_KAFKA_PARTITION_UA, 0, $payload,0);
}
//consumer started
$crk = new RdKafka\Consumer();
$crk->setLogLevel(LOG_DEBUG);
$rd->addBrokers("192.168.0.XX:9092");
$ctopic = $crk->newTopic("order_datas");
$ctopic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);
$ms = $ctopic->consume(0,10000);
var_dump($ms);
```
- PHP version: PHP 5.5.9-1ubuntu4.19
- librdkafka version: 0.9.1
- php-rdkfaka version: 0.9.1-php5

**Comment by arnaud-lb** [comment]
Hi!

Here are a few possible causes:
- You are consuming the partition 0, but you are producing on an undefined partition (`RD_KAFKA_PARTITION_UA`). If the topic has more than one partition, it's possible that messages a produced to a partition different than 0.
- The producer is asynchronous, and it is possible that at the time you start consuming, the message is not produced yet. Try running the consumer and the producer separately, in different programs.

**Comment by t3chboy** [comment]
How can i get to know whether producer is adding data or not? 
How can i get some acknowledgement from broker whether stored or not?

**Comment by arnaud-lb** [comment]
You can set a delivery report callback with Conf::setDrMsgCb: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-conf.setdrmsgcb.html (remove the delivery.report.only.error setting too). You might need to call `$producer->poll()` from time to time.

**Comment by t3chboy** [comment]
thnx for the help, but this is what i wrote but didn’t got any message.

```
$conf = new RdKafka\Conf();
//$conf->set('debug','topic');
$conf->set('delivery.report.only.error','true');
$rd = new RdKafka\Producer($conf);

$c = $rd->addBrokers("192.168.0.97:9092,192.168.0.74:9092,192.168.0.75:9092");

//created topics for all orders data
$topic = $rd->newTopic("new_order_data");

//start loop for data
for($i=0;$i<=200;$i++){
    $msg = "msg_order_id_".$i;
    $message = [
    'type' => 'new-created_'.$msg,
    'id' => $i
];
    $payload = json_encode($message);

    $topic->produce(0, 0, $payload,0);
}

$rd->poll(1000);

$conf->setDrMsgCb(function (RdKafka\Kafka $kafka, RdKafka\Message $message) {
    echo "12";
if ($message->err) {
    echo "failed";
    echo $message->errstr(), "\n";
} else {
   echo "success";
}

});
```

**Comment by arnaud-lb** [comment]
Could you add `$conf->set('debug','all');` and post what you are seeing ?

**Comment by t3chboy** [comment]
Have changed to single broker 192.168.0.97:9092 from multiple broker.
[kafka_config_log.txt](https://github.com/arnaud-lb/php-rdkafka/files/463997/kafka_config_log.txt)

**Comment by arnaud-lb** [comment]
Messages seem to have been delivered successfully:

```
%7|1473426255.117|RECV|rdkafka#producer-1| kafka1.mystore.corp:9092/1: Received ProduceResponse (v1, 42 bytes, CorrId 2, rtt 1.69ms)
%7|1473426255.117|TOPPAR|rdkafka#producer-1| kafka1.mystore.corp:9092/1: new_order_data [0] 0+0 msgs
%7|1473426255.117|MSGSET|rdkafka#producer-1| kafka1.mystore.corp:9092/1: MessageSet with 3 message(s) delivered
```

Are you able to see the messages when using kafka-console-consumer.sh ?

```
kafka/bin/kafka-console-consumer.sh --zookeeper x.x.x.x --topic streamables_alert_changed --from-beginning
```
