### ISSUE TITLE
ProducerTopic produce with key null

### ISSUE THREAD

**Issue by NastasiaSaby** [php-rdkafka/php-rdkafka#74]
When key is null when publishing a message, we've got _Uncaught TypeError: RdKafka\ProducerTopic::produce() expects parameter 4 to be string, null given_.

**Comment by arnaud-lb** [comment]
Hi @NastasiaSaby

Which version of PHP and php-rdkafka are you using ?

**Comment by NastasiaSaby** [comment]
Hi @arnaud-lb, our version of PHP is 7.0.10 and our version of php-rdkafka is 0.9.1.0.

**Comment by arnaud-lb** [comment]
Could you try with php-rdkafka 2.x ?

**Comment by NastasiaSaby** [comment]
Thank you. It works.

**Comment by NastasiaSaby** [comment]
When using "declare(strict_types = 1);", we still have :

_Uncaught TypeError: RdKafka\ProducerTopic::produce() expects parameter 4 to be string._

rdkafka support => enabled
version => 2.0.1
build date => Dec 12 2016 10:13:42
librdkafka version (runtime) => 0.9.2-112-g7f12b7
librdkafka version (build) => 0.9.3.0
Kafka => 0.10.1
PHP => 7

Code that does not work: 
```php
<?php

declare(strict_types = 1);

$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("127.0.0.1");

$topic = $rk->newTopic("batman");

$topic->produce(RD_KAFKA_PARTITION_UA, 0, "Bat", null);
```

**Comment by arnaud-lb** [comment]
Fixed, thanks!
