### ISSUE TITLE
How to close a consumer after consuming

### ISSUE THREAD

**Issue by t3chboy** [php-rdkafka/php-rdkafka#75]
How do i close the consumer after subscribing it.  
Following is how i am subscribing it.
Also consumerstop is function of this class RdKafka\ConsumerTopic  so can i use it in below code,because it need partition id as parameter for consumerstop() and while consuming i am not knwing from which partition i m consuming.

```
$consumer = new \RdKafka\KafkaConsumer($conf);
// Subscribe to topic
$consumer->subscribe(['register1']);
$message = $consumer->consume(100);
```

**Comment by arnaud-lb** [comment]
Hi @t3chboy 

Using the unsubscribe function should do what you want: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-kafkaconsumer.unsubscribe.html

If you just want to unsubscribe from one topic, call subscribe() with all the topics you want to consume, but the one you don't want to consume anymore.

**Comment by TiMESPLiNTER** [comment]
@arnaud-lb `unsubscribe` method never calls the function [`rd_kafka_consumer_close`](https://github.com/edenhill/librdkafka/blob/52c2005eb323b5876646ac0136caa12e225fdb07/src/rdkafka.c#L2109).

So I have the feeling that a `RdKafkaConsumer` never closes connection properly by calling `unsubscribe`. The only position I've found a call to this method is in the `STORE_OBJECT` call: https://github.com/arnaud-lb/php-rdkafka/blob/7f8dc9a7da0cc770902c157cb374efbacc067446/kafka_consumer.c#L55

Can you explain the reason for this. I'm not that experienced with PHP extension code so I can't really figure out when this function gets called but what I've read so far only a call to this method will close the connection from the consumer to the broker.

My consumers are idling pretty long on the broker from what I can see in the logs. Even after I `unset()` the consumer.

**Comment by arnaud-lb** [comment]
Hi @TiMESPLiNTER 

rd_kafka_consumer_close is called when the RdKafka\KafkaConsumer() instance is destroyed. The instance is destroyed when it's not referenced anymore, either by user code or by other php-rdkafka object instance like a RdKafka\Topic.

**Comment by TiMESPLiNTER** [comment]
@arnaud-lb thanks for your response. Is there a specific reason why there is no `close` method available for the `RdKafka\KafkaConsumer`? I guess my consumers never disconnect because somewhere there's still a reference pointing to it. So it would be great to be able to "force" close it with a method call.
