### ISSUE TITLE
High level consumer,where are offest stored.

### ISSUE THREAD

**Issue by t3chboy** [php-rdkafka/php-rdkafka#77]
hi,
I am using this high level consumer and this is how i consume and commit,

```
$conf->setDefaultTopicConf($topicConf);
$consumer = new \RdKafka\KafkaConsumer($conf);
// Subscribe to topic
$consumer->subscribe(['registration']);
//consuming
$message = $consumer->consume(1000);
//committing
$consumer->commit($message);

```

In the above case i am explicitly not defining this property `offset.store.method` , than where are offsets stored in zookepper or broker,
if in broker than in all brokers defined or any specific.

Also how do i get last current fetched message offset.

-     PHP version: PHP 5.5.9-1ubuntu4.19
-     librdkafka version: 0.9.1
-     php-rdkfaka version: 0.9.1-php5

**Comment by arnaud-lb** [comment]
Hi

In your librdkafka version, offset.store.method defaults to "broker". Offsets are stored in the `__consumer_offsets` topic on the broker.
