### ISSUE TITLE
Find last stored commited offset.

### ISSUE THREAD

**Issue by t3chboy** [php-rdkafka/php-rdkafka#78]
Hi,

```
        $conf->set('group.id','commonqueue2');
        $conf->set('offset.store.method', 'broker');

        $rk = new \RdKafka\Consumer($conf);
        $rk->addBrokers($kafka_servers);

        $topicConf = new \RdKafka\TopicConf();

        $topicConf->set('auto.commit.interval.ms',1000);
        $topicConf->set('offset.store.method', 'broker');
        $topicConf->set('auto.offset.reset', 'smallest');

        $topic = $rk->newTopic("registration17", $topicConf);

        $topic->consumeStart(0,RD_KAFKA_OFFSET_STORED); 

        while (true) {

            $message = $topic->consume(0,1000);

            //store offset to broker
            $topic->offsetStore($message->partition,$message->offset);

            $message_offset = $message->offset;
            echo $message_data = $message->payload;

        }//end of while loop
```

In the above program how can i find the last stored offset before executing following code
`$topic->consumeStart(0,RD_KAFKA_OFFSET_STORED);    
`

```
PHP version: PHP 5.5.9-1ubuntu4.19
librdkafka version: 0.9.1
php-rdkfaka version: 0.9.1-php5
```

**Comment by t3chboy** [comment]
Hi @arnaud-lb  any updates for above issue,i want to implement this but got stuck due to above issue.
Kindly help.

**Comment by t3chboy** [comment]
Hey @arnaud-lb  is there some method in here like position() method in java to get current  offset position.

**Comment by arnaud-lb** [comment]
Hi @t3chboy 

librdkafka has a `rd_kafka_committed()` function, but it's not implemented in php-rdkafka yet.

I think it could be added as `RdKafka\Consumer::committed([]RdKafka\TopicPartition $partitions, $timeout_ms)`

**Comment by t3chboy** [comment]
@arnaud-lb  but how to use it, if i am using it as following, i get error

```
$rk = new \RdKafka\Consumer($conf);
$rd = new \RdKafka\TopicPartition("registration22", 0);
$a = $rk->committed($rd, 100);
print_r($a);
```

or

```
$rk = new \RdKafka\Consumer($conf);
$rd = new \RdKafka\TopicPartition("registration22", 0);
$a = $rk->committed(0 100);
print_r($a);
```

Error : Segmentation fault (core dumped);

**Comment by remizyaka** [comment]
Hey @tPl0ch 
any news on implementing  rd_kafka_query_watermark_offsets in php_rdkafka?

**Comment by june6868** [comment]
@t3chboy where can find the function "committed"?

**Comment by frops** [comment]
Hello, @arnaud-lb. 
Is there news about getting information regarding **offset** and **lag**?
Thank you.

**Comment by nick-zh** [comment]
I think since `Kafka::queryWatermarkOffsets` and `KafkaConsumer::getCommittedOffsets` are now exposed, this can be closed @arnaud-lb
