### ISSUE TITLE
How to catch error info and not to output to the stdout directly?

### ISSUE THREAD

**Issue by calixwu** [php-rdkafka/php-rdkafka#81]
- PHP version: php5.6.22
- librdkafka version: 0.9.0.99
- php-rdkfaka version: master

I've got a problem similar with the commits in issue [php7 process dont die while failing to connect to broker](https://github.com/arnaud-lb/php-rdkafka/issues), but not with php7:
I call "produce" in my code, and just want to handle the errors in case it happens, but I don't know how to catch the errors.

Here's my ugly code:

```
        $kafkaConf = new \RdKafka\Conf();
        $kafkaConf->setErrorCb(array($this, 'produceErrorCallback'));

        $rk = new \RdKafka\Producer($kafkaConf);
        $rk->setLogLevel(LOG_DEBUG);
        $rk->addBrokers("127.0.0.1:9999");

        $topicConf = new \RdKafka\TopicConf();
        $topicConf->set("message.timeout.ms", 3000);
        $topic = $rk->newTopic("myTopic", $topicConf);

        try{
            $result = true;
            $topic->produce(RD_KAFKA_PARTITION_UA, 0, $payload);
            $rk->poll(3000);
        }catch (\Exception $e){
            var_dump($e);
            $result = false;
        }
```

If I add the wrong brokers on purpose, and I thought I would get some errors because it would connect timed out after 3000ms, but I got nothing, my error-callback function nor catch-exception codes.

However, when I set the message.timeout.ms very long, such as 500000ms, it does trigger my error-callback function. But the awful part is, it also output the error messages  to the stdout directly,  which means it will display on the console or the browser and I don't know how to turn it off.

So, My problems:
1. Why it does not show any errors when I set  message.timeout.ms 3000ms and set the broker to a wrong address?
2. How to make it not to output errors to the stdout directly?

Thanks~

**Comment by calixwu** [comment]
I just solved one of my problems "2. How to make it not to output errors to the stdout directly?" with:
`$rk->setLogger(RD_KAFKA_LOG_SYSLOG);`

**Comment by mogmismo** [comment]
I also have issue number 1 from the original post, seems to be ignoring  message.timeout.ms completely, and running to PHP execution time limit.  I've also set $conf->set('socket.max.fails', 1); so that it isn't quietly trying over and over, multiplying my timeout.  If the cluster isn't available for any reason, we just wait.

Is there any way to trigger an exception callback if the initial socket connection fails?  I don't want to put this into production without being able to gracefully fail.

**Comment by wangyouw** [comment]
get the same problem too

**Comment by fredsted** [comment]
Anyone found a solution to this? @arnaud-lb?

**Comment by nick-zh** [comment]
I was not able to reproduce this on a more current setup:
PHP version: 7.3.7
librdkafka version: 1.0.1-r1
php-rdkfaka version: 3.1.2
System: alpine-3.10

I ran the same code from @calixwu , i just added the callback directly, so anybody can run this code and try to reproduce it:
```
<?php

declare(strict_types=1);

use RdKafka\Conf;
use RdKafka\Producer;
use RdKafka\TopicConf;

$kafkaConf = new Conf();
$kafkaConf->setErrorCb(function (Producer $producer, int $errorCode, string $errorMsg) {
    throw new \RuntimeException($errorMsg, $errorCode);
});

$rk = new Producer($kafkaConf);
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("127.0.0.1:9999");

$topicConf = new TopicConf();
$topicConf->set("message.timeout.ms", "500000");
$topic = $rk->newTopic("myTopic", $topicConf);

try{
    $result = true;
    $topic->produce(RD_KAFKA_PARTITION_UA, 0, 'test');
    $rk->poll(3000);
}catch (\Exception $e){
    var_dump($e);
    $result = false;
}
```

For me it does not matter if i set the timeout to `3000` or `500000` i only get the output from the error callback (the exception) and i get nothing in my stdout.
When i omit the throw, i get no output at all, which is the behaviour expected.

Please let me know if this still persists @calixwu @mogmismo @wangyouw @fredsted
