### ISSUE TITLE
rdkafka-master/rdkafka.c:54: error: redefinition of typedef ‘kafka_object’

### ISSUE THREAD

**Issue by goldlife1981** [php-rdkafka/php-rdkafka#82]
when i make rdkafka  , i get   "rdkafka-master/rdkafka.c:54: error: redefinition of typedef ‘kafka_object’" error.

how to fix
- PHP version:php7.0.1
- librdkafka version:0.9.2
- php-rdkfaka version:master

**Comment by arnaud-lb** [comment]
Hi @goldlife1981 

I believe that it's fixed in the common-code branch, could you try it ? https://github.com/arnaud-lb/php-rdkafka/tree/common-code
