### ISSUE TITLE
Does php-rdkafka support for kafka consumer group?

### ISSUE THREAD

**Issue by JackDrogon** [php-rdkafka/php-rdkafka#84]
Does php-rdkafka support for kafka consumer group? How can I use php-rdkafka for kafka consumer group?

**Comment by arnaud-lb** [comment]
Hi @JackDrogon 

php-rdkafka does support consumer groups, when compiled against librdkafka >= 0.9. See the high-level consumer example here: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-high-level-consumer.html
