### ISSUE TITLE
Consumer Read Is NULL

### ISSUE THREAD

**Issue by jogucc** [php-rdkafka/php-rdkafka#85]
PRODUCE code like thist:

            $kafka = new RdKafka\Producer();
            $kafka->setLogLevel(LOG_DEBUG);
            $rst = $kafka->addBrokers("10.123.11.10:9092/alphakafka");

            $topic = $kafka->newTopic("topic_test");
            $rst = $topic->produce(RD_KAFKA_PARTITION_UA, 0, "jogu test11");
When I try to consume ,it's NULL,please help me to find why,thanks a lot!!

            $rk = new RdKafka\Consumer();
            $rst = $rk->addBrokers("10.123.11.10:9092/alphakafka");
            $topic = $rk->newTopic("topic_test");
            $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);
while (true) {
        $msg = $topic->consume(0,1000*60);
        var_dump($msg);
}

 * PHP version: 
 * librdkafka version: 
 * php-rdkfaka version: /kafka_2.10-0.9.0.1

**Comment by jogucc** [comment]
It seems I connect to  10.123.11.10:9092/bootstrap:  I want to connect to  10.123.11.10:9092/alphakafka

**Comment by jogucc** [comment]
when I use shell to consume like this:
bin/kafka-console-consumer.sh --zookeeper 10.49.xx.xx:2181/alphakafka --topic test_topic --from-beginning
I can read my msg,when I use rdkafka to consume like this:
        $rk = new RdKafka\Consumer($conf);
        $rk->setLogLevel(LOG_DEBUG);
        $rk->addBrokers("10.49.xx.xx:2181/alphakafka");
        $topic = $rk->newTopic("test_topic ");
        $msg = $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);

```
    while (true) {
        $msg = $topic->consume(0,1000*60);
        var_dump($msg);
    } 
```

The msg is   NULL,Why??

@Arnaud Le Blanc

**Comment by arnaud-lb** [comment]
Null means that consume() timed out (although sometimes it times out faster than the provided value).

You should call it again.
