### ISSUE TITLE
Memory management error in KafkaConsumer::__construct()

### ISSUE THREAD

**Issue by fgm** [php-rdkafka/php-rdkafka#88]
* PHP version: PHP 7.0.12 (cli) (built: Oct 14 2016 09:56:59) ( NTS )
 * librdkafka version: (runtime) => 0.9.1 / (build) => 0.9.1.0
 * php-rdkfaka version: 2.0.0 / build date	Oct 28 2016 15:59:13

```php
<?php
$conf = new Conf();
$conf->set('metadata.broker.list', '127.0.0.1:9092');
$consumer = new RdKafka\KafkaConsumer($conf);
```
Expected: get an instance with an "invalid" indication of some sort, or catch an exception because no consumer group was set.

Actual: script exits with:
```
php(38279,0x7fffa5de73c0) malloc: *** error for object 0x7ff3dbe41bc0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```
Workaround: ensure settings `group.id` in the conf.

**Comment by fgm** [comment]
Looking into `kafka_consumer.c`, it looks like the problem occurs because, at line 148, the ctor calls `rd_kafka_conf_destroy(conf)` because the call to `has_group_id(conf)` returned 0, but `conf` may not have been allocated during the call as but be the pointer returned from `rd_kafka_conf_dup()` in librdkafka  ?

**Comment by arnaud-lb** [comment]
Thanks, should be fixed now
