### ISSUE TITLE
Error with PHP7

### ISSUE THREAD

**Issue by johann-chan** [php-rdkafka/php-rdkafka#9]
I compiled extension with php7, but i get this error when executing script 
PHP Warning:  PHP Startup: Unable to load dynamic library '/pathto/rdkafka.so' - /pathto/rdkafka.so: undefined symbol: zval_used_for_init in Unknown on line 0
Any idea to make it work ?
Thanks

**Comment by arnaud-lb** [comment]
@johann-chan I've just pushed an experimental branch that builds against PHP 7: https://github.com/arnaud-lb/php-rdkafka/tree/php7

**Comment by johann-chan** [comment]
thanks !
I will test it by end of week
