### ISSUE TITLE
is there a way to know the total message count of a partition ?

### ISSUE THREAD

**Issue by yourNameIsGood** [php-rdkafka/php-rdkafka#91]
I am just wondering , if there is way to get the total count of messages in an certain partition.

 * PHP version:
 * librdkafka version:
 * php-rdkfaka version:

**Comment by arnaud-lb** [comment]
Hi @yourNameIsGood 

You might be able to get an approximation by consuming the first and last message of each partition, and computing the difference.

Consuming the first message can be done by calling ->consume() with RD_KAFKA_OFFSET_BEGINNING as offset. For the last message, use rd_kafka_offset_tail(1) as offset.

The Message class has an offset property that you can use to compute the number of messages between the first and last message.

**Comment by yourNameIsGood** [comment]
Hi @arnaud-lb 
Thanks to your answer, problem solved. 
btw, it took some time before I use rd_kafka_offste_tail(1) to replace RD_KAFKA_OFFSET_BEGINNING because I thought it some function in a class...

**Comment by gam6itko** [comment]
Here an example how to solve this issue https://gist.github.com/gam6itko/b3b31332066beae851f9d2947832d24f
