### ISSUE TITLE
Possible Bug - Broker Address Always Defaults To 127.0.0.1

### ISSUE THREAD

**Issue by dragoonis** [php-rdkafka/php-rdkafka#92]
I cannot connect to brokers remotely. It always tries to use 127.0.0.1

I have tried this.

```
        $consumer = new Consumer($);
        $consumer->addBrokers('remote.ip');
```

I get this output:
```
%3|1479474432.952|FAIL|rdkafka#consumer-1| 127.0.0.1:9092/1001: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
```

I tried to add some topic conf

```
        $conf = new ConsumerConf();
        $conf->set('metadata.broker.list', 'remote.ip');
        $consumer = new Consumer($conf);
        $consumer->addBrokers('remote.ip');
```

I get same error:

```
%3|1479474432.952|FAIL|rdkafka#consumer-1| 127.0.0.1:9092/1001: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
```

 * PHP version:
 * librdkafka version: master branch (built today)
 * php-rdkfaka version: master branch (built today)

**Comment by dragoonis** [comment]
This was a misconfigured kafka advertised hosts setting.

**Comment by Jamesluo1** [comment]
i also meet this problem, but i checked my server configuration, the advertised host is not 127.0.0.1
