### ISSUE TITLE
Cannot Kafka Host on AWS 

### ISSUE THREAD

**Issue by dragoonis** [php-rdkafka/php-rdkafka#93]
I have an issue with hosting Kafka on AWS, and would like to know the apporach.

My advertised hosts file contains <external_ip>:9092. When the client connects to the server it gets given the advertised hosts external IP. The client tries to connect but nothing is happening. Why? because Kafka fails to bind to an external ELASTIC IP address on the box. It can only bind to the internal IP.

When updating the advertised hosts to the internal AWS IP it can bind fine. When the clients connect in, they get given the 10.x.x.x IP to connect back to, which of course doesn't exist for the clients since it's an internal IP.

Right now hosting kafka on AWS isn't viable and I'd like to know what the solution is going forward. What should be the value of advertised hosts setting? From what I can see this has to be an IP that the server can bind to, and one that the client can connect into.

@edenhill @arnaud-lb 

Kafka server 0.10
librdkafka (master)
php-rdkafka (master)
PHP version: 5.6

**Comment by edenhill** [comment]
There are two config properties for this purpose:
 * `listensers` define what local addresses and ports are bound (e.g., ':9092' for binding to all addresses)
 * ´advertised.listeners´ - what is being exposed to clients, the externally (and internally!) reachable address

**Comment by dragoonis** [comment]
Excellent. I will give this a try.

**Comment by dragoonis** [comment]
@edenhill @arnaud-lb it seems like the advertised.listeners value is also being read by zooekeeper, because it can't create the partitions unless it can resolve the hostname of advertised.listeners.

Is this expected behaviour?

I'm using docker, and have two hostnamed: `kafka` and `zookeeper`. If I set my advertised.listeners to `kafka` then zookeeper can resolve that. If I set it to the external elastic IP of the EC2 instance (so the consumers can dial in) then no partitions get built.

Is this making sense?

**Comment by stewartbryson** [comment]
Having the same issue @dragoonis. I can't seem to make everything happy. I assume if there was some way to make the Elastic IP routable from within the AWS instance/container, then we could just set listeners to the Elastic IP and everything would work.

**Comment by dragoonis** [comment]
So I basically had to hack the hosts file on the AWS EC2 box itself, and hack the hosts file on the client machine so that `kafka` pointed to the respective location.

Thus in the config files for kafka and such it all pointed to the hostname `kafka`.

On local: `kafka` pointed to the EC2 instance
On the ec2 instance `kafka` pointed either to itself 127.0.0.1 or its external IP. pretty sure it's the local one.

Hopefully you know what I mean by that. good luck.
