### ISSUE TITLE
New release with PHP 7.1 compatibility?

### ISSUE THREAD

**Issue by dzuelke** [php-rdkafka/php-rdkafka#94]
PHP 7.1 will be released in a week :)

Would it be possible to tag and release (here and on PECL) a 2.0.1 before then with the fixes from #71 ?

/cc @arnaud-lb @remicollet

**Comment by arnaud-lb** [comment]
Hi @dzuelke 

I'm working on supporting all PHP versions in the same branch: https://github.com/arnaud-lb/php-rdkafka/tree/common-code

Once it's stable I'll tag it and release a new PECL package.

**Comment by dzuelke** [comment]
Cool, does that mean a version 3.0.0 for both PHP 5 and PHP 7 or something? :)

Either way, would it still be possible to roll out an interim fix release with change 46bb170865fe8f478452cd943c37eed3c99cf903 from #71 so that the extension works with PHP 7.1? Would be really, really great to have that, ideally before 7.1.0 hits on Thursday.

And then you can take all the time you need with the "common code" branch :)

**Comment by arnaud-lb** [comment]
I've just tagged 2.0.1 and released a 2.0.1 on pecl :)

**Comment by dzuelke** [comment]
LOVE IT :) Thanks @arnaud-lb
