### ISSUE TITLE
Event loop integration

### ISSUE THREAD

**Issue by alexeyshockov** [php-rdkafka/php-rdkafka#97]
Current implementation contains only blocking methods for working with the server.

Is it even possible to provide a stream, that would be non-blocking and then suitable for event loops (with `stream_select()` or different backend)? I'm not familiar with the C library, but I hope :)

**Comment by arnaud-lb** [comment]
Hi!

There is a related bug/question here: https://github.com/arnaud-lb/php-rdkafka/issues/95

**Comment by alexeyshockov** [comment]
Thanks for pointing to the ticket!

`addTimer()` is not the best solution, because then you switch to pool system or block the whole app (in case of using timeout in `consume()` calls). It's a possible integration method, of course.

Is it even possible to librdkafka to expose a stream? Maybe I could work on a PR, but I have no idea about internals at the moment.

**Comment by arnaud-lb** [comment]
librdkafka itself doesn't expose a stream, but it could be possible to do it in the extension, at the C level.

Alternatively, you might want to look at [proxy-based clients](https://cwiki.apache.org/confluence/display/KAFKA/Clients#Clients-Proxy(HTTPREST,etc)). It would be possible to consume messages with the React HTTP client.

**Comment by alexeyshockov** [comment]
Thanks for the answer, will take a look at proxies.
